/* Grille d'évaluation — Production écrite, DELF B1 và B2.
 *
 * Đây là thang chấm chính thức của France Éducation international: mỗi tiêu chí
 * một số điểm, cộng lại đúng 25.
 *
 * ⚠️ ĐỐI CHIẾU VỚI BẢN IN CỦA BẠN trước khi tin tuyệt đối. Grille có chỉnh sửa
 * theo từng đợt cải cách, và một tiêu chí lệch 1 điểm là mọi bài chấm lệch
 * theo. Cấu trúc dưới đây theo bản đang lưu hành; tổng đã kiểm bằng
 * `check:grille`.
 *
 * File này không import gì, nên scripts/check-grille.mjs chạy thẳng bằng node.
 * Từng nằm ở supabase/functions/_shared/ khi còn hàm AI chấm; chuyển về đây khi
 * bỏ hàm đó — một bản duy nhất thì không có gì để trôi khỏi nhau.
 */

/* ⚠️ A1 và A2 là bản PHỎNG THEO, quy về thang 25 — nói rõ để không ai tưởng
 * đây là bản sao y grille chính thức.
 *
 * Đề thi thật ở hai trình độ này chia Production écrite thành HAI bài tập với
 * thang riêng (A1: điền phiếu 10đ + viết câu 15đ; A2: hai bài ~12–13đ). Hệ
 * thống của ta coi mỗi phần thi là một khối 25 điểm, nên giữ nguyên cấu trúc
 * đó sẽ không khớp.
 *
 * Với việc TỰ CHẤM thì phỏng theo là đủ và đúng mục đích: giá trị nằm ở chỗ
 * người học đọc lại bài mình theo từng tiêu chí, không nằm ở con số cuối. B1 và
 * B2 thì bám sát grille chính thức vì đó là hai trình độ hệ thống nhắm tới.
 */
export const GRILLE = {
  A1: {
    minWords: 40,
    consigne: "Remplir une fiche et rédiger quelques phrases simples sur soi ou son quotidien.",
    adapted: true,
    criteres: [
      { id: "consigne",  max: 3, label: "Respect de la consigne",
        label_vi: "Bám sát đề bài",
        aide: "Répond bien à ce qui est demandé et respecte la longueur indiquée.",
        aide_vi: "Trả lời đúng thứ đề hỏi, và viết đủ số từ yêu cầu." },
      { id: "fiche",     max: 3, label: "Capacité à remplir une fiche",
        label_vi: "Điền phiếu thông tin",
        aide: "Donne nom, âge, nationalité, adresse ou profession sans se tromper de case.",
        aide_vi: "Điền đúng ô: họ tên, tuổi, quốc tịch, địa chỉ hoặc nghề nghiệp." },
      { id: "informer",  max: 6, label: "Capacité à informer et à décrire",
        label_vi: "Giới thiệu và mô tả",
        aide: "Écrit des phrases simples sur soi, ses goûts, ses activités.",
        aide_vi: "Viết được câu đơn giản về bản thân, sở thích và việc mình làm." },
      { id: "lexique",   max: 5, label: "Lexique et orthographe lexicale",
        label_vi: "Vốn từ và mặt chữ",
        aide: "Utilise un répertoire élémentaire de mots isolés et d'expressions.",
        aide_vi: "Dùng được vốn từ cơ bản — từ rời và vài cụm quen thuộc." },
      { id: "morpho",    max: 5, label: "Morphosyntaxe et orthographe grammaticale",
        label_vi: "Hợp giống–số và chia động từ",
        aide: "Emploie avec un contrôle limité des structures et des formes apprises.",
        aide_vi: "Dùng được các cấu trúc đã học; còn sai nhưng vẫn hiểu được." },
      { id: "coherence", max: 3, label: "Cohérence et cohésion",
        label_vi: "Mạch lạc và liên kết",
        aide: "Relie les mots avec des connecteurs très élémentaires : et, alors, mais.",
        aide_vi: "Nối câu bằng những từ đơn giản nhất: et, alors, mais." },
    ],
  },
  A2: {
    minWords: 60,
    consigne: "Décrire un événement ou une expérience, et écrire un message simple (invitation, remerciement, excuse).",
    adapted: true,
    criteres: [
      { id: "consigne",     max: 2, label: "Respect de la consigne",
        label_vi: "Bám sát đề bài",
        aide: "Respecte la situation, le type de message et la longueur demandée.",
        aide_vi: "Đúng tình huống, đúng loại tin nhắn, và đủ độ dài đề yêu cầu." },
      { id: "raconter",     max: 4, label: "Capacité à raconter et à décrire",
        label_vi: "Kể lại và mô tả",
        aide: "Décrit des activités passées ou des expériences personnelles.",
        aide_vi: "Kể lại được việc đã làm hoặc một trải nghiệm của mình." },
      { id: "impressions",  max: 3, label: "Capacité à donner ses impressions",
        label_vi: "Nói cảm nhận của mình",
        aide: "Communique sommairement ce qu'il ou elle a ressenti.",
        aide_vi: "Nói được sơ lược mình thấy thế nào — thích hay không thích, vì sao." },
      { id: "coherence",    max: 2, label: "Cohérence et cohésion",
        label_vi: "Mạch lạc và liên kết",
        aide: "Relie des énoncés avec des connecteurs simples : et, mais, parce que.",
        aide_vi: "Nối các câu bằng connecteur đơn giản: et, mais, parce que." },
      { id: "etendue_lex",  max: 2, label: "Étendue du vocabulaire",
        label_vi: "Vốn từ rộng",
        aide: "Vocabulaire suffisant pour les situations de la vie quotidienne.",
        aide_vi: "Vốn từ đủ dùng cho các tình huống đời thường." },
      { id: "maitrise_lex", max: 2, label: "Maîtrise du vocabulaire",
        label_vi: "Dùng từ chính xác",
        aide: "Contrôle restreint mais suffisant pour être compris.",
        aide_vi: "Còn nhầm từ, nhưng người đọc vẫn hiểu đúng ý." },
      { id: "orthographe",  max: 2, label: "Orthographe lexicale",
        label_vi: "Chính tả và dấu câu",
        aide: "Copie correctement de courtes expressions et des mots courants.",
        aide_vi: "Viết đúng chính tả các từ quen thuộc và cụm ngắn." },
      { id: "phrases",      max: 2, label: "Degré d'élaboration des phrases",
        label_vi: "Cấu trúc câu",
        aide: "Produit des phrases simples, parfois reliées.",
        aide_vi: "Viết câu đơn, thỉnh thoảng nối được hai câu với nhau." },
      { id: "temps",        max: 3, label: "Choix des temps et des modes",
        label_vi: "Thì và thức",
        aide: "Emploie le présent et le passé composé de façon globalement correcte.",
        aide_vi: "Dùng présent và passé composé nhìn chung đúng." },
      { id: "morpho",       max: 3, label: "Morphosyntaxe",
        label_vi: "Hợp giống–số và chia động từ",
        aide: "Accords simples, déterminants, formes verbales apprises.",
        aide_vi: "Hợp giống–số cơ bản, mạo từ, và các dạng động từ đã học." },
    ],
  },
  B1: {
    minWords: 160,
    consigne: "Essai, courrier ou article d'environ 160 mots exprimant un point de vue.",
    criteres: [
      { id: "consigne",     max: 2, label: "Respect de la consigne",
        label_vi: "Bám sát đề bài",
        aide: "Respecte la situation, le type d'écrit et la longueur demandée.",
        aide_vi: "Đúng loại văn bản đề yêu cầu, đúng tình huống và người nhận, đủ 160 từ." },
      { id: "faits",        max: 4, label: "Capacité à présenter des faits",
        label_vi: "Trình bày sự việc",
        aide: "Décrit des faits, des événements ou des expériences de façon compréhensible.",
        aide_vi: "Kể được sự việc rõ ràng, để người chưa biết gì cũng theo được." },
      { id: "pensee",       max: 4, label: "Capacité à exprimer sa pensée",
        label_vi: "Nói ra suy nghĩ của mình",
        aide: "Présente ses idées, ses sentiments et/ou ses réactions et donne son opinion.",
        aide_vi: "Nói ra được mình nghĩ gì và vì sao, kèm ví dụ từ đời sống của mình." },
      { id: "coherence",    max: 3, label: "Cohérence et cohésion",
        label_vi: "Mạch lạc và liên kết",
        aide: "Enchaîne une série d'éléments courts, simples et distincts en un discours qui s'enchaîne.",
        aide_vi: "Bài có bố cục và các câu nối vào nhau; B1 cần khoảng 5–6 connecteur khác nhau." },
      { id: "etendue_lex",  max: 2, label: "Étendue du vocabulaire",
        label_vi: "Vốn từ rộng",
        aide: "Utilise un répertoire élémentaire mais suffisant pour le sujet.",
        aide_vi: "Vốn từ đủ rộng cho chủ đề, và biết đổi cách nói để không lặp." },
      { id: "maitrise_lex", max: 2, label: "Maîtrise du vocabulaire",
        label_vi: "Dùng từ chính xác",
        aide: "Le vocabulaire est globalement correct malgré des confusions.",
        aide_vi: "Dùng từ đúng nghĩa; còn nhầm nhưng không gây hiểu sai." },
      { id: "orthographe",  max: 1, label: "Maîtrise de l'orthographe lexicale",
        label_vi: "Chính tả và dấu câu",
        aide: "Orthographe, ponctuation et mise en page assez justes pour être suivies.",
        aide_vi: "Chính tả, dấu câu và cách trình bày đủ chuẩn để người đọc theo được." },
      { id: "phrases",      max: 2, label: "Degré d'élaboration des phrases",
        label_vi: "Cấu trúc câu",
        aide: "Produit des phrases simples et complexes.",
        aide_vi: "Viết được cả câu đơn lẫn câu phức, không chỉ toàn câu ngắn nối bằng et." },
      { id: "temps",        max: 2, label: "Choix des temps et des modes",
        label_vi: "Thì và thức",
        aide: "Fait preuve d'un bon contrôle malgré de nettes influences de la langue maternelle.",
        aide_vi: "Chọn đúng thì và thức; kiểm soát tốt dù còn ảnh hưởng của tiếng mẹ đẻ." },
      { id: "morpho",       max: 3, label: "Morphosyntaxe — orthographe grammaticale",
        label_vi: "Hợp giống–số và chia động từ",
        aide: "Accord en genre et nombre, pronoms, marques verbales.",
        aide_vi: "Hợp giống–số, đại từ, đuôi động từ. Ở B1 đây là tiêu chí nặng thứ hai." },
    ],
  },
  B2: {
    minWords: 250,
    consigne: "Texte argumenté d'environ 250 mots (contribution, lettre formelle, article).",
    criteres: [
      { id: "consigne",     max: 2, label: "Respect de la consigne",
        label_vi: "Bám sát đề bài",
        aide: "Respecte la situation, le type d'écrit et la longueur indiquée.",
        aide_vi: "Đúng loại văn bản, đúng người nhận, và đủ độ dài 250 từ." },
      { id: "sociolang",    max: 2, label: "Correction sociolinguistique",
        label_vi: "Chọn đúng giọng văn",
        aide: "Adapte le registre à la situation et au destinataire.",
        aide_vi: "Giọng văn hợp với người nhận và giữ đều cả bài — vous hay tu, trang trọng hay thân mật." },
      { id: "faits",        max: 3, label: "Capacité à présenter des faits",
        label_vi: "Trình bày sự việc",
        aide: "Évoque avec clarté et précision faits, événements ou situations.",
        aide_vi: "Nêu sự việc rõ và chính xác, có con số hoặc mốc thời gian, và phục vụ lập luận." },
      { id: "argumenter",   max: 4, label: "Capacité à argumenter",
        label_vi: "Lập luận",
        aide: "Développe une argumentation, souligne les points importants, illustre par des exemples.",
        aide_vi: "Luận điểm phát triển đầy đủ, có ví dụ minh hoạ, và trả lời được ý kiến ngược lại." },
      { id: "coherence",    max: 3, label: "Cohérence et cohésion",
        label_vi: "Mạch lạc và liên kết",
        aide: "Utilise avec efficacité une gamme étendue de connecteurs.",
        aide_vi: "Bố cục rõ và connecteur đa dạng; B2 cần 8–10 loại, gồm cả toutefois, en revanche." },
      { id: "etendue_lex",  max: 2, label: "Étendue du vocabulaire",
        label_vi: "Vốn từ rộng",
        aide: "Vocabulaire étendu, variations pour éviter les répétitions.",
        aide_vi: "Vốn từ rộng, có từ riêng của chủ đề, và biết biến đổi để tránh lặp." },
      { id: "maitrise_lex", max: 2, label: "Maîtrise du vocabulaire",
        label_vi: "Dùng từ chính xác",
        aide: "Peu d'erreurs, aucune ne gêne la compréhension.",
        aide_vi: "Rất ít lỗi dùng từ, và không lỗi nào gây hiểu sai." },
      { id: "orthographe",  max: 1, label: "Maîtrise de l'orthographe",
        label_vi: "Chính tả và dấu câu",
        aide: "Orthographe et ponctuation relativement exactes.",
        aide_vi: "Chính tả và dấu câu tương đối chuẩn." },
      { id: "phrases",      max: 2, label: "Degré d'élaboration des phrases",
        label_vi: "Cấu trúc câu",
        aide: "Variété de structures, y compris complexes.",
        aide_vi: "Nhiều kiểu cấu trúc khác nhau, kể cả câu phức." },
      { id: "temps",        max: 2, label: "Choix des temps et des modes",
        label_vi: "Thì và thức",
        aide: "Bon contrôle, erreurs non systématiques.",
        aide_vi: "Kiểm soát tốt thì và thức; ở B2 subjonctif là thứ được mong đợi, không phải điểm cộng." },
      { id: "morpho",       max: 2, label: "Morphosyntaxe",
        label_vi: "Hợp giống–số và chia động từ",
        aide: "Bon contrôle grammatical, erreurs occasionnelles sans malentendu.",
        aide_vi: "Kiểm soát ngữ pháp tốt; lỗi thưa và không gây hiểu nhầm." },
    ],
  },
};

export const tongDiem = (level) =>
  (GRILLE[level]?.criteres ?? []).reduce((n, c) => n + c.max, 0);
