/* Kho câu « Nghe & Nói » (10/10). Nội dung học: KHÔNG dùng dấu gạch dài.
 * [cấp, câu tiếng Pháp, nghĩa tiếng Việt, mẹo (chỉ phát âm)] */

export const CHINH_TA = [
  ["A1", "Je m'appelle Léa et j'habite à Lyon.", "Tôi tên là Léa và tôi sống ở Lyon."],
  ["A1", "Nous avons un chat noir.", "Chúng tôi có một con mèo đen."],
  ["A1", "Il fait beau aujourd'hui.", "Hôm nay trời đẹp."],
  ["A1", "Le magasin ouvre à neuf heures.", "Cửa hàng mở cửa lúc chín giờ."],
  ["A1", "Ma sœur aime le chocolat.", "Chị gái tôi thích sô-cô-la."],
  ["A1", "Où est la gare, s'il vous plaît ?", "Làm ơn cho hỏi nhà ga ở đâu?"],
  ["A1", "Je voudrais un café et un croissant.", "Tôi muốn một ly cà phê và một chiếc bánh sừng bò."],
  ["A1", "Elle a vingt-deux ans.", "Cô ấy hai mươi hai tuổi."],
  ["A1", "Mes parents travaillent à Paris.", "Bố mẹ tôi làm việc ở Paris."],
  ["A1", "Le samedi, je joue au football.", "Thứ Bảy, tôi chơi bóng đá."],
  ["A2", "Hier, nous sommes allés au cinéma avec des amis.", "Hôm qua chúng tôi đi xem phim với bạn bè."],
  ["A2", "Quand j'étais petit, je vivais à la campagne.", "Khi còn nhỏ, tôi sống ở nông thôn."],
  ["A2", "Il faut prendre le bus numéro douze.", "Phải đi xe buýt số mười hai."],
  ["A2", "Elle s'est levée très tôt ce matin.", "Sáng nay cô ấy dậy rất sớm."],
  ["A2", "Nous allons partir en vacances au mois d'août.", "Chúng tôi sẽ đi nghỉ vào tháng Tám."],
  ["A2", "Je n'ai pas encore fini mes devoirs.", "Tôi vẫn chưa làm xong bài tập."],
  ["A2", "Le restaurant était plein, alors nous avons mangé ailleurs.", "Nhà hàng kín chỗ, nên chúng tôi ăn ở chỗ khác."],
  ["A2", "Tu peux m'envoyer l'adresse par message ?", "Bạn gửi địa chỉ cho tôi qua tin nhắn được không?"],
  ["A2", "Les enfants jouent dans le jardin depuis une heure.", "Bọn trẻ chơi trong vườn được một tiếng rồi."],
  ["A2", "J'ai acheté une robe bleue pour la fête.", "Tôi đã mua một chiếc váy xanh cho bữa tiệc."],
  ["B1", "Si j'avais plus de temps, j'apprendrais une autre langue.", "Nếu có nhiều thời gian hơn, tôi sẽ học thêm một ngoại ngữ."],
  ["B1", "Il faut que tu fasses attention à la circulation.", "Bạn phải chú ý giao thông."],
  ["B1", "Les jeunes passent de plus en plus de temps sur leur téléphone.", "Giới trẻ dành ngày càng nhiều thời gian cho điện thoại."],
  ["B1", "Bien qu'il pleuve, nous sommes sortis nous promener.", "Dù trời mưa, chúng tôi vẫn ra ngoài đi dạo."],
  ["B1", "Je pense que cette solution est la plus efficace.", "Tôi nghĩ giải pháp này hiệu quả nhất."],
  ["B1", "Elle m'a dit qu'elle viendrait plus tard.", "Cô ấy bảo tôi là cô ấy sẽ đến muộn hơn."],
  ["B1", "Le train a été annulé à cause de la grève.", "Chuyến tàu bị huỷ vì đình công."],
  ["B1", "Nous devrions réduire nos déchets au quotidien.", "Chúng ta nên giảm rác thải hằng ngày."],
  ["B1", "Après avoir terminé ses études, il a trouvé un emploi.", "Sau khi học xong, anh ấy đã tìm được việc làm."],
  ["B1", "C'est le livre dont je t'ai parlé hier.", "Đây là cuốn sách tôi đã kể với bạn hôm qua."],
  ["B2", "Il est indispensable que chacun prenne conscience de l'urgence climatique.", "Mỗi người cần nhận thức được tính cấp bách của vấn đề khí hậu."],
  ["B2", "Les mesures prises par le gouvernement ont suscité de vives réactions.", "Các biện pháp của chính phủ đã gây ra phản ứng gay gắt."],
  ["B2", "Bien que le télétravail présente des avantages, il favorise l'isolement.", "Dù làm việc từ xa có những lợi ích, nó lại dễ gây cô lập."],
  ["B2", "Encore faudrait-il que les moyens financiers soient suffisants.", "Còn phải có đủ nguồn lực tài chính đã."],
  ["B2", "Les réseaux sociaux ont profondément transformé notre rapport à l'information.", "Mạng xã hội đã thay đổi sâu sắc cách chúng ta tiếp cận thông tin."],
  ["B2", "Il aurait fallu anticiper davantage les conséquences de cette décision.", "Lẽ ra cần lường trước nhiều hơn hậu quả của quyết định này."],
  ["B2", "La plupart des experts s'accordent à dire que la situation s'améliore.", "Phần lớn chuyên gia đồng ý rằng tình hình đang cải thiện."],
  ["B2", "Quels que soient les obstacles, ils ont poursuivi leur projet.", "Dù gặp trở ngại gì, họ vẫn theo đuổi dự án."],
  ["B2", "Cette initiative, saluée par les associations, reste néanmoins insuffisante.", "Sáng kiến này được các hội đoàn hoan nghênh nhưng vẫn chưa đủ."],
  ["B2", "On ne saurait nier l'importance de l'éducation dans la lutte contre les inégalités.", "Không thể phủ nhận vai trò của giáo dục trong cuộc chiến chống bất bình đẳng."],
];

export const PHAT_AM = [
  ["A1", "Bonjour, je suis content de vous voir.", "Xin chào, tôi rất vui được gặp bạn.", "Âm mũi « on » trong bonjour, content: khép môi tròn, đẩy hơi qua mũi."],
  ["A1", "Un bon vin blanc.", "Một ly rượu vang trắng ngon.", "Ba âm mũi khác nhau: « un », « on », « in/an ». Đừng đọc thêm âm n ở cuối."],
  ["A1", "Tu as vu la rue ?", "Bạn đã thấy con phố chưa?", "Âm « u »: môi tròn như nói « u » nhưng lưỡi đặt như « i »."],
  ["A1", "Où est la roue rouge ?", "Bánh xe màu đỏ ở đâu?", "Âm « ou » giống « u » tiếng Việt; phân biệt với « u » ở câu trước."],
  ["A1", "Le rat rentre dans la rivière.", "Con chuột chạy vào dòng sông.", "Âm « r » rung ở cuống họng, không cong lưỡi như tiếng Anh."],
  ["A1", "Il y a deux euros sur la table.", "Có hai euro trên bàn.", "Âm « eu » trong deux, euros: môi tròn, lưỡi đặt như « ê »."],
  ["A1", "Mon ami arrive à midi.", "Bạn tôi đến lúc trưa.", "Nối âm: « mon ami » đọc liền thành « mo-na-mi »."],
  ["A1", "Les enfants aiment les oiseaux.", "Bọn trẻ thích chim.", "Nối âm z: « les enfants », « les oiseaux » đọc « lê-zan-fan », « lê-zoa-zô »."],
  ["A1", "Je prends le train de huit heures.", "Tôi đi chuyến tàu tám giờ.", "« huit heures » nối thành « ui-teur »; « h » không đọc."],
  ["A1", "Merci beaucoup, monsieur.", "Cảm ơn ông rất nhiều.", "« monsieur » đọc gần « mơ-xiơ », không đọc chữ n và r."],
  ["A2", "Je voudrais réserver une chambre pour deux nuits.", "Tôi muốn đặt một phòng cho hai đêm.", "Phân biệt « u » trong une, nuits với « ou » trong voudrais, pour."],
  ["A2", "Il pleut depuis ce matin.", "Trời mưa từ sáng.", "« pleut » và « depuis »: hai âm eu và ui, giữ môi tròn."],
  ["A2", "Nous habitons au premier étage.", "Chúng tôi sống ở tầng một.", "Nối âm « nous habitons » thành « nu-za-bi-ton »."],
  ["A2", "Elle a acheté du pain et du fromage.", "Cô ấy đã mua bánh mì và pho mát.", "« pain » âm mũi « in », « du » âm « u »; cuối « fromage » đọc nhẹ âm j."],
  ["A2", "Ils ont eu un accident hier soir.", "Tối qua họ bị tai nạn.", "« ils ont » nối z; « ont » và « sont » khác nhau ở âm z và s."],
  ["A2", "Ce gâteau est vraiment délicieux.", "Chiếc bánh này thật ngon.", "« vraiment »: r ở cổ họng ngay sau v; « délicieux » kết thúc bằng âm eu."],
  ["A2", "J'aime écouter de la musique le soir.", "Tôi thích nghe nhạc vào buổi tối.", "« musique » có âm « u »; « écouter » có âm « ou »."],
  ["A2", "Le cours commence à quatorze heures.", "Tiết học bắt đầu lúc mười bốn giờ.", "« quatorze heures » nối thành « ca-tor-zeur »."],
  ["A2", "Ma grand-mère vit dans un petit village.", "Bà tôi sống ở một ngôi làng nhỏ.", "Âm mũi « an » trong grand, dans; « un » trong un."],
  ["A2", "Vous pouvez répéter plus lentement ?", "Bạn có thể nhắc lại chậm hơn không?", "« plus » trước tính từ không đọc s; « lentement » hai âm mũi « an »."],
  ["B1", "Je suis tout à fait d'accord avec vous.", "Tôi hoàn toàn đồng ý với bạn.", "« tout à fait » nối t: « tu-ta-fè »."],
  ["B1", "À mon avis, il faudrait changer les habitudes.", "Theo tôi, cần thay đổi thói quen.", "Hai chỗ nối: « mon avis », « les habitudes »."],
  ["B1", "Les transports en commun sont souvent en retard.", "Phương tiện công cộng thường bị trễ.", "« en commun » nối n; chú ý ba âm mũi khác nhau."],
  ["B1", "Il est important de protéger l'environnement.", "Bảo vệ môi trường là điều quan trọng.", "« est important » nối t; « environnement » có ba âm mũi."],
  ["B1", "Nous avons longtemps hésité avant de partir.", "Chúng tôi đã do dự rất lâu trước khi đi.", "« avons » nối z sau « nous »; « longtemps » hai âm mũi « on » và « an »."],
  ["B1", "Pourriez-vous m'expliquer la situation ?", "Bạn có thể giải thích tình hình cho tôi không?", "« pourriez » r đôi đọc một lần ở cổ họng; « situation » có âm « u »."],
  ["B1", "Les jeunes utilisent beaucoup les réseaux sociaux.", "Giới trẻ dùng mạng xã hội rất nhiều.", "« les jeunes » không nối vì j; « utilisent » bắt đầu bằng âm « u »."],
  ["B1", "Je regrette de ne pas être venu plus tôt.", "Tôi tiếc vì đã không đến sớm hơn.", "Âm e câm trong « regrette », « de », « ne » đọc rất nhẹ."],
  ["B1", "Cette nouvelle a surpris tout le monde.", "Tin này làm mọi người bất ngờ.", "« surpris » u + r; « monde » âm mũi « on »."],
  ["B1", "Il vaut mieux réfléchir avant d'agir.", "Tốt hơn là nên suy nghĩ trước khi hành động.", "« mieux » âm eu; « réfléchir » r đầu câu ở cổ họng."],
  ["B2", "Il est indéniable que les inégalités se creusent.", "Không thể phủ nhận rằng bất bình đẳng ngày càng sâu sắc.", "« est indéniable » nối t; « inégalités » bắt đầu bằng âm mũi « in »."],
  ["B2", "Cette réforme suscite une vive inquiétude chez les étudiants.", "Cuộc cải cách này gây lo ngại lớn cho sinh viên.", "« suscite » và « une »: âm « u »; « les étudiants » nối z."],
  ["B2", "On ne peut pas nier l'influence croissante des écrans.", "Không thể phủ nhận ảnh hưởng ngày càng lớn của màn hình.", "« influence » hai âm mũi; « des écrans » nối z."],
  ["B2", "Les pouvoirs publics doivent intervenir sans tarder.", "Chính quyền phải can thiệp ngay.", "« pouvoirs » âm ou + oa; « intervenir » âm mũi « in » ở đầu."],
  ["B2", "Il aurait été préférable d'en discuter auparavant.", "Lẽ ra nên bàn chuyện này từ trước.", "« aurait été » nối t; « auparavant » kết thúc âm mũi « an »."],
  ["B2", "La transition énergétique représente un défi majeur.", "Chuyển đổi năng lượng là một thách thức lớn.", "« transition » âm mũi « an »; « un défi » không nối."],
  ["B2", "Force est de constater que les habitudes évoluent lentement.", "Buộc phải thừa nhận rằng thói quen thay đổi chậm.", "« Force est » nối s nhẹ; « les habitudes » nối z."],
  ["B2", "Cet argument, bien qu'intéressant, mérite d'être nuancé.", "Lập luận này tuy thú vị nhưng cần được nói rõ hơn.", "« bien qu'intéressant » nối liền; « nuancé » âm « u » rồi âm mũi « an »."],
  ["B2", "Nombreux sont ceux qui réclament davantage de transparence.", "Nhiều người đòi hỏi minh bạch hơn.", "« nombreux » âm mũi « on » + eu; « transparence » hai âm mũi « an »."],
  ["B2", "Il convient néanmoins de rester prudent face à ces chiffres.", "Tuy nhiên cần thận trọng trước những con số này.", "« néanmoins » ba âm mũi liền nhau: « an », « oin »; « prudent » u + an."],
];
