/* Kho câu bổ sung (10/10): thêm 40 câu mỗi trình độ cho mỗi loại, đủ 200 + 200.
 * Nội dung học: KHÔNG dùng dấu gạch dài. [cấp, câu, nghĩa, mẹo] */

export const CHINH_TA_2 = [
  // A1
  ["A1", "Je bois du thé le matin.", "Buổi sáng tôi uống trà."],
  ["A1", "Nous habitons dans une petite maison.", "Chúng tôi sống trong một ngôi nhà nhỏ."],
  ["A1", "Mon frère a un vélo rouge.", "Anh trai tôi có một chiếc xe đạp màu đỏ."],
  ["A1", "La banque ferme à cinq heures.", "Ngân hàng đóng cửa lúc năm giờ."],
  ["A1", "J'aime beaucoup la musique.", "Tôi rất thích âm nhạc."],
  ["A1", "Il y a trois chaises dans la cuisine.", "Có ba cái ghế trong bếp."],
  ["A1", "Elle porte une jupe verte.", "Cô ấy mặc một chiếc váy màu xanh lá."],
  ["A1", "Le chien dort sous la table.", "Con chó ngủ dưới gầm bàn."],
  ["A1", "Nous mangeons à midi.", "Chúng tôi ăn trưa lúc mười hai giờ."],
  ["A1", "Tu as quel âge ?", "Bạn bao nhiêu tuổi?"],
  ["A1", "Je vais à l'école à pied.", "Tôi đi bộ đến trường."],
  ["A1", "Il pleut beaucoup en novembre.", "Tháng Mười Một mưa nhiều."],
  ["A1", "Ma mère est professeur.", "Mẹ tôi là giáo viên."],
  ["A1", "Le bus arrive dans dix minutes.", "Xe buýt đến trong mười phút nữa."],
  ["A1", "J'ai deux sœurs et un frère.", "Tôi có hai chị em gái và một anh trai."],
  ["A1", "Nous regardons la télévision le soir.", "Buổi tối chúng tôi xem ti vi."],
  ["A1", "Elle parle français et anglais.", "Cô ấy nói tiếng Pháp và tiếng Anh."],
  ["A1", "Le pain est sur la table.", "Bánh mì ở trên bàn."],
  ["A1", "Je cherche la pharmacie.", "Tôi đang tìm hiệu thuốc."],
  ["A1", "Il travaille dans un hôpital.", "Anh ấy làm việc ở một bệnh viện."],
  ["A1", "Les enfants vont à la piscine.", "Bọn trẻ đi bể bơi."],
  ["A1", "Mon anniversaire est en juillet.", "Sinh nhật tôi vào tháng Bảy."],
  ["A1", "Combien coûte ce livre ?", "Cuốn sách này giá bao nhiêu?"],
  ["A1", "Je prends une douche le soir.", "Tôi tắm vào buổi tối."],
  ["A1", "La fenêtre est ouverte.", "Cửa sổ đang mở."],
  ["A1", "Nous partons demain matin.", "Sáng mai chúng tôi đi."],
  ["A1", "Il a les cheveux courts.", "Anh ấy để tóc ngắn."],
  ["A1", "J'achète des pommes au marché.", "Tôi mua táo ở chợ."],
  ["A1", "Ma chambre est au premier étage.", "Phòng tôi ở tầng một."],
  ["A1", "Elle écoute la radio dans la voiture.", "Cô ấy nghe đài trong xe."],
  ["A1", "Le film commence à vingt heures.", "Bộ phim bắt đầu lúc hai mươi giờ."],
  ["A1", "Je n'aime pas le lait.", "Tôi không thích sữa."],
  ["A1", "Nos voisins sont très gentils.", "Hàng xóm của chúng tôi rất tốt bụng."],
  ["A1", "Il fait froid en hiver.", "Mùa đông trời lạnh."],
  ["A1", "Tu veux un verre d'eau ?", "Bạn muốn một cốc nước không?"],
  ["A1", "La poste est à côté de la mairie.", "Bưu điện ở cạnh toà thị chính."],
  ["A1", "Je fais mes devoirs après l'école.", "Tôi làm bài tập sau giờ học."],
  ["A1", "Elle a un petit chien blanc.", "Cô ấy có một con chó nhỏ màu trắng."],
  ["A1", "Nous allons au parc le dimanche.", "Chủ nhật chúng tôi đi công viên."],
  ["A1", "Le café est très chaud.", "Cà phê rất nóng."],
  // A2
  ["A2", "L'année dernière, nous avons visité la Bretagne.", "Năm ngoái chúng tôi đã đi thăm vùng Bretagne."],
  ["A2", "Il faisait beau quand nous sommes arrivés.", "Trời đẹp khi chúng tôi đến nơi."],
  ["A2", "Je me suis réveillé trop tard ce matin.", "Sáng nay tôi dậy quá muộn."],
  ["A2", "Elle a perdu ses clés dans le métro.", "Cô ấy đánh rơi chìa khoá trên tàu điện ngầm."],
  ["A2", "Nous allons faire une fête samedi prochain.", "Thứ Bảy tới chúng tôi sẽ tổ chức tiệc."],
  ["A2", "Le médecin m'a conseillé de me reposer.", "Bác sĩ khuyên tôi nghỉ ngơi."],
  ["A2", "Il y avait beaucoup de monde au concert.", "Buổi hoà nhạc rất đông người."],
  ["A2", "Je suis né dans une petite ville du sud.", "Tôi sinh ra ở một thị trấn nhỏ miền Nam."],
  ["A2", "Ils ont déménagé il y a deux mois.", "Họ chuyển nhà cách đây hai tháng."],
  ["A2", "Pouvez-vous fermer la porte, s'il vous plaît ?", "Bạn làm ơn đóng cửa giúp được không?"],
  ["A2", "Le train pour Marseille part de la voie trois.", "Tàu đi Marseille khởi hành ở đường ray số ba."],
  ["A2", "Nous avons mangé une excellente pizza hier soir.", "Tối qua chúng tôi đã ăn một chiếc pizza tuyệt ngon."],
  ["A2", "Elle apprend à conduire depuis septembre.", "Cô ấy học lái xe từ tháng Chín."],
  ["A2", "Je préfère la mer à la montagne.", "Tôi thích biển hơn núi."],
  ["A2", "Mon grand-père racontait souvent des histoires.", "Ông tôi thường kể chuyện."],
  ["A2", "Il faut réserver la table à l'avance.", "Phải đặt bàn trước."],
  ["A2", "Nous n'avons pas trouvé de place pour nous garer.", "Chúng tôi không tìm được chỗ đỗ xe."],
  ["A2", "Le magasin est fermé le lundi matin.", "Cửa hàng đóng cửa sáng thứ Hai."],
  ["A2", "J'ai oublié mon parapluie chez toi.", "Tôi để quên ô ở nhà bạn."],
  ["A2", "Elle s'occupe de ses petits frères le mercredi.", "Thứ Tư cô ấy trông các em trai."],
  ["A2", "Nous avons passé une semaine à la campagne.", "Chúng tôi đã ở nông thôn một tuần."],
  ["A2", "Tu devrais prendre un manteau, il fait froid.", "Bạn nên mặc áo khoác, trời lạnh đấy."],
  ["A2", "Le professeur nous a donné beaucoup d'exercices.", "Thầy giáo cho chúng tôi rất nhiều bài tập."],
  ["A2", "Je voudrais changer de l'argent.", "Tôi muốn đổi tiền."],
  ["A2", "Il est tombé de vélo en rentrant de l'école.", "Cậu ấy bị ngã xe đạp khi đi học về."],
  ["A2", "Nous attendons le bus depuis vingt minutes.", "Chúng tôi chờ xe buýt đã hai mươi phút."],
  ["A2", "Elle a acheté un cadeau pour sa mère.", "Cô ấy đã mua quà cho mẹ."],
  ["A2", "Les magasins sont plus chers en centre-ville.", "Cửa hàng ở trung tâm thành phố đắt hơn."],
  ["A2", "J'ai rendez-vous chez le dentiste jeudi.", "Thứ Năm tôi có hẹn với nha sĩ."],
  ["A2", "Quand il était jeune, il jouait du piano.", "Hồi trẻ anh ấy chơi đàn piano."],
  ["A2", "Nous allons nous promener au bord du lac.", "Chúng tôi sẽ đi dạo bên hồ."],
  ["A2", "Le musée est gratuit le premier dimanche du mois.", "Bảo tàng miễn phí vào Chủ nhật đầu tháng."],
  ["A2", "Je ne connais pas encore mes nouveaux collègues.", "Tôi chưa quen các đồng nghiệp mới."],
  ["A2", "Elle a envoyé une carte postale à ses amis.", "Cô ấy đã gửi bưu thiếp cho bạn bè."],
  ["A2", "Il faut éteindre la lumière en partant.", "Phải tắt đèn khi ra về."],
  ["A2", "Nous avons regardé un match de football à la télé.", "Chúng tôi đã xem một trận bóng đá trên ti vi."],
  ["A2", "Ma voisine m'a prêté son aspirateur.", "Chị hàng xóm cho tôi mượn máy hút bụi."],
  ["A2", "Le vol a été retardé à cause du brouillard.", "Chuyến bay bị hoãn vì sương mù."],
  ["A2", "Je me couche toujours avant minuit.", "Tôi luôn đi ngủ trước nửa đêm."],
  ["A2", "Ils ont fêté leur mariage dans un château.", "Họ tổ chức đám cưới trong một lâu đài."],
  // B1
  ["B1", "Je me demande s'il viendra à la réunion.", "Tôi tự hỏi liệu anh ấy có đến cuộc họp không."],
  ["B1", "Il est possible que le magasin soit fermé.", "Có thể cửa hàng đã đóng cửa."],
  ["B1", "Nous aurions dû partir plus tôt.", "Lẽ ra chúng tôi nên đi sớm hơn."],
  ["B1", "Elle cherche un logement près de son travail.", "Cô ấy đang tìm chỗ ở gần nơi làm việc."],
  ["B1", "Depuis qu'il fait du sport, il dort mieux.", "Từ khi chơi thể thao, anh ấy ngủ ngon hơn."],
  ["B1", "Je vous écris pour réserver une chambre double.", "Tôi viết thư để đặt một phòng đôi."],
  ["B1", "Les prix ont beaucoup augmenté cette année.", "Năm nay giá cả tăng nhiều."],
  ["B1", "Pendant que je cuisinais, les enfants jouaient.", "Trong lúc tôi nấu ăn, bọn trẻ chơi đùa."],
  ["B1", "Il a décidé de changer de métier à quarante ans.", "Anh ấy quyết định đổi nghề ở tuổi bốn mươi."],
  ["B1", "Je ne crois pas qu'elle ait raison.", "Tôi không nghĩ là cô ấy đúng."],
  ["B1", "La réunion a été reportée à la semaine prochaine.", "Cuộc họp được dời sang tuần sau."],
  ["B1", "Nous avons fait du bénévolat dans une association.", "Chúng tôi đã làm tình nguyện ở một hội đoàn."],
  ["B1", "Ce quartier est devenu beaucoup plus animé.", "Khu phố này đã trở nên sôi động hơn nhiều."],
  ["B1", "Il faudrait que nous parlions de ce problème.", "Chúng ta cần nói chuyện về vấn đề này."],
  ["B1", "Elle a obtenu son diplôme avec mention.", "Cô ấy tốt nghiệp loại khá giỏi."],
  ["B1", "À force de travailler, il a fini par réussir.", "Nhờ chăm chỉ làm việc, cuối cùng anh ấy đã thành công."],
  ["B1", "Les étudiants manifestent contre la hausse des frais.", "Sinh viên biểu tình phản đối việc tăng học phí."],
  ["B1", "Je vous remercie de votre réponse rapide.", "Cảm ơn bạn đã phản hồi nhanh."],
  ["B1", "On dit que ce restaurant est le meilleur de la ville.", "Người ta nói nhà hàng này ngon nhất thành phố."],
  ["B1", "Malgré la pluie, le festival a eu beaucoup de succès.", "Dù trời mưa, lễ hội vẫn rất thành công."],
  ["B1", "Je compte m'inscrire à un cours de cuisine.", "Tôi định đăng ký một lớp nấu ăn."],
  ["B1", "Le gouvernement a annoncé de nouvelles mesures.", "Chính phủ đã công bố các biện pháp mới."],
  ["B1", "Il vaut mieux éviter les heures de pointe.", "Tốt hơn là tránh giờ cao điểm."],
  ["B1", "Elle s'est plainte du bruit de ses voisins.", "Cô ấy phàn nàn về tiếng ồn của hàng xóm."],
  ["B1", "Nous avons été très bien accueillis par nos hôtes.", "Chúng tôi được chủ nhà đón tiếp rất chu đáo."],
  ["B1", "Je vous conseille de lire ce roman en version originale.", "Tôi khuyên bạn đọc cuốn tiểu thuyết này bằng bản gốc."],
  ["B1", "Beaucoup de jeunes partent étudier à l'étranger.", "Nhiều bạn trẻ đi du học."],
  ["B1", "Le chômage a légèrement baissé ce trimestre.", "Tỷ lệ thất nghiệp giảm nhẹ trong quý này."],
  ["B1", "Si tu avais besoin d'aide, tu pourrais m'appeler.", "Nếu cần giúp, bạn có thể gọi cho tôi."],
  ["B1", "Ils se sont rencontrés pendant leurs études.", "Họ quen nhau khi còn đi học."],
  ["B1", "Il est interdit de fumer dans les lieux publics.", "Cấm hút thuốc ở nơi công cộng."],
  ["B1", "Je ne m'attendais pas à une telle réaction.", "Tôi không ngờ lại có phản ứng như vậy."],
  ["B1", "La bibliothèque propose des ateliers gratuits.", "Thư viện có các buổi hội thảo miễn phí."],
  ["B1", "Nous espérons que la situation va s'améliorer.", "Chúng tôi hy vọng tình hình sẽ cải thiện."],
  ["B1", "Elle hésite entre deux offres d'emploi.", "Cô ấy phân vân giữa hai lời mời làm việc."],
  ["B1", "Il a fallu attendre deux heures aux urgences.", "Phải chờ hai tiếng ở phòng cấp cứu."],
  ["B1", "Je trouve que les transports sont trop chers.", "Tôi thấy phương tiện công cộng quá đắt."],
  ["B1", "Le spectacle a été annulé en raison de la tempête.", "Buổi biểu diễn bị huỷ vì bão."],
  ["B1", "Nous avons appris la nouvelle par la radio.", "Chúng tôi biết tin qua đài."],
  ["B1", "Avant de partir, n'oublie pas d'éteindre l'ordinateur.", "Trước khi đi, đừng quên tắt máy tính."],
  // B2
  ["B2", "Il est regrettable que si peu de moyens soient consacrés à la recherche.", "Thật đáng tiếc là có quá ít nguồn lực dành cho nghiên cứu."],
  ["B2", "La montée des prix de l'énergie inquiète les ménages.", "Giá năng lượng tăng khiến các hộ gia đình lo lắng."],
  ["B2", "Bien que la loi ait été votée, son application reste incertaine.", "Dù luật đã được thông qua, việc áp dụng vẫn chưa chắc chắn."],
  ["B2", "Les entreprises sont de plus en plus nombreuses à recruter à distance.", "Ngày càng nhiều doanh nghiệp tuyển dụng từ xa."],
  ["B2", "Il convient de distinguer l'information de l'opinion.", "Cần phân biệt thông tin với ý kiến."],
  ["B2", "Faute de financement, le projet a dû être abandonné.", "Do thiếu kinh phí, dự án đã phải bỏ dở."],
  ["B2", "Les habitants réclament davantage d'espaces verts.", "Cư dân đòi hỏi thêm nhiều không gian xanh."],
  ["B2", "Nul ne peut ignorer les effets de la pollution sur la santé.", "Không ai có thể phớt lờ tác hại của ô nhiễm đối với sức khoẻ."],
  ["B2", "Cette décision risque d'accentuer les inégalités sociales.", "Quyết định này có nguy cơ làm gia tăng bất bình đẳng xã hội."],
  ["B2", "On assiste à une prise de conscience progressive de la population.", "Chúng ta đang chứng kiến người dân dần nâng cao nhận thức."],
  ["B2", "Le débat a mis en lumière des points de vue divergents.", "Cuộc tranh luận làm nổi bật những quan điểm khác biệt."],
  ["B2", "Il serait souhaitable que les élèves apprennent à trier l'information.", "Học sinh nên học cách sàng lọc thông tin."],
  ["B2", "Les conséquences de cette crise se font encore sentir aujourd'hui.", "Hậu quả của cuộc khủng hoảng này vẫn còn đến hôm nay."],
  ["B2", "À condition que chacun y mette du sien, la réforme peut réussir.", "Với điều kiện mỗi người cùng góp sức, cuộc cải cách có thể thành công."],
  ["B2", "La consommation de viande a sensiblement diminué en dix ans.", "Lượng thịt tiêu thụ đã giảm rõ rệt trong mười năm."],
  ["B2", "Ce phénomène touche particulièrement les zones rurales.", "Hiện tượng này đặc biệt ảnh hưởng tới vùng nông thôn."],
  ["B2", "Encore faut-il que les citoyens soient correctement informés.", "Còn phải để người dân được thông tin đầy đủ đã."],
  ["B2", "Les spécialistes mettent en garde contre une utilisation excessive des écrans.", "Các chuyên gia cảnh báo việc dùng màn hình quá mức."],
  ["B2", "Il est fort probable que les températures continuent d'augmenter.", "Rất có thể nhiệt độ sẽ tiếp tục tăng."],
  ["B2", "Cette mesure a été accueillie avec scepticisme par les syndicats.", "Biện pháp này được các công đoàn đón nhận một cách hoài nghi."],
  ["B2", "Loin de résoudre le problème, cette solution l'aggrave.", "Giải pháp này không những không giải quyết mà còn làm vấn đề trầm trọng hơn."],
  ["B2", "La généralisation du télétravail transforme nos villes.", "Việc làm việc từ xa trở nên phổ biến đang thay đổi các thành phố."],
  ["B2", "Il appartient aux pouvoirs publics de garantir l'accès aux soins.", "Chính quyền có trách nhiệm bảo đảm việc tiếp cận chăm sóc y tế."],
  ["B2", "Les associations dénoncent un manque criant de logements sociaux.", "Các hội đoàn lên án tình trạng thiếu trầm trọng nhà ở xã hội."],
  ["B2", "Quoi qu'on en dise, la lecture reste un loisir apprécié.", "Dù người ta nói gì, đọc sách vẫn là thú vui được ưa chuộng."],
  ["B2", "Cette étude remet en question des idées largement répandues.", "Nghiên cứu này đặt lại câu hỏi về những quan niệm phổ biến."],
  ["B2", "L'essor du numérique a bouleversé le marché du travail.", "Sự bùng nổ kỹ thuật số đã làm đảo lộn thị trường lao động."],
  ["B2", "Il est indispensable de sensibiliser les jeunes au gaspillage.", "Cần thiết phải nâng cao nhận thức của giới trẻ về lãng phí."],
  ["B2", "De nombreux salariés aspirent à un meilleur équilibre de vie.", "Nhiều người lao động mong muốn cân bằng cuộc sống tốt hơn."],
  ["B2", "Le recours aux énergies fossiles demeure trop important.", "Việc sử dụng năng lượng hoá thạch vẫn còn quá nhiều."],
  ["B2", "Cette initiative citoyenne a rapidement pris de l'ampleur.", "Sáng kiến của người dân này đã nhanh chóng lan rộng."],
  ["B2", "On peut se demander si ces efforts suffiront.", "Người ta có thể tự hỏi liệu những nỗ lực này có đủ không."],
  ["B2", "Les inégalités d'accès à internet persistent dans certaines régions.", "Bất bình đẳng trong tiếp cận internet vẫn tồn tại ở một số vùng."],
  ["B2", "Pour peu qu'on s'y intéresse, l'histoire devient passionnante.", "Chỉ cần quan tâm một chút, lịch sử sẽ trở nên cuốn hút."],
  ["B2", "La presse locale joue un rôle essentiel dans la vie démocratique.", "Báo chí địa phương đóng vai trò thiết yếu trong đời sống dân chủ."],
  ["B2", "Il aurait été préférable de consulter les habitants au préalable.", "Lẽ ra nên tham khảo ý kiến người dân từ trước."],
  ["B2", "Cette tendance s'observe dans la plupart des pays européens.", "Xu hướng này có thể thấy ở phần lớn các nước châu Âu."],
  ["B2", "Le coût de la vie pèse lourdement sur les étudiants.", "Chi phí sinh hoạt đè nặng lên sinh viên."],
  ["B2", "Rien ne laisse présager une amélioration rapide.", "Không có dấu hiệu nào cho thấy sẽ cải thiện nhanh."],
  ["B2", "Il s'agit avant tout d'une question de volonté politique.", "Đây trước hết là vấn đề ý chí chính trị."],
];

export const PHAT_AM_2 = [
  // A1
  ["A1", "Le vent souffle fort ce soir.", "Tối nay gió thổi mạnh.", "« vent » âm mũi « an », không đọc chữ t."],
  ["A1", "Un lapin brun mange du pain.", "Một con thỏ nâu ăn bánh mì.", "Ba âm mũi « in »: lapin, brun, pain. Không đọc thêm âm n."],
  ["A1", "Le pull bleu est dans le placard.", "Chiếc áo len xanh ở trong tủ.", "« pull » âm « u », « bleu » âm « eu »."],
  ["A1", "Tout le monde est là.", "Mọi người đều ở đây.", "« tout » âm « ou », « monde » âm mũi « on »."],
  ["A1", "Rose roule sur la route.", "Rose lăn bánh trên đường.", "Ba chữ r ở cổ họng; « roule », « route » âm « ou »."],
  ["A1", "Il boit du jus de fruit.", "Anh ấy uống nước hoa quả.", "« jus », « fruit », « du » đều có âm « u »; « boit » đọc « boa »."],
  ["A1", "Les oiseaux chantent le matin.", "Chim hót vào buổi sáng.", "« les oiseaux » nối z; « chantent » không đọc đuôi ent."],
  ["A1", "Je suis très heureux.", "Tôi rất hạnh phúc.", "« heureux » hai âm « eu »; h câm."],
  ["A1", "Nous avons deux enfants.", "Chúng tôi có hai đứa con.", "Nối z hai lần: « nous avons », « deux enfants »."],
  ["A1", "C'est un grand jardin.", "Đó là một khu vườn lớn.", "« c'est un » nối t; « grand », « jardin » âm mũi."],
  ["A1", "Mon oncle habite à Bordeaux.", "Chú tôi sống ở Bordeaux.", "« mon oncle » nối n; « Bordeaux » đọc « bo-đô »."],
  ["A1", "Le soleil brille aujourd'hui.", "Hôm nay nắng đẹp.", "« soleil » và « brille »: âm « ille » đọc như « i-ơ » nhẹ."],
  ["A1", "La fille regarde la lune.", "Cô gái ngắm mặt trăng.", "« fille » đọc « phi-ơ »; « lune » âm « u »."],
  ["A1", "Où sont mes chaussures ?", "Giày của tôi đâu?", "« chaussures » âm « u » và r cuối nhẹ."],
  ["A1", "Il est huit heures et quart.", "Bây giờ là tám giờ mười lăm.", "« huit heures » nối t; « quart » đọc « ca »."],
  ["A1", "Elle a un beau sourire.", "Cô ấy có nụ cười đẹp.", "« beau » âm « ô »; « sourire » âm « ou » + r."],
  ["A1", "Je voudrais du riz, s'il vous plaît.", "Làm ơn cho tôi xin cơm.", "« riz » không đọc z; « vous » âm « ou »."],
  ["A1", "Le train part dans une minute.", "Tàu khởi hành trong một phút nữa.", "« train » âm mũi « in »; « une minute » hai âm « u »."],
  ["A1", "Mes amis sont en vacances.", "Bạn bè tôi đang đi nghỉ.", "« mes amis » nối z; « sont en » nối t."],
  ["A1", "Quel temps fait-il ?", "Thời tiết thế nào?", "« temps » âm mũi « an », không đọc p và s."],
  ["A1", "Le bébé dort dans son lit.", "Em bé ngủ trong nôi.", "« dort » r cuối nhẹ; « lit » không đọc t."],
  ["A1", "Une grande tour blanche.", "Một ngọn tháp trắng cao.", "« tour » âm « ou »; « grande », « blanche » âm mũi « an »."],
  ["A1", "J'ai faim et j'ai soif.", "Tôi đói và khát.", "« faim » âm mũi « in »; « soif » đọc « soa-ph »."],
  ["A1", "Il neige à la montagne.", "Trên núi tuyết rơi.", "« neige » âm « ê »; « montagne » âm « gn » như « nh »."],
  ["A1", "Le chat noir saute sur le mur.", "Con mèo đen nhảy lên tường.", "« noir » âm « oa »; « mur » âm « u »."],
  ["A1", "Nous sommes dix dans la classe.", "Lớp chúng tôi có mười người.", "« dix » đọc « đis » khi đứng một mình hoặc cuối nhóm."],
  ["A1", "Cette robe est trop longue.", "Chiếc váy này dài quá.", "« longue » âm mũi « on » + g."],
  ["A1", "Il y a du vent sur la plage.", "Trên bãi biển có gió.", "« il y a » đọc liền « i-li-a »; « vent » âm mũi."],
  ["A1", "Je lis un livre intéressant.", "Tôi đọc một cuốn sách hay.", "« un livre » không nối; « intéressant » mở đầu âm mũi « in »."],
  ["A1", "Bonne nuit, à demain !", "Chúc ngủ ngon, hẹn mai gặp!", "« bonne » không phải âm mũi vì có hai chữ n; « nuit » âm « ui »."],
  ["A1", "Les fleurs sont jaunes.", "Những bông hoa màu vàng.", "« fleurs » âm « eu » mở; « jaunes » âm « ô »."],
  ["A1", "Mon père aime le poisson.", "Bố tôi thích cá.", "« poisson » âm s (hai chữ s), khác « poison » âm z."],
  ["A1", "Elle chante une chanson.", "Cô ấy hát một bài hát.", "« chante », « chanson » âm mũi « an » và « on »."],
  ["A1", "Le musée ouvre à dix heures.", "Bảo tàng mở cửa lúc mười giờ.", "« dix heures » nối z; « musée » âm « u »."],
  ["A1", "Tu viens avec nous ?", "Bạn đi cùng chúng tôi không?", "« viens » âm mũi « in »; « nous » âm « ou »."],
  ["A1", "Un croissant et un jus d'orange.", "Một bánh sừng bò và một cốc nước cam.", "« croissant » âm mũi « an »; « orange » âm mũi + j."],
  ["A1", "La rue est très étroite.", "Con phố rất hẹp.", "« très étroite » nối z; « rue » âm « u »."],
  ["A1", "Mes grands-parents vivent en Normandie.", "Ông bà tôi sống ở Normandie.", "« vivent » không đọc ent; « en Normandie » âm mũi « an »."],
  ["A1", "Il porte un chapeau noir.", "Anh ấy đội mũ đen.", "« chapeau » âm « ô »; « noir » âm « oa » + r."],
  ["A1", "Nous allons à la boulangerie.", "Chúng tôi đi tiệm bánh mì.", "« nous allons » nối z; « boulangerie » âm « ou » + âm mũi « an »."],
  // A2
  ["A2", "J'ai rencontré un ancien ami au marché.", "Tôi gặp lại một người bạn cũ ở chợ.", "« un ancien ami » nối n hai lần."],
  ["A2", "Il faisait très chaud pendant les vacances.", "Trong kỳ nghỉ trời rất nóng.", "« faisait » đọc « phơ-dè »; « pendant » hai âm mũi « an »."],
  ["A2", "Elle s'est inscrite à la salle de sport.", "Cô ấy đăng ký vào phòng tập.", "« s'est inscrite » nối t; « inscrite » mở đầu âm mũi « in »."],
  ["A2", "Nous avons pris le petit-déjeuner ensemble.", "Chúng tôi ăn sáng cùng nhau.", "« ensemble » hai âm mũi « an »; « déjeuner » âm « eu »."],
  ["A2", "Le bureau se trouve au troisième étage.", "Văn phòng ở tầng ba.", "« troisième étage » nối âm z nhẹ."],
  ["A2", "Ils ont attendu une heure devant le cinéma.", "Họ đã chờ một tiếng trước rạp chiếu phim.", "« ils ont » nối z, « ont attendu » nối t, « une heure » liền."],
  ["A2", "Je me sens beaucoup mieux aujourd'hui.", "Hôm nay tôi thấy khoẻ hơn nhiều.", "« sens » âm mũi « an » đọc s cuối; « mieux » âm « eu »."],
  ["A2", "Le pont a été construit au siècle dernier.", "Cây cầu được xây vào thế kỷ trước.", "« pont » âm mũi « on »; « construit » âm « ui »."],
  ["A2", "Cette boulangerie vend du pain bio.", "Tiệm bánh này bán bánh mì hữu cơ.", "« vend » âm mũi « an » không đọc d; « pain » âm mũi « in »."],
  ["A2", "Il faut tourner à droite après le feu.", "Phải rẽ phải sau đèn giao thông.", "« tourner » âm « ou »; « feu » âm « eu »; « droite » âm « oa »."],
  ["A2", "Nous avons visité un vieux château.", "Chúng tôi đã tham quan một lâu đài cổ.", "« vieux » âm « iơ »; « château » âm « ô »."],
  ["A2", "Mon cousin habite au Canada depuis un an.", "Anh họ tôi sống ở Canada được một năm.", "« cousin » âm z + âm mũi « in »; « un an » nối n."],
  ["A2", "Elle a eu peur pendant l'orage.", "Cô ấy sợ hãi trong cơn giông.", "« eu » đọc như « u »; « peur » âm « eu » mở."],
  ["A2", "Les enfants jouent dans la cour.", "Bọn trẻ chơi ngoài sân.", "« jouent » đọc « giu », không đọc ent; « cour » âm « ou »."],
  ["A2", "J'aimerais apprendre à nager cet été.", "Hè này tôi muốn học bơi.", "« apprendre » âm mũi « an »; « cet été » nối t."],
  ["A2", "On se retrouve devant la gare à midi.", "Hẹn gặp trước nhà ga lúc trưa.", "« retrouve » r ở cổ họng hai lần; âm « ou »."],
  ["A2", "Il a plu toute la nuit.", "Trời mưa suốt đêm.", "« plu » âm « u »; « toute » âm « ou »; « nuit » âm « ui »."],
  ["A2", "Ma tante prépare un gâteau au chocolat.", "Cô tôi làm bánh sô-cô-la.", "« tante » âm mũi « an »; « gâteau au » hai âm « ô » liền."],
  ["A2", "Nous partirons dès que possible.", "Chúng tôi sẽ đi càng sớm càng tốt.", "« dès que » đọc « đè cơ »; « possible » âm s."],
  ["A2", "Le directeur est en réunion.", "Giám đốc đang họp.", "« est en » nối t; « réunion » âm « u » + âm mũi « on »."],
  ["A2", "Elle porte toujours des lunettes rondes.", "Cô ấy luôn đeo kính tròn.", "« toujours » âm « ou »; « lunettes » âm « u »."],
  ["A2", "Je cherche un appartement avec un balcon.", "Tôi tìm một căn hộ có ban công.", "« un appartement » nối n; « balcon » âm mũi « on »."],
  ["A2", "Ils se sont mariés au printemps.", "Họ cưới nhau vào mùa xuân.", "« printemps » hai âm mũi « in » và « an »."],
  ["A2", "Ce musée est fermé pour travaux.", "Bảo tàng đóng cửa để sửa chữa.", "« travaux » âm « ô », không đọc x."],
  ["A2", "Il vend des légumes au marché.", "Anh ấy bán rau ở chợ.", "« vend des » không nối; « légumes » âm « u »."],
  ["A2", "Nous avons nagé dans une rivière froide.", "Chúng tôi bơi ở một con sông lạnh.", "« rivière » r hai lần; « froide » âm « oa »."],
  ["A2", "Le patron a augmenté les salaires.", "Ông chủ đã tăng lương.", "« augmenté » âm mũi « an »; « salaires » âm « e »."],
  ["A2", "Elle a écrit une longue lettre.", "Cô ấy đã viết một lá thư dài.", "« a écrit » liền; « longue » âm mũi « on »."],
  ["A2", "Je suis allé chez le coiffeur.", "Tôi đã đi cắt tóc.", "« suis allé » nối z; « coiffeur » âm « oa » + « eu »."],
  ["A2", "Ce quartier est très calme la nuit.", "Khu phố này ban đêm rất yên tĩnh.", "« quartier » đọc « các-tiê »; « nuit » âm « ui »."],
  ["A2", "On a perdu le match de dimanche.", "Chúng tôi thua trận Chủ nhật.", "« perdu » âm « u »; « dimanche » âm mũi « an »."],
  ["A2", "Le printemps arrive enfin.", "Mùa xuân cuối cùng cũng đến.", "« enfin » hai âm mũi « an » và « in »."],
  ["A2", "Mon voisin joue de la guitare.", "Hàng xóm tôi chơi đàn ghi-ta.", "« voisin » âm z + mũi « in »; « joue » âm « ou »."],
  ["A2", "Vous avez reçu mon message ?", "Bạn đã nhận được tin nhắn của tôi chưa?", "« vous avez » nối z; « reçu » âm « u »."],
  ["A2", "Elle travaille dans un grand hôtel.", "Cô ấy làm ở một khách sạn lớn.", "« grand hôtel » nối t; h câm."],
  ["A2", "Les feuilles tombent en automne.", "Lá rụng vào mùa thu.", "« feuilles » âm « eu » + i; « en automne » nối n, không đọc m."],
  ["A2", "Nous dînons souvent au restaurant.", "Chúng tôi hay ăn tối ở nhà hàng.", "« dînons » âm mũi « on »; « souvent » âm « ou » + « an »."],
  ["A2", "Il a mal à la tête depuis hier.", "Anh ấy bị đau đầu từ hôm qua.", "« depuis » âm « ui »; « hier » đọc « i-e »."],
  ["A2", "Je n'ai jamais vu un spectacle pareil.", "Tôi chưa bao giờ xem buổi diễn nào như vậy.", "« vu un » không nối; « pareil » âm « ây »."],
  ["A2", "On peut se tutoyer, si tu veux.", "Mình xưng « tu » với nhau nhé, nếu bạn muốn.", "« tutoyer » âm « u » + « oa »; « veux » âm « eu »."],
  // B1
  ["B1", "Il est grand temps de prendre une décision.", "Đã đến lúc phải quyết định.", "« grand temps » hai âm mũi « an » liền nhau."],
  ["B1", "Je trouve cette idée tout à fait intéressante.", "Tôi thấy ý tưởng này rất thú vị.", "« tout à fait » nối t; « intéressante » mở đầu âm mũi « in »."],
  ["B1", "Les élèves ont réalisé un excellent projet.", "Học sinh đã thực hiện một dự án xuất sắc.", "« les élèves » nối z; « ont réalisé » nối t; « un excellent » nối n."],
  ["B1", "Nous sommes en train de chercher une solution.", "Chúng tôi đang tìm giải pháp.", "« en train » hai âm mũi « an » và « in »."],
  ["B1", "Elle s'intéresse beaucoup à l'environnement.", "Cô ấy rất quan tâm đến môi trường.", "« s'intéresse » âm mũi « in »; « environnement » ba âm mũi."],
  ["B1", "Pourriez-vous me rappeler plus tard ?", "Bạn có thể gọi lại cho tôi sau không?", "« pourriez » âm « ou » + r; « plus tard » không đọc s."],
  ["B1", "Il a commencé à pleuvoir dès notre arrivée.", "Trời bắt đầu mưa ngay khi chúng tôi đến.", "« pleuvoir » âm « eu » + « oa »; « notre arrivée » liền."],
  ["B1", "On devrait profiter du beau temps.", "Chúng ta nên tận hưởng thời tiết đẹp.", "« devrait » âm « ơ » nhẹ; « profiter » âm « o »."],
  ["B1", "Je n'en suis pas tout à fait sûr.", "Tôi không hoàn toàn chắc chắn.", "« n'en » âm mũi « an »; « sûr » âm « u »."],
  ["B1", "Ce film m'a beaucoup ému.", "Bộ phim này làm tôi rất xúc động.", "« ému » âm « u »; « beaucoup » âm « ô » + « ou »."],
  ["B1", "Ils ont l'intention de déménager en province.", "Họ định chuyển về tỉnh.", "« l'intention » âm mũi « in » + « an » + « on »."],
  ["B1", "Il faut absolument éviter le gaspillage.", "Nhất định phải tránh lãng phí.", "« absolument » âm mũi « an » cuối; « gaspillage » âm « i-a »."],
  ["B1", "Elle a réussi son examen du premier coup.", "Cô ấy thi đỗ ngay lần đầu.", "« réussi » âm « u »; « examen » đọc « ég-za-min »."],
  ["B1", "Les enfants apprennent vite à utiliser les écrans.", "Trẻ con học dùng màn hình rất nhanh.", "« les enfants » nối z; « apprennent » không đọc ent; « les écrans » nối z."],
  ["B1", "On ne se rend pas toujours compte du temps qui passe.", "Người ta không phải lúc nào cũng nhận ra thời gian trôi.", "« rend », « compte », « temps » đều là âm mũi."],
  ["B1", "Je vous remercie d'avoir pris le temps de répondre.", "Cảm ơn bạn đã dành thời gian trả lời.", "« remercie » hai chữ r; « répondre » âm mũi « on »."],
  ["B1", "Il s'agit d'un problème assez fréquent.", "Đây là một vấn đề khá thường gặp.", "« d'un » âm mũi; « fréquent » âm mũi « an » không đọc t."],
  ["B1", "Nous avons longuement discuté de ce sujet.", "Chúng tôi đã bàn rất lâu về chủ đề này.", "« longuement » âm mũi « on » và « an »; « sujet » âm « u »."],
  ["B1", "Elle préfère vivre en ville qu'à la campagne.", "Cô ấy thích sống ở thành phố hơn nông thôn.", "« en ville » âm mũi; « campagne » âm mũi + « nh »."],
  ["B1", "Les résultats seront publiés la semaine prochaine.", "Kết quả sẽ được công bố tuần sau.", "« résultats » âm « u »; « seront » âm mũi « on »."],
  ["B1", "Je n'arrive pas à me concentrer avec ce bruit.", "Tôi không tập trung được với tiếng ồn này.", "« concentrer » hai âm mũi « on » và « an »; « bruit » âm « ui »."],
  ["B1", "Il a toujours rêvé de voyager en Asie.", "Anh ấy luôn mơ được đi du lịch châu Á.", "« toujours » âm « ou »; « voyager » âm « oa-i »."],
  ["B1", "Ce n'est pas la peine de t'inquiéter.", "Bạn không cần lo đâu.", "« peine » âm « e »; « t'inquiéter » âm mũi « in »."],
  ["B1", "Nous avons dû annuler notre séjour.", "Chúng tôi đã phải huỷ chuyến đi.", "« dû » âm « u »; « annuler » âm « u »; « séjour » âm « ou »."],
  ["B1", "Elle a un sens de l'humour très développé.", "Cô ấy rất có khiếu hài hước.", "« sens » âm mũi đọc s; « humour » âm « u » + « ou »."],
  ["B1", "Je suis convaincu que nous allons réussir.", "Tôi tin chắc chúng ta sẽ thành công.", "« convaincu » âm mũi « on » + « in » + « u »."],
  ["B1", "Il y a eu un accident sur l'autoroute.", "Đã có tai nạn trên đường cao tốc.", "« il y a eu un » đọc liền; « accident » âm mũi cuối."],
  ["B1", "Ce sont des questions qu'on se pose souvent.", "Đó là những câu hỏi người ta hay tự đặt ra.", "« qu'on » âm mũi « on »; « souvent » âm « ou » + « an »."],
  ["B1", "Elle travaille à mi-temps pour s'occuper de ses enfants.", "Cô ấy làm bán thời gian để chăm con.", "« mi-temps » âm mũi; « ses enfants » nối z."],
  ["B1", "On m'a proposé un poste à l'étranger.", "Người ta mời tôi một vị trí ở nước ngoài.", "« proposé un » không nối; « étranger » âm mũi « an »."],
  ["B1", "Je pense qu'il faudrait changer de méthode.", "Tôi nghĩ nên đổi phương pháp.", "« pense » âm mũi « an »; « changer » âm mũi « an »."],
  ["B1", "Les embouteillages sont de plus en plus fréquents.", "Tắc đường ngày càng thường xuyên.", "« embouteillages » âm mũi « an » + « ou »; « de plus en plus » đọc « plu-zan-plu »."],
  ["B1", "Elle a été élue déléguée de sa classe.", "Cô ấy được bầu làm lớp trưởng.", "« été élue » ba âm « é » liền; « élue » âm « u »."],
  ["B1", "Il s'est excusé de son retard.", "Anh ấy xin lỗi vì đến muộn.", "« s'est excusé » nối t; « retard » r hai lần."],
  ["B1", "Nous avons adoré la cuisine de cette région.", "Chúng tôi rất thích ẩm thực vùng này.", "« nous avons adoré » nối z; « cuisine » âm « ui »."],
  ["B1", "Ce livre m'a fait réfléchir.", "Cuốn sách này khiến tôi suy ngẫm.", "« réfléchir » r đầu và cuối ở cổ họng."],
  ["B1", "On a organisé une collecte pour les sans-abri.", "Chúng tôi đã tổ chức quyên góp cho người vô gia cư.", "« organisé une » liền; « sans-abri » âm mũi nối z."],
  ["B1", "Je vous souhaite une bonne continuation.", "Chúc bạn mọi điều tốt đẹp.", "« souhaite » âm « ou-è »; « continuation » âm mũi « on » + « u »."],
  ["B1", "Il fait de son mieux pour progresser.", "Anh ấy cố hết sức để tiến bộ.", "« mieux » âm « eu »; « progresser » hai chữ r."],
  ["B1", "Elle a vécu plusieurs années au Japon.", "Cô ấy sống ở Nhật vài năm.", "« plusieurs années » nối z; « Japon » âm mũi « on »."],
  // B2
  ["B2", "Il convient de nuancer cette affirmation.", "Cần nói rõ hơn khẳng định này.", "« convient » âm mũi « on » + « in »; « nuancer » âm « u » + mũi « an »."],
  ["B2", "Les enjeux environnementaux sont considérables.", "Các thách thức về môi trường là rất lớn.", "« les enjeux » nối z; « environnementaux » ba âm mũi."],
  ["B2", "On ne saurait sous-estimer l'influence des réseaux sociaux.", "Không thể đánh giá thấp ảnh hưởng của mạng xã hội.", "« sous-estimer » nối z; « influence » hai âm mũi."],
  ["B2", "Cette mesure a suscité un vif mécontentement.", "Biện pháp này gây bất bình mạnh mẽ.", "« suscité un » không nối; « mécontentement » bốn âm mũi."],
  ["B2", "Il est impératif de réduire les émissions polluantes.", "Bắt buộc phải giảm khí thải gây ô nhiễm.", "« est impératif » nối t; « émissions » âm mũi « on »."],
  ["B2", "L'enseignement à distance présente des limites évidentes.", "Học từ xa có những giới hạn rõ ràng.", "« enseignement » âm mũi « an » hai lần; « des limites » không nối."],
  ["B2", "Les inégalités sociales se sont creusées depuis la crise.", "Bất bình đẳng xã hội ngày càng sâu từ sau khủng hoảng."," « les inégalités » nối z; « creusées » âm « eu »."],
  ["B2", "Nombre de citoyens s'interrogent sur l'avenir.", "Nhiều người dân đặt câu hỏi về tương lai.", "« nombre » âm mũi « on »; « s'interrogent » âm mũi « in »."],
  ["B2", "Cette évolution soulève de nombreuses questions éthiques.", "Sự phát triển này đặt ra nhiều câu hỏi đạo đức.", "« soulève » âm « ou »; « nombreuses » âm mũi + « eu »."],
  ["B2", "Il serait judicieux d'investir dans les transports en commun.", "Đầu tư vào giao thông công cộng là sáng suốt.", "« judicieux » âm « u » + « eu »; « en commun » nối n."],
  ["B2", "Les pouvoirs publics tardent à réagir.", "Chính quyền chậm phản ứng.", "« pouvoirs » âm « ou » + « oa »; « tardent » không đọc ent."],
  ["B2", "On constate une augmentation inquiétante des loyers.", "Có thể thấy giá thuê nhà tăng đáng lo ngại.", "« constate une » liền; « augmentation inquiétante » nối n."],
  ["B2", "Les citoyens aspirent à davantage de transparence.", "Người dân mong muốn minh bạch hơn.", "« citoyens » âm « oa-i » + mũi « in »; « transparence » hai âm mũi « an »."],
  ["B2", "Cet argument me paraît tout à fait recevable.", "Lập luận này tôi thấy hoàn toàn có thể chấp nhận.", "« cet argument » nối t; « tout à fait » nối t."],
  ["B2", "Il s'agit d'un enjeu majeur pour les générations futures.", "Đây là thách thức lớn cho các thế hệ tương lai.", "« d'un enjeu » nối n; « futures » âm « u »."],
  ["B2", "La consommation responsable gagne du terrain.", "Tiêu dùng có trách nhiệm đang lan rộng.", "« consommation » hai âm mũi « on »; « responsable » âm mũi « on »."],
  ["B2", "Les autorités ont pris des mesures d'urgence.", "Chính quyền đã có các biện pháp khẩn cấp.", "« les autorités » nối z; « ont pris » nối t; « urgence » âm mũi."],
  ["B2", "Je doute fort que cette solution soit efficace.", "Tôi rất nghi ngờ giải pháp này hiệu quả.", "« doute » âm « ou »; « soit efficace » nối t."],
  ["B2", "Il importe de préserver la biodiversité.", "Điều quan trọng là bảo tồn đa dạng sinh học.", "« importe » mở đầu âm mũi « in »; « biodiversité » r giữa từ."],
  ["B2", "Les jeunes générations sont particulièrement sensibilisées.", "Các thế hệ trẻ đặc biệt có ý thức.", "« générations » âm mũi « on »; « sensibilisées » âm mũi « an »."],
  ["B2", "Ce phénomène s'explique en partie par la mondialisation.", "Hiện tượng này giải thích một phần bởi toàn cầu hoá.", "« en partie » âm mũi « an »; « mondialisation » âm mũi « on » hai lần."],
  ["B2", "On assiste à une véritable révolution numérique.", "Chúng ta đang chứng kiến một cuộc cách mạng số thực sự.", "« on assiste » nối n; « numérique » âm « u »."],
  ["B2", "Cette proposition a été rejetée à une large majorité.", "Đề xuất này bị bác bỏ với đa số lớn.", "« a été » liền; « rejetée » âm « ơ » nhẹ."],
  ["B2", "Les entreprises doivent assumer leurs responsabilités.", "Doanh nghiệp phải gánh vác trách nhiệm của mình.", "« les entreprises » nối z; « leurs responsabilités » nối z."],
  ["B2", "Il est temps d'agir plutôt que de discourir.", "Đã đến lúc hành động thay vì bàn luận.", "« temps » âm mũi; « plutôt » âm « u » + « ô »."],
  ["B2", "La pénurie de main-d'œuvre touche plusieurs secteurs.", "Tình trạng thiếu nhân lực ảnh hưởng nhiều ngành.", "« pénurie » âm « u »; « main-d'œuvre » âm mũi « in » + « eu »."],
  ["B2", "On peut légitimement s'interroger sur ces chiffres.", "Người ta hoàn toàn có thể đặt câu hỏi về những con số này.", "« légitimement » âm mũi « an » cuối; « chiffres » âm « i »."],
  ["B2", "Cette réforme vise à simplifier les démarches administratives.", "Cuộc cải cách này nhằm đơn giản hoá thủ tục hành chính.", "« simplifier » âm mũi « in »; « démarches » r giữa."],
  ["B2", "Les spécialistes divergent sur ce point.", "Các chuyên gia bất đồng về điểm này.", "« divergent » không đọc ent; « point » âm mũi « oin »."],
  ["B2", "Il faut reconnaître que les progrès sont indéniables.", "Phải thừa nhận rằng những tiến bộ là không thể phủ nhận.", "« reconnaître » hai chữ r; « indéniables » âm mũi « in »."],
  ["B2", "Le vieillissement de la population pose de nouveaux défis.", "Dân số già hoá đặt ra những thách thức mới.", "« vieillissement » âm « iê-i » + mũi « an »; « nouveaux défis » không nối."],
  ["B2", "Rien ne justifie une telle augmentation des prix.", "Không gì biện minh cho việc tăng giá như vậy.", "« rien » âm mũi « in »; « justifie » âm « u »."],
  ["B2", "Les échanges culturels enrichissent les deux pays.", "Giao lưu văn hoá làm phong phú cả hai nước.", "« les échanges » nối z; « enrichissent » âm mũi « an », không đọc ent."],
  ["B2", "Il est urgent d'agir face au réchauffement climatique.", "Cần hành động khẩn cấp trước sự nóng lên toàn cầu.", "« est urgent » nối t; « réchauffement » âm « ô » + mũi « an »."],
  ["B2", "Nous plaidons pour une meilleure répartition des richesses.", "Chúng tôi kêu gọi phân chia của cải công bằng hơn.", "« plaidons » âm mũi « on »; « meilleure » âm « e-i-eu »."],
  ["B2", "Ce compromis ne satisfait personne.", "Thoả hiệp này không làm ai hài lòng.", "« compromis » âm mũi « on »; « satisfait » không đọc t."],
  ["B2", "On observe un regain d'intérêt pour la lecture.", "Người ta thấy sự quan tâm trở lại với việc đọc sách.", "« on observe » nối n; « regain » âm mũi « in »."],
  ["B2", "L'opinion publique reste profondément divisée.", "Dư luận vẫn chia rẽ sâu sắc.", "« opinion » âm mũi « on »; « profondément » hai âm mũi."],
  ["B2", "Il aurait mieux valu prévenir que guérir.", "Lẽ ra phòng bệnh vẫn hơn chữa bệnh.", "« aurait mieux » âm « eu »; « guérir » r cuối."],
  ["B2", "Ces chiffres témoignent d'une amélioration notable.", "Những con số này cho thấy sự cải thiện đáng kể.", "« témoignent » âm « oa » + « nh », không đọc ent; « d'une amélioration » liền."],
];
