/* Kho câu RIÊNG cho « Nghe điền từ » (10/10). Trước đó dạng này dùng lại câu
 * chép chính tả, nên học sinh gặp đúng một câu hai lần. 50 câu mỗi trình độ.
 * Nội dung học: KHÔNG dùng dấu gạch dài. [cấp, câu, nghĩa] */

export const DIEN_TU = [
  // A1
  ["A1", "Le samedi, je fais le marché avec ma grand-mère.", "Thứ Bảy, tôi đi chợ với bà."],
  ["A1", "Mon appartement est au deuxième étage.", "Căn hộ của tôi ở tầng hai."],
  ["A1", "Nous partons en vacances au mois d'août.", "Chúng tôi đi nghỉ vào tháng Tám."],
  ["A1", "Le café est à côté de la poste.", "Quán cà phê ở cạnh bưu điện."],
  ["A1", "Je prends une douche tous les soirs.", "Tối nào tôi cũng tắm."],
  ["A1", "Ma sœur adore les gâteaux au chocolat.", "Em gái tôi rất thích bánh sô cô la."],
  ["A1", "Il fait froid, mets ton manteau.", "Trời lạnh, mặc áo khoác vào."],
  ["A1", "La boulangerie ouvre très tôt le matin.", "Tiệm bánh mở cửa từ rất sớm."],
  ["A1", "Nous avons un chat noir et blanc.", "Chúng tôi có một con mèo đen trắng."],
  ["A1", "Mon père travaille dans un hôpital.", "Bố tôi làm việc ở bệnh viện."],
  ["A1", "Je voudrais un kilo de pommes, s'il vous plaît.", "Cho tôi một ký táo."],
  ["A1", "Le train pour Lyon part à huit heures.", "Tàu đi Lyon khởi hành lúc tám giờ."],
  ["A1", "Elle chante dans la voiture avec sa fille.", "Cô ấy hát trong xe cùng con gái."],
  ["A1", "Les enfants jouent dans le jardin.", "Bọn trẻ chơi trong vườn."],
  ["A1", "Je n'aime pas le poisson.", "Tôi không thích cá."],
  ["A1", "Le dimanche, nous déjeunons chez mes parents.", "Chủ Nhật, chúng tôi ăn trưa ở nhà bố mẹ tôi."],
  ["A1", "Pardon, où sont les toilettes ?", "Xin lỗi, nhà vệ sinh ở đâu?"],
  ["A1", "Mon anniversaire est le douze mars.", "Sinh nhật tôi là ngày mười hai tháng Ba."],
  ["A1", "Il lit un livre dans sa chambre.", "Anh ấy đọc sách trong phòng."],
  ["A1", "Nous allons au cinéma ce soir.", "Tối nay chúng tôi đi xem phim."],
  ["A1", "La salle de bains est à droite.", "Phòng tắm ở bên phải."],
  ["A1", "J'achète du pain à la boulangerie.", "Tôi mua bánh mì ở tiệm bánh."],
  ["A1", "Mes amis habitent à Paris.", "Các bạn tôi sống ở Paris."],
  ["A1", "Tu veux du sucre dans ton café ?", "Bạn có muốn cho đường vào cà phê không?"],
  ["A1", "Le cours de français commence à dix heures.", "Lớp tiếng Pháp bắt đầu lúc mười giờ."],
  ["A1", "Elle a les cheveux longs et bruns.", "Cô ấy có mái tóc dài màu nâu."],
  ["A1", "Je téléphone à ma mère le soir.", "Tôi gọi điện cho mẹ vào buổi tối."],
  ["A1", "Il y a un parc près de chez moi.", "Có một công viên gần nhà tôi."],
  ["A1", "Nous apprenons l'anglais à l'école.", "Chúng tôi học tiếng Anh ở trường."],
  ["A1", "Ce pantalon coûte trente euros.", "Cái quần này giá ba mươi euro."],
  ["A1", "Le matin, je bois un jus d'orange.", "Buổi sáng tôi uống nước cam."],
  ["A1", "Mon bureau est très petit.", "Văn phòng của tôi rất nhỏ."],
  ["A1", "Il neige à la montagne en hiver.", "Mùa đông trên núi có tuyết."],
  ["A1", "Je me lève à sept heures.", "Tôi dậy lúc bảy giờ."],
  ["A1", "Elle va au travail en métro.", "Cô ấy đi làm bằng tàu điện ngầm."],
  ["A1", "Nous faisons du vélo le dimanche.", "Chúng tôi đạp xe vào Chủ Nhật."],
  ["A1", "La pharmacie est fermée aujourd'hui.", "Hôm nay hiệu thuốc đóng cửa."],
  ["A1", "Mon voisin est très gentil.", "Hàng xóm của tôi rất tử tế."],
  ["A1", "J'ai faim, on mange quand ?", "Tôi đói rồi, khi nào ăn?"],
  ["A1", "Les fleurs du jardin sont jaunes.", "Hoa trong vườn màu vàng."],
  ["A1", "Il regarde un match de football.", "Anh ấy xem một trận bóng đá."],
  ["A1", "Nous avons cours le lundi et le jeudi.", "Chúng tôi có lớp vào thứ Hai và thứ Năm."],
  ["A1", "Ma chambre est bleue et blanche.", "Phòng tôi màu xanh và trắng."],
  ["A1", "Je cherche mes clés.", "Tôi đang tìm chìa khóa."],
  ["A1", "Le restaurant est à gauche de la banque.", "Nhà hàng ở bên trái ngân hàng."],
  ["A1", "Elle parle trois langues.", "Cô ấy nói ba thứ tiếng."],
  ["A1", "On se retrouve devant le musée ?", "Mình gặp nhau trước bảo tàng nhé?"],
  ["A1", "Mon fils a six ans.", "Con trai tôi sáu tuổi."],
  ["A1", "Je prends le bus numéro quatre.", "Tôi đi xe buýt số bốn."],
  ["A1", "Ma tante habite près de la mer.", "Dì tôi sống gần biển."],
  // A2
  ["A2", "Hier soir, nous avons dîné dans un restaurant italien.", "Tối qua chúng tôi ăn tối ở một nhà hàng Ý."],
  ["A2", "Quand j'étais petit, j'habitais à la campagne.", "Hồi nhỏ tôi sống ở nông thôn."],
  ["A2", "Elle a perdu son portefeuille dans le métro.", "Cô ấy đánh mất ví trong tàu điện ngầm."],
  ["A2", "Je vais réserver une table pour quatre personnes.", "Tôi sẽ đặt một bàn cho bốn người."],
  ["A2", "Les billets sont moins chers pour les étudiants.", "Vé rẻ hơn cho sinh viên."],
  ["A2", "Nous sommes arrivés en retard à cause des embouteillages.", "Chúng tôi đến muộn vì tắc đường."],
  ["A2", "Il faut prendre ce médicament trois fois par jour.", "Phải uống thuốc này ba lần một ngày."],
  ["A2", "Mon frère cherche un appartement plus grand.", "Anh tôi đang tìm một căn hộ rộng hơn."],
  ["A2", "Vous pouvez m'envoyer le document par courriel ?", "Anh có thể gửi tài liệu cho tôi qua email không?"],
  ["A2", "L'été dernier, nous sommes allés en Espagne.", "Mùa hè năm ngoái chúng tôi đi Tây Ban Nha."],
  ["A2", "Je n'ai pas encore lu ce livre.", "Tôi chưa đọc cuốn sách này."],
  ["A2", "Ce pull est trop petit, je voudrais l'échanger.", "Cái áo len này nhỏ quá, tôi muốn đổi."],
  ["A2", "Le week-end prochain, il va faire beau.", "Cuối tuần tới trời sẽ đẹp."],
  ["A2", "Elle s'est inscrite à un cours de danse.", "Cô ấy đã đăng ký một lớp học nhảy."],
  ["A2", "Nous faisons la queue depuis une demi-heure.", "Chúng tôi xếp hàng đã nửa tiếng."],
  ["A2", "Mon ordinateur ne marche plus depuis lundi.", "Máy tính của tôi hỏng từ thứ Hai."],
  ["A2", "Tu peux acheter du lait en rentrant ?", "Trên đường về bạn mua sữa được không?"],
  ["A2", "Il a commencé son nouveau travail la semaine dernière.", "Anh ấy bắt đầu công việc mới tuần trước."],
  ["A2", "Les magasins sont fermés le jour de Noël.", "Các cửa hàng đóng cửa vào ngày Giáng sinh."],
  ["A2", "J'ai rendez-vous chez le dentiste jeudi matin.", "Sáng thứ Năm tôi có hẹn với nha sĩ."],
  ["A2", "Nous avons visité un vieux château au bord de la Loire.", "Chúng tôi tham quan một lâu đài cổ bên bờ sông Loire."],
  ["A2", "Ma grand-mère fait toujours une tarte aux pommes.", "Bà tôi lúc nào cũng làm bánh táo."],
  ["A2", "Il est interdit de fumer dans le bâtiment.", "Cấm hút thuốc trong tòa nhà."],
  ["A2", "Je préfère voyager en train qu'en avion.", "Tôi thích đi tàu hơn đi máy bay."],
  ["A2", "Elle a oublié son parapluie au bureau.", "Cô ấy quên ô ở văn phòng."],
  ["A2", "Le concert a duré plus de deux heures.", "Buổi hòa nhạc kéo dài hơn hai tiếng."],
  ["A2", "On pourrait faire un pique-nique au bord du lac.", "Mình có thể đi dã ngoại bên bờ hồ."],
  ["A2", "Mes voisins font beaucoup de bruit le soir.", "Hàng xóm của tôi rất ồn vào buổi tối."],
  ["A2", "J'apprends à conduire depuis trois mois.", "Tôi học lái xe đã ba tháng."],
  ["A2", "Le vol pour Rome a été annulé.", "Chuyến bay đi Rome đã bị hủy."],
  ["A2", "Nous avons fêté l'anniversaire de Lucie samedi.", "Thứ Bảy chúng tôi đã tổ chức sinh nhật Lucie."],
  ["A2", "Il vaut mieux réserver les billets à l'avance.", "Nên đặt vé trước thì hơn."],
  ["A2", "Mon collègue est malade, il reste chez lui.", "Đồng nghiệp tôi bị ốm, anh ấy ở nhà."],
  ["A2", "La bibliothèque prête des livres pendant trois semaines.", "Thư viện cho mượn sách trong ba tuần."],
  ["A2", "J'ai mal à la tête depuis ce matin.", "Tôi đau đầu từ sáng."],
  ["A2", "Ils ont déménagé dans le sud de la France.", "Họ đã chuyển xuống miền Nam nước Pháp."],
  ["A2", "Tu as déjà goûté la cuisine vietnamienne ?", "Bạn đã bao giờ ăn thử món Việt chưa?"],
  ["A2", "Le marché a lieu tous les mercredis sur la place.", "Chợ họp ở quảng trường vào mọi thứ Tư."],
  ["A2", "Elle travaille à mi-temps dans une librairie.", "Cô ấy làm bán thời gian ở một hiệu sách."],
  ["A2", "Nous avons loué une maison près de la mer.", "Chúng tôi thuê một ngôi nhà gần biển."],
  ["A2", "Je dois rendre ce rapport avant vendredi.", "Tôi phải nộp báo cáo này trước thứ Sáu."],
  ["A2", "Il pleuvait quand nous sommes sortis.", "Trời đang mưa khi chúng tôi ra ngoài."],
  ["A2", "Mon téléphone n'a plus de batterie.", "Điện thoại tôi hết pin rồi."],
  ["A2", "La réunion a été déplacée à quinze heures.", "Cuộc họp đã dời sang mười lăm giờ."],
  ["A2", "On se voit après le travail pour boire un verre ?", "Sau giờ làm mình gặp nhau uống một ly nhé?"],
  ["A2", "Ils ont acheté une voiture électrique.", "Họ đã mua một chiếc ô tô điện."],
  ["A2", "La directrice nous a présenté le nouveau collègue.", "Bà giám đốc giới thiệu đồng nghiệp mới với chúng tôi."],
  ["A2", "Je me suis couché très tard hier.", "Hôm qua tôi đi ngủ rất muộn."],
  ["A2", "Cette rue est très animée le soir.", "Con phố này rất nhộn nhịp vào buổi tối."],
  ["A2", "Nous allons repeindre la cuisine en blanc.", "Chúng tôi sẽ sơn lại bếp màu trắng."],
  // B1
  ["B1", "Si j'avais plus de temps, je ferais du bénévolat.", "Nếu có nhiều thời gian hơn, tôi sẽ làm tình nguyện."],
  ["B1", "Les jeunes lisent de moins en moins la presse papier.", "Giới trẻ ngày càng ít đọc báo giấy."],
  ["B1", "Il faut que tu préviennes ton chef de ton absence.", "Bạn phải báo trước với sếp về việc vắng mặt."],
  ["B1", "Depuis qu'il fait du sport, il dort beaucoup mieux.", "Từ khi chơi thể thao, anh ấy ngủ ngon hơn nhiều."],
  ["B1", "La ville a décidé de créer de nouvelles pistes cyclables.", "Thành phố quyết định làm thêm làn đường cho xe đạp."],
  ["B1", "Je regrette de ne pas avoir appris le piano plus tôt.", "Tôi tiếc vì đã không học piano sớm hơn."],
  ["B1", "Ce film m'a beaucoup ému, surtout la fin.", "Bộ phim làm tôi rất xúc động, nhất là đoạn kết."],
  ["B1", "Elle a obtenu une bourse pour étudier au Canada.", "Cô ấy nhận được học bổng sang Canada học."],
  ["B1", "Le prix des loyers a beaucoup augmenté cette année.", "Giá thuê nhà năm nay tăng mạnh."],
  ["B1", "Nous devrions trier nos déchets plus soigneusement.", "Chúng ta nên phân loại rác cẩn thận hơn."],
  ["B1", "Bien qu'il soit fatigué, il continue à travailler.", "Dù mệt, anh ấy vẫn tiếp tục làm việc."],
  ["B1", "J'ai trouvé ce stage grâce à un ancien professeur.", "Tôi tìm được kỳ thực tập này nhờ một thầy giáo cũ."],
  ["B1", "Le télétravail permet d'éviter les longs trajets.", "Làm việc từ xa giúp tránh những chuyến đi dài."],
  ["B1", "Il paraît que le nouveau restaurant est excellent.", "Nghe nói nhà hàng mới rất ngon."],
  ["B1", "Les habitants se sont mobilisés pour sauver le parc.", "Người dân đã cùng nhau hành động để cứu công viên."],
  ["B1", "Je vous écris pour me plaindre d'un problème de livraison.", "Tôi viết thư để khiếu nại về sự cố giao hàng."],
  ["B1", "On m'a conseillé de lire ce roman pendant les vacances.", "Người ta khuyên tôi đọc cuốn tiểu thuyết này trong kỳ nghỉ."],
  ["B1", "Elle s'est habituée à la vie en ville assez vite.", "Cô ấy quen với cuộc sống thành phố khá nhanh."],
  ["B1", "Les élèves ont organisé une collecte pour une association.", "Học sinh đã tổ chức quyên góp cho một hội từ thiện."],
  ["B1", "Ce qui me plaît dans ce métier, c'est le contact humain.", "Điều tôi thích ở nghề này là được tiếp xúc với con người."],
  ["B1", "Pendant le confinement, beaucoup de gens ont appris à cuisiner.", "Trong thời gian phong tỏa, nhiều người đã học nấu ăn."],
  ["B1", "Il a raté son train parce que son réveil n'a pas sonné.", "Anh ấy lỡ tàu vì đồng hồ báo thức không reo."],
  ["B1", "Je ne pense pas que ce soit une bonne idée.", "Tôi không nghĩ đó là một ý hay."],
  ["B1", "Les réseaux sociaux ont changé notre façon de communiquer.", "Mạng xã hội đã thay đổi cách chúng ta giao tiếp."],
  ["B1", "Le festival attire chaque année des milliers de visiteurs.", "Lễ hội mỗi năm thu hút hàng nghìn du khách."],
  ["B1", "Elle a démissionné pour créer sa propre entreprise.", "Cô ấy nghỉ việc để thành lập công ty riêng."],
  ["B1", "Si tu veux réussir l'examen, tu dois réviser régulièrement.", "Muốn thi đỗ, bạn phải ôn tập đều đặn."],
  ["B1", "Nous avons été très bien accueillis par la famille.", "Chúng tôi được gia đình đón tiếp rất chu đáo."],
  ["B1", "Le gouvernement veut réduire la consommation d'énergie.", "Chính phủ muốn giảm tiêu thụ năng lượng."],
  ["B1", "Je me demande s'il viendra à la fête samedi.", "Tôi tự hỏi liệu anh ấy có đến bữa tiệc thứ Bảy không."],
  ["B1", "Avant de partir, n'oublie pas d'éteindre les lumières.", "Trước khi đi, đừng quên tắt đèn."],
  ["B1", "La plupart des étudiants travaillent pendant l'été.", "Phần lớn sinh viên đi làm trong mùa hè."],
  ["B1", "Ce quartier est devenu beaucoup plus calme qu'avant.", "Khu phố này yên tĩnh hơn trước rất nhiều."],
  ["B1", "Il est important de manger des fruits et des légumes.", "Ăn rau quả là điều quan trọng."],
  ["B1", "J'aurais aimé voyager davantage quand j'étais étudiant.", "Giá mà hồi sinh viên tôi đi du lịch nhiều hơn."],
  ["B1", "Les places pour le spectacle se sont vendues en une heure.", "Vé xem buổi diễn bán hết trong một giờ."],
  ["B1", "Mon entreprise propose des cours de langue aux salariés.", "Công ty tôi mở lớp ngoại ngữ cho nhân viên."],
  ["B1", "Elle a promis de m'aider à préparer mon entretien.", "Cô ấy hứa giúp tôi chuẩn bị buổi phỏng vấn."],
  ["B1", "Les embouteillages font perdre beaucoup de temps aux conducteurs.", "Tắc đường khiến người lái xe mất rất nhiều thời gian."],
  ["B1", "On ne peut pas tout acheter sur internet.", "Không thể mua mọi thứ trên mạng."],
  ["B1", "Le médecin m'a recommandé de marcher trente minutes par jour.", "Bác sĩ khuyên tôi đi bộ ba mươi phút mỗi ngày."],
  ["B1", "Cette expérience m'a appris à être plus patient.", "Trải nghiệm này dạy tôi kiên nhẫn hơn."],
  ["B1", "Ils se sont rencontrés lors d'un voyage en Italie.", "Họ quen nhau trong một chuyến đi Ý."],
  ["B1", "Je suis d'accord avec toi sur ce point.", "Tôi đồng ý với bạn ở điểm này."],
  ["B1", "Le nombre de touristes a doublé en dix ans.", "Lượng khách du lịch đã tăng gấp đôi trong mười năm."],
  ["B1", "Pour économiser de l'argent, il prépare ses repas lui-même.", "Để tiết kiệm, anh ấy tự nấu ăn."],
  ["B1", "Les bénévoles distribuent des repas aux personnes âgées.", "Các tình nguyện viên phát bữa ăn cho người già."],
  ["B1", "Elle hésite encore entre deux offres d'emploi.", "Cô ấy vẫn còn phân vân giữa hai lời mời làm việc."],
  ["B1", "Le musée sera fermé pendant les travaux de rénovation.", "Bảo tàng sẽ đóng cửa trong thời gian cải tạo."],
  ["B1", "Je compte sur toi pour garder ce secret.", "Tôi trông cậy bạn giữ bí mật này."],
  // B2
  ["B2", "Il est indispensable que les pouvoirs publics investissent dans la recherche.", "Nhà nước cần phải đầu tư vào nghiên cứu."],
  ["B2", "Malgré les critiques, le projet a finalement été adopté.", "Bất chấp chỉ trích, dự án cuối cùng vẫn được thông qua."],
  ["B2", "Les inégalités d'accès aux soins se sont aggravées dans les zones rurales.", "Bất bình đẳng trong tiếp cận y tế gia tăng ở nông thôn."],
  ["B2", "À condition d'être bien encadré, le télétravail améliore la productivité.", "Nếu được quản lý tốt, làm việc từ xa nâng cao năng suất."],
  ["B2", "Cette mesure risque de pénaliser les ménages les plus modestes.", "Biện pháp này có nguy cơ gây thiệt cho các hộ thu nhập thấp."],
  ["B2", "Les spécialistes s'accordent à dire que la situation reste préoccupante.", "Các chuyên gia đều cho rằng tình hình vẫn đáng lo ngại."],
  ["B2", "On reproche souvent aux médias de privilégier le sensationnel.", "Người ta thường trách truyền thông thích giật gân."],
  ["B2", "La réforme a suscité de vives réactions parmi les enseignants.", "Cải cách đã gây phản ứng mạnh trong giới giáo viên."],
  ["B2", "Faute de moyens, l'association a dû réduire ses activités.", "Vì thiếu kinh phí, hội phải thu hẹp hoạt động."],
  ["B2", "Il aurait fallu consulter les habitants avant de lancer les travaux.", "Lẽ ra phải hỏi ý kiến người dân trước khi khởi công."],
  ["B2", "Les entreprises sont incitées à réduire leurs émissions de carbone.", "Các doanh nghiệp được khuyến khích giảm phát thải carbon."],
  ["B2", "Bien que la croissance ait repris, le chômage reste élevé.", "Dù tăng trưởng đã phục hồi, thất nghiệp vẫn cao."],
  ["B2", "L'essor du commerce en ligne fragilise les petits commerçants.", "Sự bùng nổ thương mại điện tử làm suy yếu tiểu thương."],
  ["B2", "Cette découverte pourrait bouleverser notre compréhension du cerveau.", "Phát hiện này có thể làm đảo lộn hiểu biết của chúng ta về não bộ."],
  ["B2", "Les jeunes diplômés peinent à trouver un emploi stable.", "Sinh viên mới ra trường chật vật tìm việc ổn định."],
  ["B2", "Il convient de distinguer les faits des opinions.", "Cần phân biệt sự thật với ý kiến."],
  ["B2", "La municipalité envisage d'étendre la zone piétonne.", "Chính quyền thành phố tính mở rộng khu đi bộ."],
  ["B2", "Cette loi vise à mieux protéger les données personnelles.", "Luật này nhằm bảo vệ dữ liệu cá nhân tốt hơn."],
  ["B2", "Le recours systématique à la voiture pose un problème de santé publique.", "Việc lúc nào cũng dùng ô tô gây ra vấn đề sức khỏe cộng đồng."],
  ["B2", "Nombre de salariés aspirent à un meilleur équilibre entre vie privée et travail.", "Nhiều người lao động mong cân bằng tốt hơn giữa đời tư và công việc."],
  ["B2", "Les autorités ont pris des mesures pour limiter le gaspillage alimentaire.", "Chính quyền đã có biện pháp hạn chế lãng phí thực phẩm."],
  ["B2", "L'apprentissage d'une langue étrangère favorise l'ouverture d'esprit.", "Học ngoại ngữ giúp mở rộng tư duy."],
  ["B2", "Le débat porte essentiellement sur le financement des retraites.", "Cuộc tranh luận chủ yếu xoay quanh nguồn tài chính cho lương hưu."],
  ["B2", "Ces chiffres doivent être interprétés avec prudence.", "Những con số này cần được diễn giải thận trọng."],
  ["B2", "La pénurie de médecins se fait sentir dans de nombreuses régions.", "Tình trạng thiếu bác sĩ thể hiện rõ ở nhiều vùng."],
  ["B2", "Il ne suffit pas de légiférer, encore faut-il appliquer la loi.", "Ban hành luật chưa đủ, còn phải thực thi nó."],
  ["B2", "Le tourisme de masse menace l'équilibre de certains villages.", "Du lịch đại trà đe dọa sự cân bằng của một số làng."],
  ["B2", "Les parents s'inquiètent de l'exposition des enfants aux écrans.", "Phụ huynh lo lắng về việc trẻ tiếp xúc với màn hình."],
  ["B2", "Cette initiative locale a inspiré d'autres communes.", "Sáng kiến địa phương này đã truyền cảm hứng cho các xã khác."],
  ["B2", "Le rapport souligne le rôle essentiel des associations.", "Báo cáo nhấn mạnh vai trò thiết yếu của các hội đoàn."],
  ["B2", "On assiste à un retour en force des produits locaux.", "Chúng ta đang chứng kiến sự trở lại mạnh mẽ của sản phẩm địa phương."],
  ["B2", "Les négociations entre syndicats et patronat sont dans l'impasse.", "Đàm phán giữa công đoàn và giới chủ đang bế tắc."],
  ["B2", "Il serait illusoire de croire que la technologie résoudra tout.", "Thật ảo tưởng nếu tin rằng công nghệ sẽ giải quyết mọi thứ."],
  ["B2", "La transition écologique exige des efforts de la part de tous.", "Chuyển đổi sinh thái đòi hỏi nỗ lực của tất cả mọi người."],
  ["B2", "Les étudiants dénoncent la hausse des frais d'inscription.", "Sinh viên lên án việc tăng học phí."],
  ["B2", "Ce phénomène touche particulièrement les grandes agglomérations.", "Hiện tượng này đặc biệt ảnh hưởng đến các đô thị lớn."],
  ["B2", "La lecture recule chez les adolescents au profit des écrans.", "Việc đọc sách ở tuổi thiếu niên giảm, nhường chỗ cho màn hình."],
  ["B2", "L'entreprise s'est engagée à recruter davantage de femmes ingénieures.", "Công ty cam kết tuyển thêm nhiều nữ kỹ sư."],
  ["B2", "Il est temps de repenser notre modèle de consommation.", "Đã đến lúc xem lại mô hình tiêu dùng của chúng ta."],
  ["B2", "Cette question divise profondément l'opinion publique.", "Vấn đề này chia rẽ sâu sắc dư luận."],
  ["B2", "Les agriculteurs subissent de plein fouet la sécheresse.", "Nông dân hứng chịu trực tiếp hạn hán."],
  ["B2", "Le bénévolat permet d'acquérir des compétences recherchées.", "Làm tình nguyện giúp có được những kỹ năng được săn đón."],
  ["B2", "La généralisation de l'intelligence artificielle soulève des questions éthiques.", "Việc phổ biến trí tuệ nhân tạo đặt ra các câu hỏi đạo đức."],
  ["B2", "Les transports en commun restent insuffisants en périphérie.", "Giao thông công cộng vẫn còn thiếu ở vùng ven."],
  ["B2", "Ce témoignage met en lumière les difficultés des aidants familiaux.", "Lời chứng này làm rõ những khó khăn của người chăm sóc trong gia đình."],
  ["B2", "La fréquentation des musées a nettement progressé cette année.", "Lượng khách đến bảo tàng năm nay tăng rõ rệt."],
  ["B2", "Il faudra du temps avant que les mentalités évoluent.", "Sẽ cần thời gian trước khi não trạng thay đổi."],
  ["B2", "Les consommateurs sont de plus en plus attentifs à l'origine des produits.", "Người tiêu dùng ngày càng chú ý đến nguồn gốc sản phẩm."],
  ["B2", "Ce dispositif a fait ses preuves dans plusieurs pays européens.", "Cơ chế này đã chứng minh hiệu quả ở nhiều nước châu Âu."],
  ["B2", "En définitive, la solution passera par un compromis.", "Rốt cuộc, giải pháp sẽ phải đi qua một sự thỏa hiệp."],
];
