-- 013 — giải thích cho nhóm `temps_present` (45 câu qcm + fill)
--
-- 15 câu `vf` của ba bài này KHÔNG nằm ở đây: chúng đã có sẵn trường
-- `justification` trong payload, và giao diện hiện nó ngay dưới đáp án. Thêm
-- `explanation` vào đó chỉ tạo hai khối chữ nói cùng một điều.
--
-- Thứ tự ưu tiên vẫn là phán đoán sư phạm, KHÔNG phải dữ liệu: chưa có bảng
-- `answers` nên không đo được câu nào hay sai. Xem CLAUDE.md.

update public.questions set explanation = '« Nous » au présent prend toujours -ons. Les deux pièges ici sont des temps différents : « visitions » appartient à l’imparfait et « visiterons » au futur, alors que « le samedi matin » et « toujours » situent l’action dans une habitude présente. « Visitont » n’existe pas : -ont est réservé à ils/elles.' where id = 'msfndrpnpe56p7';
update public.questions set explanation = 'Le sujet « Mes deux petites sœurs » est pluriel : terminaison -ent, muette à l’oral. C’est justement parce qu’on n’entend aucune différence entre « joue » et « jouent » que la faute est si fréquente — il faut chercher le sujet des yeux, pas de l’oreille.' where id = 'msfndrpogfc7am';
update public.questions set explanation = 'Verbe en -ger : sans précaution, le g prendrait le son [g] devant -ons. On ajoute donc un e de liaison → « nous mangeons ». « Mangons » oublie ce e, « mangeions » est l’imparfait, et « mangez » va avec « vous », pas avec « nous ».' where id = 'msfndrpodp3mbn';
update public.questions set explanation = '« Toi et ton frère » équivaut à « vous » : terminaison -ez. Le piège est le sujet composé — dès qu’un « toi » figure dans une liste sans « moi », l’ensemble se remplace par « vous », jamais par « tu ».' where id = 'msfndrpoku3w7e';
update public.questions set explanation = '« Ma grand-mère » est une seule personne : « elle oublie », terminaison -e. « Oublies » irait avec « tu », « oublient » avec « elles ». Quant à « oubli », c’est le nom, pas le verbe.' where id = 'msfndrpoh3cf29';
update public.questions set explanation = '« Tous les élèves » commande les deux verbes : les deux doivent donc être au pluriel. La réponse qui n’accorde que le premier illustre l’erreur classique — quand un sujet gouverne deux verbes éloignés, on oublie le second. Et -ont n’est pas une terminaison du 1er groupe.' where id = 'msfndrpo56o6yj';
update public.questions set explanation = 'Avec « nous », le c de « commencer » doit devenir ç pour garder le son [s] devant -ons : « commençons ». Sans cédille, on lirait [k]. « Commencions » est l’imparfait, et « préparont » invente une terminaison.' where id = 'msfndrporqdegu';
update public.questions set explanation = 'Verbe en é_er : le é de l’avant-dernière syllabe devient è quand la terminaison est muette → « je préfère ». « Prefère » oublie le premier accent, « préfére » garde l’aigu, et « préfèrent » accorde au pluriel alors que le sujet est « je ».' where id = 'msfndrpo852bx4';
update public.questions set explanation = 'Avec « je », les verbes du 1er groupe se terminent par -e : « j’arrive », « j’allume » — jamais par -s, contrairement aux 2e et 3e groupes. C’est la terminaison la plus souvent fautive, par contamination des autres groupes.' where id = 'msfndrpof5gn83';
update public.questions set explanation = '« Vous » demande -ez : « vous parlez ». Attention à ne pas écrire « parler » : l’infinitif et la forme de « vous » se prononcent exactement pareil, et c’est de loin la faute d’orthographe la plus fréquente à l’écrit.' where id = 'msfndrpoupaznt';
update public.questions set explanation = '« Mes amis et moi » équivaut à « nous ». Et « nager » se termine par -ger, d’où le e de liaison devant -ons pour garder le son [ʒ] : « nous nageons », et non « nagons ».' where id = 'msfndrpow7ylxa';
update public.questions set explanation = '« Mes cousins » équivaut à « ils » : terminaison -ent. Ici, pas de e supplémentaire — la règle des verbes en -ger ne joue que devant a et o. D’où « nous voyageons » mais « ils voyagent ».' where id = 'msfndrpoy1wyin';
update public.questions set explanation = '« Acheter » change son e muet en è devant une terminaison muette : « elle achète ». Écrire « achete » est l’erreur attendue, parce que rien dans l’infinitif n’annonce cet accent.' where id = 'msfndrpo682dag';
update public.questions set explanation = '« Tu » prend toujours un -s, y compris au 1er groupe où la forme de « je » n’en a pas : « je téléphone » mais « tu téléphones ». Les deux se prononcent de la même façon, donc l’oreille ne sert à rien.' where id = 'msfndrpoah1y5i';
update public.questions set explanation = '« S’appeler » est un verbe pronominal : le pronom réfléchi change avec le sujet — « tu t’appelles », « je m’appelle ». Oublier ce pronom, ou garder « se » pour toutes les personnes, est l’erreur la plus courante. Notez aussi le doublement du l devant une terminaison muette.' where id = 'msfndrpoyjzfwj';
update public.questions set explanation = '« Choisir » appartient au 2e groupe : son pluriel s’allonge avec l’infixe -iss- → « nous choisissons ». « Choisons » le supprime, « choisissions » est l’imparfait. Repère fiable : si le participe présent est « choisissant », l’infixe est obligatoire.' where id = 'msfnib0hey70ts';
update public.questions set explanation = '« Partir » est du 3e groupe malgré son infinitif en -ir : son radical perd le t au singulier → « il part », sans -iss-. « Partit » est du passé simple, un temps du récit écrit qu’on ne peut pas employer pour un horaire habituel.' where id = 'msfnib0hp07ika';
update public.questions set explanation = '« Grandir » se conjugue comme « finir » : 2e groupe, donc -iss- au pluriel → « ils grandissent ». « Grandent » calque le 1er groupe, et « grandit » laisse le verbe au singulier alors que le sujet est « mes deux neveux ».' where id = 'msfnib0hqmpf87';
update public.questions set explanation = 'Même famille que « partir » : « sortir » est du 3e groupe, donc pas d’infixe -iss- → « ils sortent ». C’est le piège central de cette leçon — la terminaison -ir ne dit pas à quel groupe le verbe appartient.' where id = 'msfnib0hk7jlxo';
update public.questions set explanation = '« Dormir » est du 3e groupe : « vous dormez », sans -iss-. Il fait partie du petit ensemble partir / sortir / dormir / servir / mentir, qui perdent leur consonne finale au singulier et ne prennent jamais l’infixe.' where id = 'msfnib0hebdwzg';
update public.questions set explanation = '« Ouvrir » et « offrir » ont des terminaisons de 1er groupe : « nous ouvrons », « elle offre ». Jamais d’infixe -iss-, et surtout pas « elle offrit », qui est du passé simple alors que toute la phrase est au présent.' where id = 'msfnib0h9wrfsj';
update public.questions set explanation = 'Deux groupes dans la même phrase : « réussir » est du 2e groupe (-iss- au pluriel → réussissent) et « échouer » du 1er (→ échouent). Les intervertir est exactement ce que la question cherche à détecter. Le sujet reste pluriel des deux côtés.' where id = 'msfnib0h9xnvpt';
update public.questions set explanation = '« Venir » double le n à la 3e personne du pluriel : « ils viennent ». « Vienent » avec un seul n est la faute attendue, car l’infinitif ne laisse rien deviner de ce doublement. « Viennissent » ajoute un infixe qui n’appartient qu’au 2e groupe.' where id = 'msfnib0hiz6pg5';
update public.questions set explanation = '« Le cours » est un sujet singulier : « il finit ». L’infixe -iss- des verbes du 2e groupe n’apparaît qu’au pluriel — « nous finissons », mais « il finit ».' where id = 'msfnib0himr0zn';
update public.questions set explanation = '« Réfléchir » est du 2e groupe et « nous » est un pluriel : l’infixe est obligatoire → « nous réfléchissons ». « Nous réfléchons » est l’erreur la plus fréquente de tout ce groupe de verbes.' where id = 'msfnib0ht91z6g';
update public.questions set explanation = '« Sortir » et « partir » perdent leur consonne finale au singulier et prennent -s : « je sors », « je pars ». Ni infixe, ni -e final : « je sortis » serait du passé simple et « je sorte » du subjonctif.' where id = 'msfnib0hzrn3u9';
update public.questions set explanation = '2e groupe avec « vous » : l’infixe reste et la terminaison est -ez → « vous choisissez ». « Vous choisez » supprime l’infixe, comme si le verbe était du 3e groupe.' where id = 'msfnib0holfcq4';
update public.questions set explanation = '« Ouvrir » prend les terminaisons du 1er groupe : « ils ouvrent », avec -ent et sans infixe, malgré son infinitif en -ir. Sa conjugaison ressemble à celle de « parler », pas à celle de « finir ».' where id = 'msfnib0hdtwabq';
update public.questions set explanation = '« Dormir » perd son m au singulier : « tu dors », avec le -s de la 2e personne. « Tu dormes » serait du subjonctif et « tu dormis » du passé simple.' where id = 'msfnib0h28xt9c';
update public.questions set explanation = '« Venir » et « tenir » se conjuguent exactement de la même façon : au singulier, le radical devient vien-/tien- → « il vient », « il tient ». Le n ne double qu’à la 3e personne du pluriel, pas ici.' where id = 'msfnib0hzvh0zo';
update public.questions set explanation = '« Prendre » perd son d devant les terminaisons du pluriel : « nous prenons ». Le n ne double qu’à la 3e personne du pluriel (« ils prennent ») — avec « nous », un seul n.' where id = 'msfnlktn8mging';
update public.questions set explanation = '« Apprendre » et « comprendre » suivent « prendre » : à la 3e personne du pluriel, le n double → « ils apprennent », « ils comprennent ». Un seul n est la faute attendue, car l’infinitif n’annonce pas ce doublement.' where id = 'msfnlktnqs5jd1';
update public.questions set explanation = 'Les deux verbes dépendent du même sujet « vous » : « vous êtes », « vous avez ». La réponse « êtes / avons » change de sujet en cours de phrase — vérifiez toujours que le second verbe garde le sujet du premier. Et « estes » n’existe pas : « être » s’apprend par cœur.' where id = 'msfnlktnrgcxsx';
update public.questions set explanation = '« Ma sœur et moi » équivaut à « nous ». « Aller » donne « nous allons » et « faire » donne « nous faisons » : attention à l’orthographe, on prononce [fəzɔ̃] mais on écrit fai-, jamais « fesons ».' where id = 'msfnlktnfa8gbu';
update public.questions set explanation = 'Avec « je », « pouvoir » et « devoir » prennent -x et -s : « je peux », « je dois ». Le x de « je peux » — comme celui de « je veux » — est une survivance orthographique : écrire « je peus » est logique, mais faux.' where id = 'msfnlktn3jq1j2';
update public.questions set explanation = '« Dire » donne « ils disent » et « voir » donne « ils voient » : le y de « nous voyons » disparaît devant une terminaison muette. « Voyent » est précisément la faute attendue.' where id = 'msfnlktnkid03j';
update public.questions set explanation = 'Deux sujets singuliers distincts — « mon père », « ma mère » — donc deux verbes au singulier : « il lit », « elle boit ». La réponse au pluriel est tentante parce que la phrase parle de deux personnes, mais chacune a son propre verbe.' where id = 'msfnlktnfiiwpf';
update public.questions set explanation = '« Savoir » s’emploie devant une proposition (« savez où se trouve… ») et « connaître » devant un nom (« ce quartier »). Intervertir les deux est l’erreur la plus fréquente avec ces verbes, qui se rendent souvent par un seul mot dans d’autres langues.' where id = 'msfnlktnxzxz33';
update public.questions set explanation = '« Être » et « avoir » sont les deux verbes les plus irréguliers du français : « je suis », « j’ai ». Notez l’élision obligatoire — on écrit « j’ai », jamais « je ai ».' where id = 'msfnlktnc437sw';
update public.questions set explanation = 'Avec « nous », « venir » et « vouloir » retrouvent un radical régulier : « nous venons », « nous voulons ». Ni doublement du n, ni -eu- : ces irrégularités n’apparaissent qu’au singulier et à la 3e personne du pluriel (je viens, je veux, ils viennent, ils veulent).' where id = 'msfnlktn49cqwa';
update public.questions set explanation = '« Savoir » donne « je sais » et « tu sais » : deux formes identiques à l’oral comme à l’écrit. Le radical sav- ne réapparaît qu’au pluriel, dans « nous savons » et « vous savez ».' where id = 'msfnlktn068rvh';
update public.questions set explanation = '« Faire » a une 3e personne du pluriel irrégulière : « ils font », comme « ils sont », « ils ont » et « ils vont » — les quatre seuls verbes en -ont du français. Et « pouvoir » avec « je » donne « je peux », avec un x.' where id = 'msfnlktn7tidjb';
update public.questions set explanation = '« Le professeur » est singulier (« il écrit ») et « les élèves » est pluriel (« ils prennent »). Quand une phrase contient deux sujets différents, chaque verbe s’accorde avec le sien — et « prendre » double le n au pluriel.' where id = 'msfnlktnysra3i';
update public.questions set explanation = '« Aller » est irrégulier au point que son infinitif ne ressemble à aucune de ses formes conjuguées. Avec « vous », c’est « vous allez » : avec « nous allons », la seule forme du présent qui conserve le radical all-.' where id = 'msfnlktniornzy';
update public.questions set explanation = '« On » se conjugue toujours comme « il / elle », même lorsqu’il désigne « nous » : « on doit », « on risque », au singulier. L’accorder au pluriel est l’erreur la plus fréquente avec ce pronom.' where id = 'msfnlktn0syws6';
