-- 014 — giải thích cho nhóm `lexique_thematique` (30 câu)
--
-- Ba bài rất khác nhau, nên cách viết cũng khác:
--   · Écologie B1 (10 qcm) — tách các thuật ngữ hay bị lẫn: empreinte carbone
--     với empreinte écologique, effet de serre với couche d’ozone, fossile với
--     nucléaire.
--   · Le quotidien A1 (10 qcm) — dạy cả TRƯỜNG TỪ VỰNG, vì ba phương án sai
--     đều là từ đáng học chung với đáp án (bốn bữa ăn, các cửa hàng, các ngày).
--   · Caractéristiques morales B1 (10 câu sắp xếp) — vừa trật tự từ vừa nghĩa
--     của tính từ; nhiều câu hỏng vì thiếu giới từ đi kèm (jaloux DE,
--     confiance EN).
--
-- Thứ tự ưu tiên vẫn là phán đoán sư phạm, KHÔNG phải dữ liệu. Xem CLAUDE.md.

update public.questions set explanation = 'L’empreinte carbone ne mesure que les gaz à effet de serre, exprimés en équivalent CO₂. La deuxième réponse décrit l’empreinte écologique, qui se compte en hectares de surface : deux indicateurs voisins que les médias confondent constamment.' where id = 'mriey00yi6n2xo';
update public.questions set explanation = 'La biodiversité couvre à la fois les espèces vivantes et les milieux où elles évoluent — le mot ne se limite pas aux animaux et aux plantes. La dernière réponse applique l’idée de « diversité » aux sources d’énergie, ce qui n’a aucun rapport avec le vivant.' where id = 'mriey00yo7c5fn';
update public.questions set explanation = 'L’effet de serre est le mécanisme de rétention de la chaleur ; la couche d’ozone, elle, filtre les rayons ultraviolets. Deux phénomènes distincts, régulièrement mélangés. Retenez aussi que l’effet de serre est naturel : c’est son renforcement par l’activité humaine qui pose problème.' where id = 'mriey00yt1lobt';
update public.questions set explanation = '« Écoresponsable » décrit une démarche continue de réduction de l’impact, pas une perfection atteinte. Les trois autres réponses proposent des engagements absolus — exclusivement recyclé, aucun numérique, tous les bénéfices reversés — et c’est ce caractère extrême qui les disqualifie.' where id = 'mriey00y97atf7';
update public.questions set explanation = '« Trier », c’est séparer les déchets selon leur nature, en amont du recyclage. Brûler, c’est « incinérer » ; enterrer, c’est « enfouir » ; acheter moins, c’est « réduire ». Chaque distracteur correspond à un verbe précis du même champ lexical : il vaut la peine de les apprendre ensemble.' where id = 'mriey00y91kdsp';
update public.questions set explanation = 'Le préfixe « dé- » indique la suppression : la déforestation est la disparition du couvert forestier. Deux réponses décrivent le mouvement inverse, le reboisement. Et le mot désigne le phénomène lui-même, jamais la loi qui l’interdit.' where id = 'mriey00yqpgbye';
update public.questions set explanation = '« Fossile » renvoie à l’origine de la ressource : des organismes enfouis depuis des millions d’années — pétrole, charbon, gaz naturel. Le nucléaire n’est pas fossile, puisqu’il vient d’un minerai, mais il n’est pas renouvelable non plus : c’est la troisième catégorie, celle qu’on oublie dans l’opposition habituelle.' where id = 'mriey00yyt123f';
update public.questions set explanation = '« Co- » signifie « ensemble » : covoiturer, c’est partager un même véhicule pour un trajet commun. Le bénéfice vient du nombre de voitures en moins, et non du type de véhicule ni de l’itinéraire choisi — ce qui élimine les réponses parlant d’électrique ou d’autoroute.' where id = 'mriey00yd90903';
update public.questions set explanation = '« Renouvelable » porte sur la reconstitution de la ressource, pas sur son prix, son stockage ni sa simplicité technique. C’est un critère de disponibilité à l’échelle humaine : le soleil et le vent se renouvellent, le pétrole non.' where id = 'mriey00yt3uwz7';
update public.questions set explanation = '« Transition » implique un passage progressif d’un modèle à un autre, pas une rupture brutale. Les trois distracteurs remplacent tous cette progressivité par une mesure radicale et immédiate — interdiction totale, transfert intégral, suppression au profit exclusif de.' where id = 'mriey00yobkwgc';
update public.questions set explanation = 'Les quatre réponses forment la journée alimentaire française : petit déjeuner (matin), déjeuner (midi), goûter (vers seize heures), dîner (soir). Le piège pour un débutant : « déjeuner » tout seul désigne le repas de MIDI — celui du matin s’appelle « petit déjeuner ».' where id = 'mrkm60ck80vv9c';
update public.questions set explanation = 'Le bus, le métro, le train, le vélo et la voiture sont des « moyens de transport ». Retenez la construction entière : « un moyen de transport », avec « de » et sans article devant le dernier mot.' where id = 'mrkm60ckmzn5dn';
update public.questions set explanation = 'On dort dans un lit, qui se trouve dans la chambre. Les autres réponses sont bien des meubles ou des objets de la maison, mais chacun a sa pièce : le frigo à la cuisine, le bureau pour travailler, le placard pour ranger.' where id = 'mrkm60ckcv8n5w';
update public.questions set explanation = 'Les noms de commerces se forment souvent sur le produit suivi de -erie : le pain → la boulangerie, les gâteaux → la pâtisserie, la viande → la boucherie. Attention au piège interne : une « librairie » vend des LIVRES, pas du pain — et les médicaments sont à la pharmacie.' where id = 'mrkm60ckq77tei';
update public.questions set explanation = 'Le manteau se porte quand il fait froid. Les trois autres réponses appartiennent au vocabulaire de l’été — short, maillot de bain, chapeau de soleil : la question teste moins le mot lui-même que son association avec la saison.' where id = 'mrkm60cknyp099';
update public.questions set explanation = 'On BOIT de l’eau, tandis que le pain, le fromage et le gâteau se mangent. Notez aussi l’élision obligatoire devant une voyelle : « un verre d’eau », jamais « un verre de eau ».' where id = 'mrkm60ckdwqpg5';
update public.questions set explanation = 'On se lave les mains avec de l’eau et du savon. Les trois autres réponses sont des produits alimentaires : le sucre, le sel et le café se trouvent à la cuisine, pas dans la salle de bains.' where id = 'mrkm60ck0e44vp';
update public.questions set explanation = 'Les jours de la semaine dans l’ordre : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche. Après lundi vient donc mardi. Notez qu’en français les jours s’écrivent avec une minuscule, contrairement à l’anglais.' where id = 'mrkm60ck4o3z9s';
update public.questions set explanation = 'On « regarde la télévision » : le verbe demande ici quelque chose qu’on observe volontairement, et seule la télévision en est un parmi les réponses. À l’oral, le mot s’abrège couramment en « la télé ».' where id = 'mrkm60ckdojbmn';
update public.questions set explanation = 'On écrit sur une feuille de papier — la structure « une feuille de + matière » est fixe. Le bois est tentant puisque le papier en est fabriqué, mais « une feuille de bois » ne se dit pas pour écrire.' where id = 'mrkm60ckk3xq4y';
update public.questions set explanation = '« Ordonné » qualifie une personne qui range et classe ses affaires : l’adjectif vient du verbe « ordonner », mettre en ordre. Pour l’ordre des mots, « car » relie deux propositions complètes et se place obligatoirement entre elles — jamais en tête de phrase.' where id = 'jtl8k4m';
update public.questions set explanation = 'La négation encadre le verbe conjugué : ne + dit + jamais. Déplacer « jamais » ailleurs dans la phrase est l’erreur la plus fréquente. Et « un menteur » est celui qui ment : le nom se forme sur le verbe « mentir ».' where id = 'e6loo50';
update public.questions set explanation = '« Avoir confiance EN » : c’est l’expression qui impose la préposition, et ce qui suit est un pronom tonique — « en lui », jamais « en il ». Notez également qu’on dit « avoir confiance » sans article.' where id = 'gac4r1e';
update public.questions set explanation = 'Deux adjectifs coordonnés qualifient le même sujet pluriel : les deux prennent donc le -s. « Aimable » (agréable, gentil) et « sociable » (qui aime la compagnie) sont proches mais distincts — et « sociable » ne signifie pas « social ».' where id = 'o63qpp1';
update public.questions set explanation = '« Voir tout en noir » est une expression imagée : n’envisager que le pire. C’est la définition même du pessimiste, dont le contraire est l’optimiste. Ici les deux propositions peuvent s’inverser, la cause pouvant précéder ou suivre la conséquence.' where id = 'rb1jj0g';
update public.questions set explanation = 'Expression figée : se dit de quelqu’un qui a l’air parfaitement innocent — souvent avec l’idée qu’il ne l’est pas vraiment. Comme toute expression figée, l’ordre des mots ne se discute pas, et le verbe reste au conditionnel : « on donnerait ».' where id = 't2h9vjy';
update public.questions set explanation = '« Distrait » qualifie celui dont l’attention se disperse. C’est la cause, introduite par « car », qui vient donc en seconde position. Attention aussi à l’adverbe : « toujours » se place juste après le verbe conjugué, pas avant lui.' where id = 'zw5huo1';
update public.questions set explanation = '« Jaloux DE » : l’adjectif impose sa préposition, comme « fier de » ou « content de ». Retenir l’adjectif sans la préposition qui l’accompagne est ce qui fait échouer la phrase, même quand le sens est parfaitement compris.' where id = '5lcp0ss';
update public.questions set explanation = 'Impératif négatif : « ne » et « pas » encadrent le verbe → « Ne soyez pas ». L’adjectif s’accorde avec le « vous » pluriel, d’où le -s d’« égoïstes ». Le second verbe reste à l’impératif affirmatif, sans pronom sujet.' where id = 's0m9r7j';
update public.questions set explanation = '« Pour » suivi de l’infinitif exprime le but, et ce groupe placé en tête de phrase est détaché par une virgule. « Il faut » est un verbe impersonnel : il se construit avec un infinitif et son sujet « il » ne change jamais.' where id = '4u00rj7';
