-- 015 — giải thích cho bốn nhóm còn lại (69 câu)
--   but_hypothese 15 · formation_mots 24 · temps_futur 15 · temps_passe 15
--
-- 10 câu `vf` (futur 5, passé 5) bỏ qua: đã có `justification` sẵn, như 013.
--
-- PHẦN CUỐI sửa ba đáp án SAI trong chính đáp án mẫu — học sinh gõ đúng tiếng
-- Pháp chuẩn mà vẫn bị chấm sai. Không thể viết giải thích hợp thức hoá chúng.

update public.questions set explanation = 'Ce qui suit le blanc est un groupe nominal — « ce grand voyage » — et seul « pour » se construit directement avec un nom. « Afin de » appelle obligatoirement un infinitif, « pour que » une proposition au subjonctif.' where id = 'msd6141uirvkls';
update public.questions set explanation = 'Le sujet est le même des deux côtés : c’est lui qui emprunte et lui qui paie. Même sujet impose l’infinitif → « afin de payer ». Dès que le sujet ne change pas, « pour que » et « afin que » sont interdits, quelle que soit la phrase.' where id = 'msd6141ucekhot';
update public.questions set explanation = 'Deux sujets différents : ce sont « mes parents » qui prêtent, mais « je » qui pars. Ce changement impose « pour que » suivi du subjonctif, d’où « puisse » et non « peux ». « Puisque » exprimerait la cause, pas le but.' where id = 'msd6141u3nr8i3';
update public.questions set explanation = '« Le professeur » parle, mais ce sont « les élèves » qui comprennent : sujets différents, donc « afin que » + subjonctif. « Parce que » est le piège de sens — il donnerait la cause de sa façon de parler, alors que la phrase en exprime le but.' where id = 'msd6141u51ytcs';
update public.questions set explanation = 'C’est « je » qui se lève et « je » qui veut avoir le temps : même sujet, donc infinitif après « pour ». Les autres réponses introduisent toutes une proposition avec sujet exprimé, ce qui est impossible quand ce sujet est déjà celui du premier verbe.' where id = 'msd6141u9m5chc';
update public.questions set explanation = 'Chaque phrase fausse illustre une erreur différente : « pour que » suivi d’un infinitif, « pour qu’ » suivi de l’indicatif au lieu du subjonctif, et « afin que » suivi d’un infinitif. Seule « afin de réussir » respecte la règle — locution en « de » + infinitif, sujet unique.' where id = 'msd6141ua788t5';
update public.questions set explanation = 'La ville construit, les habitants se déplacent : deux sujets, donc « pour que » + subjonctif → « puissent », et non « peuvent ». « Afin que » conviendrait tout aussi bien, mais la réponse qui le propose met l’indicatif.' where id = 'msd6141uf2u1y6';
update public.questions set explanation = 'Même sujet — il met son réveil, il ne veut pas rater son avion — donc infinitif. Observez surtout la négation : à l’infinitif, « ne pas » reste groupé DEVANT le verbe → « afin de ne pas rater », jamais « afin de ne rater pas ».' where id = 'msd6141u1b9vg3';
update public.questions set explanation = 'Après le blanc vient un groupe nominal, « nos enfants » : seul « pour » l’accepte directement. On dit « un cadeau pour toi », jamais « afin de toi ». Ici, « pour » exprime d’ailleurs le destinataire autant que le but.' where id = 'msd6141uz2686m';
update public.questions set explanation = 'Le médecin prescrit, elle dort : sujets différents, donc subjonctif → « afin qu’elle puisse ». Les réponses à l’indicatif — « dort », « peut » — sont la faute attendue, le subjonctif s’oubliant d’autant plus facilement qu’il n’existe pas dans beaucoup de langues.' where id = 'msd6141u5xsz1l';
update public.questions set explanation = 'Ce qui suit est un nom, « mon futur travail » : « pour » se construit directement avec lui. « Afin de » serait impossible ici, cette locution appelant obligatoirement un infinitif.' where id = 'msd6141uweyom8';
update public.questions set explanation = '« Afin de » est la variante formelle de « pour », en deux mots comme le demande la consigne. Devant une voyelle, « de » s’élide → « afin d’acheter ». Le sujet ne changeant pas, l’infinitif est obligatoire.' where id = 'msd6141ubpopq5';
update public.questions set explanation = '« Puisses » est un subjonctif, et sa seule présence impose une conjonction en « que ». Le changement de sujet le confirme — je laisse, tu entres — donc « pour que » ou « afin que », jamais l’infinitif.' where id = 'msd6141un2osch';
update public.questions set explanation = 'Après « afin que », le subjonctif est obligatoire : « comprendre » donne « qu’il comprenne », avec deux n et un e final. Écrire « comprend » est l’erreur la plus fréquente, parce que l’indicatif vient spontanément.' where id = 'msd6141ux2kpmv';
update public.questions set explanation = '« Mes sœurs et moi » équivaut à « nous », et après « pour que » le verbe passe au subjonctif → « que nous puissions ». Attention au sujet composé : c’est lui qui commande l’accord, pas le mot le plus proche du blanc.' where id = 'msd6141uohp4if';
update public.questions set explanation = 'Le suffixe -able s’ajoute à un radical verbal pour dire « qu’on peut faire » : faire → faisable, lire → lisible, boire → buvable. Le radical utilisé est celui du présent avec « nous » (nous faisons), et non l’infinitif.' where id = 'mrh4rnvmynpnmz';
update public.questions set explanation = 'Le suffixe -ateur désigne l’objet ou la personne qui accomplit l’action : adapter → adaptateur, ventiler → ventilateur. Le contexte — « a branché » — impose un objet concret, donc pas « adaptation », qui nommerait le processus.' where id = 'mrh4s1gijv4bso';
update public.questions set explanation = 'Le suffixe -eux forme des adjectifs à partir de noms : fièvre → fiévreux, peur → peureux, chance → chanceux. Attention au changement d’accent dans le radical : le è de « fièvre » devient é dans « fiévreux ».' where id = 'mrh4se6np69u53';
update public.questions set explanation = 'Le sigle ONU se lit comme un mot et reçoit le suffixe adjectival -ien : « onusien ». Il s’accorde ici avec « l’institution », féminin singulier → « onusienne », et s’écrit tout en minuscules, contrairement au sigle lui-même.' where id = 'mrh4si8hl6ir98';
update public.questions set explanation = '« Natal » et « naître » viennent du même radical latin, mais par deux voies différentes — le dérivé n’est donc pas reconnaissable dans le verbe de départ. « Maison natale » est une collocation figée : celle où l’on est né. L’adjectif s’accorde au féminin en « natale ».' where id = 'mrh4sreiqzsb4x';
update public.questions set explanation = 'Le suffixe -age nomme l’action ou son résultat : savon → savonnage, laver → lavage, masser → massage. La phrase le confirme d’elle-même, puisque « lavage » et « massage » l’encadrent. Notez le doublement du n.' where id = 'mrh4tyw4dd08l4';
update public.questions set explanation = 'L’adjectif « long » donne le verbe « prolonger », c’est-à-dire rendre plus long. La forme pronominale s’impose ici : le froid dure de lui-même, personne ne l’allonge — c’est la valeur du pronom « se » avec un sujet non animé.' where id = 'mrh4u7ild9teft';
update public.questions set explanation = 'Chaîne complète de dérivation : le nom « soin » donne l’adjectif « soigneux », qui donne l’adverbe « soigneusement ». Les adverbes en -ment se forment sur le FÉMININ de l’adjectif — soigneuse + ment. Il faut bien un adverbe ici, puisque le mot modifie le participe « préparé ».' where id = 'mrh4uicsau91py';
update public.questions set explanation = 'Du nom « jet » on remonte au verbe « jeter », auquel s’ajoute le préfixe « re- », qui marque le renvoi vers l’extérieur. Attention à l’orthographe : devant une terminaison muette, « jeter » double son t → « il rejette » (l’orthographe rectifiée de 1990 admet aussi « il rejète »).' where id = 'mrh4uuybxo82yr';
update public.questions set explanation = 'Ici la dérivation va en sens inverse : du verbe on remonte au nom, en retirant la terminaison — embarrasser → embarras. Le nom garde les deux r et les deux s, mais perd le e final. « Être dans l’embarras » est une expression figée.' where id = 'mrh4v1il8hsjuo';
update public.questions set explanation = 'Encore le suffixe -age de l’activité : bricoler → bricolage, comme jardiner → jardinage. Après « matériel de », il faut obligatoirement un nom, jamais l’infinitif du verbe.' where id = 'mrh4v96e5a56qn';
update public.questions set explanation = 'Le radical savant d’« arbre » est arbor-, hérité du latin : arbre → arboriculture, comme vigne → viticulture. C’est ce passage par la forme latine qui rend le mot difficile à retrouver — et qui explique le r que l’on oublie si souvent.' where id = 'mrh4vaysa3ptm6';
update public.questions set explanation = 'Le suffixe -ement transforme un verbe en nom d’action : entraîner → entraînement, changer → changement. L’accent circonflexe du verbe se conserve dans le nom dérivé.' where id = 'mrh5c2dp1e0wpo';
update public.questions set explanation = '« Cher » donne le verbe « enchérir » — rendre plus cher — formé avec le préfixe en- et la terminaison -ir. Comme tout verbe du 2e groupe, son participe présent prend l’infixe -iss- → « enchérissant », qui équivaut ici à « ce qui augmente ».' where id = 'mrh5c3e3trpdmm';
update public.questions set explanation = 'Le radical savant de « paix » est pac-, du latin pax : paix → pacifique, pacifiste, pacifier. Le lien entre les deux mots ne se voit qu’en passant par le latin. L’adjectif s’accorde avec « les idées », féminin pluriel → « pacifiques ».' where id = 'mrh5c4gwvcx3q2';
update public.questions set explanation = '« Trahir » donne le nom « trahison » : le h se conserve, mais la finale change complètement — ni « trahissement », ni « trahition ». Le suffixe -ison est rare, d’où la difficulté ; comparez avec guérir → guérison.' where id = 'mrh5c575lm4ned';
update public.questions set explanation = 'Le suffixe -ité transforme un adjectif en nom abstrait de qualité : digne → dignité, rapide → rapidité, sincère → sincérité. Le e final de l’adjectif disparaît devant le suffixe.' where id = 'mrh5c60jz8n4js';
update public.questions set explanation = 'Du nom « souci » vient l’adjectif « soucieux », que le préfixe négatif in- vient inverser. La forme usuelle est « insouciant / insouciante », bâtie sur le participe « souciant ». L’adjectif s’accorde avec « une personne », féminin singulier.' where id = 'mrh5c6y9bnitt3';
update public.questions set explanation = 'Le nom « examen » donne le verbe « examiner », puis le nom d’agent en -ateur : « examinateur ». Attention au radical, qui perd le e de « examen » et prend un i — examin-, et non examen-.' where id = 'mrh5dk3mayogb4';
update public.questions set explanation = 'Même chaîne qu’à « soigneusement » : le nom « anxiété » donne l’adjectif « anxieux », puis l’adverbe formé sur son féminin — anxieuse + ment. Le mot modifie ici un verbe, ce qui exige bien un adverbe et non un adjectif.' where id = 'mrh5dksm4n3xbt';
update public.questions set explanation = '« Intense » donne « intensément », et non « intensement » : quand l’adjectif se termine par un e muet, l’adverbe prend souvent un accent aigu sur le e du suffixe — comme énorme → énormément, aveugle → aveuglément.' where id = 'mrh5dlcfuatjj4';
update public.questions set explanation = 'Formé sur le participe passé « décidé » + -ment. Mais attention au sens : « décidément » ne veut pas dire « de façon décidée » — c’est un adverbe de commentaire, qui signifie « vraiment, il faut bien le constater ». Un dérivé peut s’éloigner beaucoup du verbe de départ.' where id = 'mrh5dlsg1coa8p';
update public.questions set explanation = 'De l’adjectif « doux » on forme le verbe « adoucir » avec le préfixe a- : rendre plus doux. Le radical passe par le féminin — douc-, comme dans « douce » — d’où le c et non le x. Verbe du 2e groupe, donc « il adoucit ».' where id = 'mrh5dmdhxy5rds';
update public.questions set explanation = 'Encore le suffixe -age de l’action : raser → rasage. « Après-rasage » est un nom composé calqué sur l’anglais after-shave, et il s’écrit avec un trait d’union.' where id = 'mrh5dmwvfgpepn';
update public.questions set explanation = '« Mes parents et moi » équivaut à « nous » : au futur simple, la terminaison est -ons → « nous passerons ». « Passerions » est le conditionnel — un seul i les sépare, et c’est la confusion la plus fréquente de toute la leçon. « Passeront » irait avec « ils ».' where id = 'msfnsuegbiy4ub';
update public.questions set explanation = 'Après « quand », le français emploie le FUTUR, là où beaucoup de langues gardent le présent : « quand tu auras », jamais « quand tu as ». Et « pouvoir » a un radical irrégulier au futur, pourr- avec deux r → « tu pourras ».' where id = 'msfnsuegz2jjkb';
update public.questions set explanation = '« Venir » est irrégulier au futur : son radical devient viendr- → « ils viendront ». Les terminaisons, elles, sont parfaitement régulières et identiques pour tous les verbes du français : -ai, -as, -a, -ons, -ez, -ont.' where id = 'msfnsueg3rfe9g';
update public.questions set explanation = '« Faire » donne fer- au futur : « nous ferons ». Attention ensuite à l’accent — « amener » prend un è devant une syllabe muette, et cet accent se maintient à toutes les personnes du futur → « ils amèneront ».' where id = 'msfnsueghby14i';
update public.questions set explanation = '« Pleuvoir » est impersonnel et irrégulier : son futur est « il pleuvra », sans e — « pleuvera » est exactement la faute attendue. Le second verbe doit rester au futur lui aussi : « reporterions » serait un conditionnel, alors que la phrase ne pose aucune condition.' where id = 'msfnsuegu3leev';
update public.questions set explanation = '« Aller » a un futur totalement irrégulier, bâti sur ir- : « j’irai ». Rien dans l’infinitif ne le laisse deviner, il faut le mémoriser. Et « j’irais » avec -s serait du conditionnel, un temps qui n’a rien à faire dans un projet annoncé comme certain.' where id = 'msfnsuegx5m31j';
update public.questions set explanation = '« Recevoir » et « devoir » perdent la voyelle de leur infinitif au futur : recevr-, devr-. Presque tous les verbes en -oir sont irréguliers de cette façon — voir → verr-, savoir → saur-, pouvoir → pourr-.' where id = 'msfnsuegj6fb9u';
update public.questions set explanation = 'Encore « quand » suivi du futur, obligatoire en français. « Être » donne ser- et « voir » donne verr-, avec deux r. Ne fabriquez pas « voirons » à partir de l’infinitif : les verbes en -oir ne construisent presque jamais leur futur sur lui.' where id = 'msfnsueg5lysh9';
update public.questions set explanation = 'Pour un verbe du 1er groupe, le futur se forme sur l’INFINITIF COMPLET, auquel on ajoute la terminaison : visiter + ai = « je visiterai ». Le e de l’infinitif se conserve à l’écrit, même s’il ne s’entend presque pas.' where id = 'msfnsuegkj7omn';
update public.questions set explanation = 'Après « quand », le futur est obligatoire : « quand tu seras ». Et « envoyer » est irrégulier — son radical devient enverr-, avec deux r, alors que l’infinitif n’en compte qu’un seul.' where id = 'msfnsueg4whnt3';
update public.questions set explanation = '« Aller » donne ir- : « nous irons ». « Falloir » est impersonnel, il n’existe qu’à la 3e personne du singulier, et son futur est « il faudra » — à ne pas confondre avec « il faudrait », qui serait un conditionnel.' where id = 'msfnsueg2uzhbo';
update public.questions set explanation = '« Venir » prend un d au futur : viendr- → « ils viendront ». C’est le même d que dans tenir → tiendr- et vouloir → voudr-. La phrase le confirme d’ailleurs, puisque le second verbe est déjà au futur : « apporteront ».' where id = 'msfnsueg3coikv';
update public.questions set explanation = '« Pouvoir » donne pourr- au futur, avec deux r : « vous pourrez ». Un seul r produirait « vous pourez », qui n’existe pas. Notez au passage que le futur sert ici à formuler une demande polie.' where id = 'msfnsuegy9zfup';
update public.questions set explanation = 'Verbe du 1er groupe : infinitif complet + terminaison → travailler + a = « elle travaillera ». La 3e personne du singulier se termine par -a et jamais par -as : « elle travaillera », mais « tu travailleras ».' where id = 'msfnsuegzuag62';
update public.questions set explanation = 'Les verbes en -RE perdent leur e final avant les terminaisons du futur : prendre → prendr- → « nous prendrons ». La règle vaut pour tout le groupe — boire → boirons, écrire → écrirons, dire → dirons.' where id = 'msfnsuegk7g89w';
update public.questions set explanation = '« Regarder » se conjugue avec « avoir », et sans complément d’objet placé avant le verbe, le participe reste invariable : « nous avons regardé », sans s malgré le sujet pluriel. C’est l’erreur la plus fréquente du passé composé — on accorde avec le sujet par réflexe.' where id = 'msfo85wult88cn';
update public.questions set explanation = '« Arriver » et « rester » appartiennent aux verbes de déplacement et d’état qui se conjuguent avec « être ». Et avec « être », le participe s’accorde bien avec le sujet : « ma sœur » est féminin singulier → arrivée, restée, un e chacun.' where id = 'msfo85wufq0y00';
update public.questions set explanation = '« Se lever » est pronominal, et les pronominaux prennent TOUJOURS « être », jamais « avoir » : « je me suis levé », et non « je m’ai levé ». Le second verbe, « prendre », n’est pas pronominal et garde « avoir » ; son participe « pris » est irrégulier.' where id = 'msfo85wunjqkl6';
update public.questions set explanation = 'Deux auxiliaires dans la même phrase : « venir » prend « être », d’où l’accord au féminin pluriel → « venues » ; « apporter » prend « avoir », d’où l’absence d’accord → « apporté ». C’est exactement ce contraste que la question cherche à tester.' where id = 'msfo85wucnw542';
update public.questions set explanation = '« Prendre » et « mettre » ont des participes irréguliers et très courts : « pris », « mis ». Les formes régularisées « prendu » et « mettu » n’existent pas. Et le s de « mis » appartient au mot lui-même au masculin singulier — ce n’est pas une marque de pluriel.' where id = 'msfo85wubjvsm9';
update public.questions set explanation = '« Lire » a un participe irrégulier très court : « lu ». Dans la seconde partie, le pronom « que » reprend « le livre » et se trouve placé avant le verbe : l’accord se ferait donc — mais « livre » étant masculin singulier, « prêté » ne change pas de forme.' where id = 'msfo85wu55v14e';
update public.questions set explanation = 'À la forme négative, « ne » et « pas » encadrent l’AUXILIAIRE et non le participe : « nous ne sommes pas allés ». « Aller » prend « être », d’où l’accord au pluriel. Mais « pleuvoir » prend « avoir » : « il a plu », sans accord, puisque « il » y est impersonnel.' where id = 'msfo85wuawj1m7';
update public.questions set explanation = '« Naître » se conjugue avec « être » et son participe « né » est irrégulier, très éloigné de l’infinitif ; il s’accorde ici au masculin pluriel. « Vivre » prend « avoir » et donne « vécu ». Deux verbes dans une même phrase, deux auxiliaires différents.' where id = 'msfo85wuzbwx2f';
update public.questions set explanation = 'Passé composé = auxiliaire au présent + participe passé. « Manger » prend « avoir » et son participe se termine par -é : « j’ai mangé ». Ne confondez pas ce -é avec l’infinitif -er : les deux se prononcent exactement pareil, et c’est la faute d’orthographe la plus répandue du français.' where id = 'msfo85wuwxc052';
update public.questions set explanation = '« Aller » et « rester » prennent tous deux « être », donc accord avec le sujet. « Ma famille et moi » équivaut à « nous », et le masculin pluriel s’impose dès qu’un homme est inclus dans le groupe → « allés », « restés ».' where id = 'msfo85wu2sxvdn';
update public.questions set explanation = '« Voir » donne le participe irrégulier « vu ». Dans la seconde partie, « le message » est repris par « que » placé avant le verbe : l’accord se ferait, mais le mot est masculin singulier, donc « envoyé » ne bouge pas.' where id = 'msfo85wuo2loyd';
update public.questions set explanation = '« Se réveiller » est pronominal, donc « être » : « elle s’est réveillée », avec accord au féminin. « Rater » n’est pas pronominal et garde « avoir » : « a raté », sans accord. Le contraste tient dans une seule phrase, avec le même sujet.' where id = 'msfo85wut3x7rq';
update public.questions set explanation = 'Deux participes irréguliers à mémoriser : faire → fait, offrir → offert. Les deux verbes prennent « avoir ». Et le pronom « m’ » est ici un complément indirect — on offre quelque chose À quelqu’un — donc il ne déclenche aucun accord.' where id = 'msfo85wu1erq93';
update public.questions set explanation = '« Naître » prend « être » : « vous êtes né ». « Vouloir » prend « avoir » et donne le participe « voulu ». Notez que la phrase se corrige elle-même : « l’année dernière » est incompatible avec une naissance, d’où la reformulation qui suit.' where id = 'msfo85wu6x0dz8';
update public.questions set explanation = '« Prendre » se conjugue avec « avoir » — « nous avons pris » — mais « partir » avec « être » : « il est parti ». Ces deux verbes se ressemblent par le sens (on prend un train, le train part), et c’est précisément pourquoi on leur attribue le même auxiliaire par erreur.' where id = 'msfo85wulw10co';

-- ── sửa đáp án mẫu ──
-- « aboriculture » sai chính tả; đúng là « arboriculture » (radical latin arbor-).
update public.questions
   set payload = jsonb_set(payload, '{accepted}', '"arboriculture"')
 where id = 'mrh4vaysa3ptm6';

-- « rejète » là biến thể chỉnh lý 1990; « rejette » mới là dạng chuẩn. Nhận cả hai.
update public.questions
   set payload = jsonb_set(payload, '{accepted}', '"rejette|rejète"')
 where id = 'mrh4uuybxo82yr';

-- « insoucieuse » hiếm đến mức gần như không dùng; dạng thường là « insouciante ».
update public.questions
   set payload = jsonb_set(payload, '{accepted}', '"insouciante|insoucieuse"')
 where id = 'mrh5c6y9bnitt3';
