-- SINH TỰ ĐỘNG bởi scripts/lo-trinh/sinh-sql.mjs từ scripts/lo-trinh/chu-de.mjs. Đừng sửa tay.

insert into public.lo_trinh_chu_de (id, ten_fr, ten_vi, mau, ord) values
  ('moi-truong', 'L''environnement et le climat', 'Môi trường và khí hậu', '#16A34A', 0),
  ('nang-luong', 'L''énergie et la consommation durable', 'Năng lượng và tiêu dùng bền vững', '#CA8A04', 1),
  ('binh-dang-gioi', 'L''égalité femmes-hommes', 'Bình đẳng giới', '#DB2777', 2),
  ('cong-nghe-so', 'Le numérique et l''intelligence artificielle', 'Công nghệ số và trí tuệ nhân tạo', '#2563EB', 3),
  ('mang-xa-hoi', 'Les réseaux sociaux et l''information', 'Mạng xã hội và tin giả', '#7C3AED', 4),
  ('viec-lam', 'Le travail et le télétravail', 'Việc làm và làm việc từ xa', '#0891B2', 5),
  ('nhap-cu', 'La migration et l''intégration', 'Nhập cư và hội nhập', '#EA580C', 6),
  ('suc-khoe', 'La santé, le sport et l''alimentation', 'Sức khoẻ, thể thao và ăn uống', '#DC2626', 7),
  ('giao-duc', 'L''éducation', 'Giáo dục', '#4F46E5', 8),
  ('gia-dinh', 'La famille et les générations', 'Gia đình và các thế hệ', '#B45309', 9),
  ('do-thi', 'La ville, les transports et le logement', 'Đô thị, giao thông và nhà ở', '#475569', 10),
  ('du-lich', 'Le tourisme et la culture', 'Du lịch và văn hoá', '#0D9488', 11),
  ('tieu-dung', 'La consommation et la publicité', 'Tiêu dùng và quảng cáo', '#9333EA', 12),
  ('cong-dong', 'Le bénévolat et la vie collective', 'Tình nguyện và cộng đồng', '#059669', 13),
  ('truyen-thong', 'Les médias et la presse', 'Truyền thông và báo chí', '#1D4ED8', 14),
  ('nghien', 'Le tabac et les addictions', 'Thuốc lá và các chứng nghiện', '#57534E', 15)
on conflict (id) do update set ten_fr = excluded.ten_fr, ten_vi = excluded.ten_vi, mau = excluded.mau, ord = excluded.ord;

insert into public.lo_trinh_man (id, chu_de_id, ord, ten, cap) values
  ('moi-truong-1', 'moi-truong', 0, 'La nature', 'A2'),
  ('moi-truong-2', 'moi-truong', 1, 'Le temps qu''il fait', 'A2'),
  ('moi-truong-3', 'moi-truong', 2, 'Les gestes écologiques', 'B1'),
  ('moi-truong-4', 'moi-truong', 3, 'La pollution', 'B1'),
  ('moi-truong-5', 'moi-truong', 4, 'Le climat change', 'B1'),
  ('moi-truong-6', 'moi-truong', 5, 'Agir pour le climat', 'B2'),
  ('moi-truong-7', 'moi-truong', 6, 'La biodiversité', 'B2'),
  ('nang-luong-1', 'nang-luong', 0, 'À la maison', 'A2'),
  ('nang-luong-2', 'nang-luong', 1, 'Se déplacer proprement', 'A2'),
  ('nang-luong-3', 'nang-luong', 2, 'Les énergies', 'B1'),
  ('nang-luong-4', 'nang-luong', 3, 'Consommer mieux', 'B1'),
  ('nang-luong-5', 'nang-luong', 4, 'Économiser', 'B1'),
  ('nang-luong-6', 'nang-luong', 5, 'La sobriété', 'B2'),
  ('nang-luong-7', 'nang-luong', 6, 'Le débat sur l''énergie', 'B2'),
  ('binh-dang-gioi-1', 'binh-dang-gioi', 0, 'Les personnes', 'A2'),
  ('binh-dang-gioi-2', 'binh-dang-gioi', 1, 'Les métiers', 'A2'),
  ('binh-dang-gioi-3', 'binh-dang-gioi', 2, 'À la maison', 'B1'),
  ('binh-dang-gioi-4', 'binh-dang-gioi', 3, 'Au travail', 'B1'),
  ('binh-dang-gioi-5', 'binh-dang-gioi', 4, 'Les droits', 'B1'),
  ('binh-dang-gioi-6', 'binh-dang-gioi', 5, 'Les discriminations', 'B2'),
  ('binh-dang-gioi-7', 'binh-dang-gioi', 6, 'Le féminisme', 'B2'),
  ('cong-nghe-so-1', 'cong-nghe-so', 0, 'L''ordinateur', 'A2'),
  ('cong-nghe-so-2', 'cong-nghe-so', 1, 'Internet', 'A2'),
  ('cong-nghe-so-3', 'cong-nghe-so', 2, 'Le téléphone', 'B1'),
  ('cong-nghe-so-4', 'cong-nghe-so', 3, 'Les données', 'B1'),
  ('cong-nghe-so-5', 'cong-nghe-so', 4, 'L''intelligence artificielle', 'B2'),
  ('cong-nghe-so-6', 'cong-nghe-so', 5, 'Les enjeux du numérique', 'B2'),
  ('mang-xa-hoi-1', 'mang-xa-hoi', 0, 'Sur les réseaux', 'A2'),
  ('mang-xa-hoi-2', 'mang-xa-hoi', 1, 'Les écrans', 'A2'),
  ('mang-xa-hoi-3', 'mang-xa-hoi', 2, 'La vie en ligne', 'B1'),
  ('mang-xa-hoi-4', 'mang-xa-hoi', 3, 'Les risques', 'B1'),
  ('mang-xa-hoi-5', 'mang-xa-hoi', 4, 'Les fausses informations', 'B2'),
  ('mang-xa-hoi-6', 'mang-xa-hoi', 5, 'L''esprit critique', 'B2'),
  ('viec-lam-1', 'viec-lam', 0, 'Au bureau', 'A2'),
  ('viec-lam-2', 'viec-lam', 1, 'Chercher un emploi', 'A2'),
  ('viec-lam-3', 'viec-lam', 2, 'Le télétravail', 'B1'),
  ('viec-lam-4', 'viec-lam', 3, 'Les conditions de travail', 'B1'),
  ('viec-lam-5', 'viec-lam', 4, 'Le monde du travail', 'B2'),
  ('viec-lam-6', 'viec-lam', 5, 'L''avenir du travail', 'B2'),
  ('nhap-cu-1', 'nhap-cu', 0, 'Voyager et s''installer', 'A2'),
  ('nhap-cu-2', 'nhap-cu', 1, 'Les langues', 'A2'),
  ('nhap-cu-3', 'nhap-cu', 2, 'Les démarches', 'B1'),
  ('nhap-cu-4', 'nhap-cu', 3, 'S''intégrer', 'B1'),
  ('nhap-cu-5', 'nhap-cu', 4, 'Les migrations', 'B2'),
  ('nhap-cu-6', 'nhap-cu', 5, 'Une société multiculturelle', 'B2'),
  ('suc-khoe-1', 'suc-khoe', 0, 'Le corps', 'A2'),
  ('suc-khoe-2', 'suc-khoe', 1, 'Chez le médecin', 'A2'),
  ('suc-khoe-3', 'suc-khoe', 2, 'Le sport', 'A2'),
  ('suc-khoe-4', 'suc-khoe', 3, 'Bien manger', 'B1'),
  ('suc-khoe-5', 'suc-khoe', 4, 'Une vie saine', 'B1'),
  ('suc-khoe-6', 'suc-khoe', 5, 'La santé publique', 'B2'),
  ('suc-khoe-7', 'suc-khoe', 6, 'Le bien-être', 'B2'),
  ('giao-duc-1', 'giao-duc', 0, 'À l''école', 'A2'),
  ('giao-duc-2', 'giao-duc', 1, 'Les matières', 'A2'),
  ('giao-duc-3', 'giao-duc', 2, 'Étudier', 'B1'),
  ('giao-duc-4', 'giao-duc', 3, 'L''université', 'B1'),
  ('giao-duc-5', 'giao-duc', 4, 'Le système éducatif', 'B2'),
  ('giao-duc-6', 'giao-duc', 5, 'Apprendre autrement', 'B2'),
  ('gia-dinh-1', 'gia-dinh', 0, 'La famille', 'A2'),
  ('gia-dinh-2', 'gia-dinh', 1, 'Les étapes de la vie', 'A2'),
  ('gia-dinh-3', 'gia-dinh', 2, 'La vie de famille', 'B1'),
  ('gia-dinh-4', 'gia-dinh', 3, 'Les générations', 'B1'),
  ('gia-dinh-5', 'gia-dinh', 4, 'Entre les générations', 'B2'),
  ('gia-dinh-6', 'gia-dinh', 5, 'La famille change', 'B2'),
  ('do-thi-1', 'do-thi', 0, 'En ville', 'A2'),
  ('do-thi-2', 'do-thi', 1, 'Se déplacer', 'A2'),
  ('do-thi-3', 'do-thi', 2, 'Le logement', 'A2'),
  ('do-thi-4', 'do-thi', 3, 'La vie urbaine', 'B1'),
  ('do-thi-5', 'do-thi', 4, 'L''urbanisme', 'B2'),
  ('do-thi-6', 'do-thi', 5, 'La crise du logement', 'B2'),
  ('du-lich-1', 'du-lich', 0, 'Les vacances', 'A2'),
  ('du-lich-2', 'du-lich', 1, 'Visiter une ville', 'A2'),
  ('du-lich-3', 'du-lich', 2, 'La culture', 'B1'),
  ('du-lich-4', 'du-lich', 3, 'Voyager autrement', 'B1'),
  ('du-lich-5', 'du-lich', 4, 'Le tourisme de masse', 'B2'),
  ('du-lich-6', 'du-lich', 5, 'Le tourisme responsable', 'B2'),
  ('tieu-dung-1', 'tieu-dung', 0, 'Faire les courses', 'A2'),
  ('tieu-dung-2', 'tieu-dung', 1, 'Les vêtements', 'A2'),
  ('tieu-dung-3', 'tieu-dung', 2, 'Acheter en ligne', 'B1'),
  ('tieu-dung-4', 'tieu-dung', 3, 'Les soldes', 'B1'),
  ('tieu-dung-5', 'tieu-dung', 4, 'La publicité', 'B2'),
  ('tieu-dung-6', 'tieu-dung', 5, 'La société de consommation', 'B2'),
  ('cong-dong-1', 'cong-dong', 0, 'Aider les autres', 'A2'),
  ('cong-dong-2', 'cong-dong', 1, 'Les associations', 'A2'),
  ('cong-dong-3', 'cong-dong', 2, 'Le bénévolat', 'B1'),
  ('cong-dong-4', 'cong-dong', 3, 'Vivre ensemble', 'B1'),
  ('cong-dong-5', 'cong-dong', 4, 'L''engagement citoyen', 'B2'),
  ('cong-dong-6', 'cong-dong', 5, 'La solidarité', 'B2'),
  ('truyen-thong-1', 'truyen-thong', 0, 'Les médias', 'A2'),
  ('truyen-thong-2', 'truyen-thong', 1, 'À la télévision', 'A2'),
  ('truyen-thong-3', 'truyen-thong', 2, 'Le journalisme', 'B1'),
  ('truyen-thong-4', 'truyen-thong', 3, 'S''informer', 'B1'),
  ('truyen-thong-5', 'truyen-thong', 4, 'La liberté de la presse', 'B2'),
  ('truyen-thong-6', 'truyen-thong', 5, 'Les médias aujourd''hui', 'B2'),
  ('nghien-1', 'nghien', 0, 'Le tabac', 'A2'),
  ('nghien-2', 'nghien', 1, 'Le souffle', 'A2'),
  ('nghien-3', 'nghien', 2, 'Arrêter de fumer', 'B1'),
  ('nghien-4', 'nghien', 3, 'Les addictions', 'B1'),
  ('nghien-5', 'nghien', 4, 'La prévention', 'B2'),
  ('nghien-6', 'nghien', 5, 'Le débat sur les addictions', 'B2')
on conflict (id) do update set chu_de_id = excluded.chu_de_id, ord = excluded.ord, ten = excluded.ten, cap = excluded.cap;

delete from public.lo_trinh_tu where man_id in ('moi-truong-1', 'moi-truong-2', 'moi-truong-3', 'moi-truong-4', 'moi-truong-5', 'moi-truong-6', 'moi-truong-7', 'nang-luong-1', 'nang-luong-2', 'nang-luong-3', 'nang-luong-4', 'nang-luong-5', 'nang-luong-6', 'nang-luong-7', 'binh-dang-gioi-1', 'binh-dang-gioi-2', 'binh-dang-gioi-3', 'binh-dang-gioi-4', 'binh-dang-gioi-5', 'binh-dang-gioi-6', 'binh-dang-gioi-7', 'cong-nghe-so-1', 'cong-nghe-so-2', 'cong-nghe-so-3', 'cong-nghe-so-4', 'cong-nghe-so-5', 'cong-nghe-so-6', 'mang-xa-hoi-1', 'mang-xa-hoi-2', 'mang-xa-hoi-3', 'mang-xa-hoi-4', 'mang-xa-hoi-5', 'mang-xa-hoi-6', 'viec-lam-1', 'viec-lam-2', 'viec-lam-3', 'viec-lam-4', 'viec-lam-5', 'viec-lam-6', 'nhap-cu-1', 'nhap-cu-2', 'nhap-cu-3', 'nhap-cu-4', 'nhap-cu-5', 'nhap-cu-6', 'suc-khoe-1', 'suc-khoe-2', 'suc-khoe-3', 'suc-khoe-4', 'suc-khoe-5', 'suc-khoe-6', 'suc-khoe-7', 'giao-duc-1', 'giao-duc-2', 'giao-duc-3', 'giao-duc-4', 'giao-duc-5', 'giao-duc-6', 'gia-dinh-1', 'gia-dinh-2', 'gia-dinh-3', 'gia-dinh-4', 'gia-dinh-5', 'gia-dinh-6', 'do-thi-1', 'do-thi-2', 'do-thi-3', 'do-thi-4', 'do-thi-5', 'do-thi-6', 'du-lich-1', 'du-lich-2', 'du-lich-3', 'du-lich-4', 'du-lich-5', 'du-lich-6', 'tieu-dung-1', 'tieu-dung-2', 'tieu-dung-3', 'tieu-dung-4', 'tieu-dung-5', 'tieu-dung-6', 'cong-dong-1', 'cong-dong-2', 'cong-dong-3', 'cong-dong-4', 'cong-dong-5', 'cong-dong-6', 'truyen-thong-1', 'truyen-thong-2', 'truyen-thong-3', 'truyen-thong-4', 'truyen-thong-5', 'truyen-thong-6', 'nghien-1', 'nghien-2', 'nghien-3', 'nghien-4', 'nghien-5', 'nghien-6');
insert into public.lo_trinh_tu (man_id, ord, fr, vi, loai) values
  ('moi-truong-1', 0, 'la forêt', 'rừng', 'n'),
  ('moi-truong-1', 1, 'la mer', 'biển', 'n'),
  ('moi-truong-1', 2, 'la montagne', 'núi', 'n'),
  ('moi-truong-1', 3, 'le fleuve', 'sông lớn', 'n'),
  ('moi-truong-1', 4, 'l''arbre', 'cây', 'n'),
  ('moi-truong-1', 5, 'la plage', 'bãi biển', 'n'),
  ('moi-truong-1', 6, 'le ciel', 'bầu trời', 'n'),
  ('moi-truong-1', 7, 'l''île', 'hòn đảo', 'n'),
  ('moi-truong-2', 0, 'la pluie', 'mưa', 'n'),
  ('moi-truong-2', 1, 'la neige', 'tuyết', 'n'),
  ('moi-truong-2', 2, 'le vent', 'gió', 'n'),
  ('moi-truong-2', 3, 'le nuage', 'đám mây', 'n'),
  ('moi-truong-2', 4, 'l''orage', 'cơn giông', 'n'),
  ('moi-truong-2', 5, 'la chaleur', 'cái nóng', 'n'),
  ('moi-truong-2', 6, 'il fait froid', 'trời lạnh', 'x'),
  ('moi-truong-2', 7, 'il fait beau', 'trời đẹp', 'x'),
  ('moi-truong-3', 0, 'trier les déchets', 'phân loại rác', 'x'),
  ('moi-truong-3', 1, 'recycler', 'tái chế', 'v'),
  ('moi-truong-3', 2, 'jeter', 'vứt bỏ', 'v'),
  ('moi-truong-3', 3, 'économiser l''eau', 'tiết kiệm nước', 'x'),
  ('moi-truong-3', 4, 'éteindre la lumière', 'tắt đèn', 'x'),
  ('moi-truong-3', 5, 'le compost', 'phân ủ hữu cơ', 'n'),
  ('moi-truong-3', 6, 'la poubelle', 'thùng rác', 'n'),
  ('moi-truong-3', 7, 'réutiliser', 'tái sử dụng', 'v'),
  ('moi-truong-4', 0, 'la pollution', 'sự ô nhiễm', 'n'),
  ('moi-truong-4', 1, 'les déchets', 'rác thải', 'n'),
  ('moi-truong-4', 2, 'polluer', 'gây ô nhiễm', 'v'),
  ('moi-truong-4', 3, 'la fumée', 'khói', 'n'),
  ('moi-truong-4', 4, 'l''air', 'không khí', 'n'),
  ('moi-truong-4', 5, 'sale', 'bẩn', 'a'),
  ('moi-truong-4', 6, 'propre', 'sạch', 'a'),
  ('moi-truong-4', 7, 'le plastique', 'nhựa', 'n'),
  ('moi-truong-5', 0, 'le réchauffement', 'sự nóng lên', 'n'),
  ('moi-truong-5', 1, 'la sécheresse', 'hạn hán', 'n'),
  ('moi-truong-5', 2, 'l''inondation', 'lũ lụt', 'n'),
  ('moi-truong-5', 3, 'la canicule', 'đợt nắng nóng', 'n'),
  ('moi-truong-5', 4, 'la tempête', 'cơn bão', 'n'),
  ('moi-truong-5', 5, 'fondre', 'tan chảy', 'v'),
  ('moi-truong-5', 6, 'augmenter', 'tăng lên', 'v'),
  ('moi-truong-5', 7, 'la température', 'nhiệt độ', 'n'),
  ('moi-truong-6', 0, 'les émissions', 'lượng khí thải', 'n'),
  ('moi-truong-6', 1, 'le gaz à effet de serre', 'khí nhà kính', 'n'),
  ('moi-truong-6', 2, 'réduire', 'cắt giảm', 'v'),
  ('moi-truong-6', 3, 'l''empreinte carbone', 'dấu chân carbon', 'n'),
  ('moi-truong-6', 4, 'la transition', 'sự chuyển đổi', 'n'),
  ('moi-truong-6', 5, 'durable', 'bền vững', 'a'),
  ('moi-truong-6', 6, 'menacé', 'bị đe doạ', 'a'),
  ('moi-truong-6', 7, 's''adapter', 'thích nghi', 'v'),
  ('moi-truong-7', 0, 'la biodiversité', 'đa dạng sinh học', 'n'),
  ('moi-truong-7', 1, 'l''espèce', 'loài', 'n'),
  ('moi-truong-7', 2, 'disparaître', 'biến mất', 'v'),
  ('moi-truong-7', 3, 'protéger', 'bảo vệ', 'v'),
  ('moi-truong-7', 4, 'l''écosystème', 'hệ sinh thái', 'n'),
  ('moi-truong-7', 5, 'la déforestation', 'nạn phá rừng', 'n'),
  ('moi-truong-7', 6, 'la faune', 'hệ động vật', 'n'),
  ('moi-truong-7', 7, 'la flore', 'hệ thực vật', 'n'),
  ('nang-luong-1', 0, 'l''électricité', 'điện', 'n'),
  ('nang-luong-1', 1, 'le chauffage', 'hệ thống sưởi', 'n'),
  ('nang-luong-1', 2, 'la lampe', 'cái đèn', 'n'),
  ('nang-luong-1', 3, 'la facture', 'hoá đơn', 'n'),
  ('nang-luong-1', 4, 'allumer', 'bật', 'v'),
  ('nang-luong-1', 5, 'éteindre', 'tắt', 'v'),
  ('nang-luong-1', 6, 'le frigo', 'tủ lạnh', 'n'),
  ('nang-luong-1', 7, 'la prise', 'ổ cắm điện', 'n'),
  ('nang-luong-2', 0, 'le vélo', 'xe đạp', 'n'),
  ('nang-luong-2', 1, 'à pied', 'đi bộ', 'x'),
  ('nang-luong-2', 2, 'le train', 'tàu hoả', 'n'),
  ('nang-luong-2', 3, 'le bus', 'xe buýt', 'n'),
  ('nang-luong-2', 4, 'la voiture électrique', 'ô tô điện', 'n'),
  ('nang-luong-2', 5, 'le covoiturage', 'đi chung xe', 'n'),
  ('nang-luong-2', 6, 'la trottinette', 'xe trượt', 'n'),
  ('nang-luong-2', 7, 'le métro', 'tàu điện ngầm', 'n'),
  ('nang-luong-3', 0, 'le soleil', 'mặt trời', 'n'),
  ('nang-luong-3', 1, 'l''énergie solaire', 'năng lượng mặt trời', 'n'),
  ('nang-luong-3', 2, 'l''éolienne', 'tua-bin gió', 'n'),
  ('nang-luong-3', 3, 'le charbon', 'than đá', 'n'),
  ('nang-luong-3', 4, 'le pétrole', 'dầu mỏ', 'n'),
  ('nang-luong-3', 5, 'le gaz', 'khí đốt', 'n'),
  ('nang-luong-3', 6, 'renouvelable', 'tái tạo được', 'a'),
  ('nang-luong-3', 7, 'nucléaire', 'hạt nhân', 'a'),
  ('nang-luong-4', 0, 'acheter local', 'mua hàng địa phương', 'x'),
  ('nang-luong-4', 1, 'de saison', 'theo mùa', 'x'),
  ('nang-luong-4', 2, 'le gaspillage', 'sự lãng phí', 'n'),
  ('nang-luong-4', 3, 'gaspiller', 'lãng phí', 'v'),
  ('nang-luong-4', 4, 'le vrac', 'hàng bán cân', 'n'),
  ('nang-luong-4', 5, 'l''emballage', 'bao bì', 'n'),
  ('nang-luong-4', 6, 'réparer', 'sửa chữa', 'v'),
  ('nang-luong-4', 7, 'd''occasion', 'hàng đã qua sử dụng', 'x'),
  ('nang-luong-5', 0, 'la consommation', 'mức tiêu thụ', 'n'),
  ('nang-luong-5', 1, 'consommer', 'tiêu thụ', 'v'),
  ('nang-luong-5', 2, 'économiser', 'tiết kiệm', 'v'),
  ('nang-luong-5', 3, 'isoler', 'cách nhiệt', 'v'),
  ('nang-luong-5', 4, 'la douche', 'vòi sen', 'n'),
  ('nang-luong-5', 5, 'le bain', 'bồn tắm', 'n'),
  ('nang-luong-5', 6, 'la veille', 'chế độ chờ', 'n'),
  ('nang-luong-5', 7, 'débrancher', 'rút phích cắm', 'v'),
  ('nang-luong-6', 0, 'la sobriété', 'sự tiết chế', 'n'),
  ('nang-luong-6', 1, 'la pénurie', 'sự khan hiếm', 'n'),
  ('nang-luong-6', 2, 'la ressource', 'tài nguyên', 'n'),
  ('nang-luong-6', 3, 'épuiser', 'làm cạn kiệt', 'v'),
  ('nang-luong-6', 4, 'produire', 'sản xuất', 'v'),
  ('nang-luong-6', 5, 'l''autonomie', 'sự tự chủ', 'n'),
  ('nang-luong-6', 6, 'coûteux', 'tốn kém', 'a'),
  ('nang-luong-6', 7, 'rentable', 'có lãi', 'a'),
  ('nang-luong-7', 0, 'la centrale', 'nhà máy điện', 'n'),
  ('nang-luong-7', 1, 'le réseau', 'mạng lưới điện', 'n'),
  ('nang-luong-7', 2, 'la facture énergétique', 'hoá đơn năng lượng', 'n'),
  ('nang-luong-7', 3, 'subventionner', 'trợ cấp', 'v'),
  ('nang-luong-7', 4, 'investir', 'đầu tư', 'v'),
  ('nang-luong-7', 5, 'la dépendance', 'sự phụ thuộc', 'n'),
  ('nang-luong-7', 6, 'propre', 'sạch', 'a'),
  ('nang-luong-7', 7, 'polluant', 'gây ô nhiễm', 'a'),
  ('binh-dang-gioi-1', 0, 'la femme', 'người phụ nữ', 'n'),
  ('binh-dang-gioi-1', 1, 'l''homme', 'người đàn ông', 'n'),
  ('binh-dang-gioi-1', 2, 'la fille', 'cô gái', 'n'),
  ('binh-dang-gioi-1', 3, 'le garçon', 'cậu con trai', 'n'),
  ('binh-dang-gioi-1', 4, 'la mère', 'người mẹ', 'n'),
  ('binh-dang-gioi-1', 5, 'le père', 'người bố', 'n'),
  ('binh-dang-gioi-1', 6, 'la sœur', 'chị/em gái', 'n'),
  ('binh-dang-gioi-1', 7, 'le frère', 'anh/em trai', 'n'),
  ('binh-dang-gioi-2', 0, 'l''infirmière', 'nữ y tá', 'n'),
  ('binh-dang-gioi-2', 1, 'le pompier', 'lính cứu hoả', 'n'),
  ('binh-dang-gioi-2', 2, 'l''ingénieure', 'nữ kỹ sư', 'n'),
  ('binh-dang-gioi-2', 3, 'le médecin', 'bác sĩ', 'n'),
  ('binh-dang-gioi-2', 4, 'la cheffe', 'nữ quản lý', 'n'),
  ('binh-dang-gioi-2', 5, 'l''avocat', 'luật sư', 'n'),
  ('binh-dang-gioi-2', 6, 'la directrice', 'nữ giám đốc', 'n'),
  ('binh-dang-gioi-2', 7, 'le pilote', 'phi công', 'n'),
  ('binh-dang-gioi-3', 0, 'les tâches ménagères', 'việc nhà', 'n'),
  ('binh-dang-gioi-3', 1, 'faire la vaisselle', 'rửa bát', 'x'),
  ('binh-dang-gioi-3', 2, 'faire le ménage', 'dọn dẹp nhà', 'x'),
  ('binh-dang-gioi-3', 3, 's''occuper des enfants', 'chăm con', 'x'),
  ('binh-dang-gioi-3', 4, 'partager', 'chia sẻ', 'v'),
  ('binh-dang-gioi-3', 5, 'aider', 'giúp đỡ', 'v'),
  ('binh-dang-gioi-3', 6, 'la répartition', 'sự phân chia', 'n'),
  ('binh-dang-gioi-3', 7, 'le congé parental', 'nghỉ phép nuôi con', 'n'),
  ('binh-dang-gioi-4', 0, 'le salaire', 'tiền lương', 'n'),
  ('binh-dang-gioi-4', 1, 'l''égalité', 'sự bình đẳng', 'n'),
  ('binh-dang-gioi-4', 2, 'l''inégalité', 'sự bất bình đẳng', 'n'),
  ('binh-dang-gioi-4', 3, 'le poste', 'vị trí công việc', 'n'),
  ('binh-dang-gioi-4', 4, 'embaucher', 'tuyển dụng', 'v'),
  ('binh-dang-gioi-4', 5, 'promouvoir', 'thăng chức', 'v'),
  ('binh-dang-gioi-4', 6, 'la promotion', 'sự thăng chức', 'n'),
  ('binh-dang-gioi-4', 7, 'l''écart', 'khoảng cách', 'n'),
  ('binh-dang-gioi-5', 0, 'le droit de vote', 'quyền bầu cử', 'n'),
  ('binh-dang-gioi-5', 1, 'la liberté', 'tự do', 'n'),
  ('binh-dang-gioi-5', 2, 'le respect', 'sự tôn trọng', 'n'),
  ('binh-dang-gioi-5', 3, 'respecter', 'tôn trọng', 'v'),
  ('binh-dang-gioi-5', 4, 'la loi', 'luật', 'n'),
  ('binh-dang-gioi-5', 5, 'voter', 'bỏ phiếu', 'v'),
  ('binh-dang-gioi-5', 6, 'juste', 'công bằng', 'a'),
  ('binh-dang-gioi-5', 7, 'injuste', 'bất công', 'a'),
  ('binh-dang-gioi-6', 0, 'la discrimination', 'sự phân biệt đối xử', 'n'),
  ('binh-dang-gioi-6', 1, 'le stéréotype', 'khuôn mẫu định kiến', 'n'),
  ('binh-dang-gioi-6', 2, 'le harcèlement', 'sự quấy rối', 'n'),
  ('binh-dang-gioi-6', 3, 'dénoncer', 'tố cáo', 'v'),
  ('binh-dang-gioi-6', 4, 'lutter contre', 'đấu tranh chống', 'x'),
  ('binh-dang-gioi-6', 5, 'le préjugé', 'thành kiến', 'n'),
  ('binh-dang-gioi-6', 6, 'sexiste', 'phân biệt giới tính', 'a'),
  ('binh-dang-gioi-6', 7, 'inégal', 'không đồng đều', 'a'),
  ('binh-dang-gioi-7', 0, 'le féminisme', 'chủ nghĩa nữ quyền', 'n'),
  ('binh-dang-gioi-7', 1, 'la parité', 'sự cân bằng giới', 'n'),
  ('binh-dang-gioi-7', 2, 'revendiquer', 'đòi hỏi', 'v'),
  ('binh-dang-gioi-7', 3, 'l''émancipation', 'sự giải phóng', 'n'),
  ('binh-dang-gioi-7', 4, 'le plafond de verre', 'trần kính', 'n'),
  ('binh-dang-gioi-7', 5, 'la mixité', 'sự pha trộn giới', 'n'),
  ('binh-dang-gioi-7', 6, 'militant', 'mang tính đấu tranh', 'a'),
  ('binh-dang-gioi-7', 7, 'paritaire', 'cân bằng nam nữ', 'a'),
  ('cong-nghe-so-1', 0, 'l''écran', 'màn hình', 'n'),
  ('cong-nghe-so-1', 1, 'le clavier', 'bàn phím', 'n'),
  ('cong-nghe-so-1', 2, 'la souris', 'chuột máy tính', 'n'),
  ('cong-nghe-so-1', 3, 'le fichier', 'tệp', 'n'),
  ('cong-nghe-so-1', 4, 'cliquer', 'nhấp chuột', 'v'),
  ('cong-nghe-so-1', 5, 'télécharger', 'tải xuống', 'v'),
  ('cong-nghe-so-1', 6, 'imprimer', 'in', 'v'),
  ('cong-nghe-so-1', 7, 'le mot de passe', 'mật khẩu', 'n'),
  ('cong-nghe-so-2', 0, 'le site', 'trang web', 'n'),
  ('cong-nghe-so-2', 1, 'le courriel', 'thư điện tử', 'n'),
  ('cong-nghe-so-2', 2, 'envoyer', 'gửi', 'v'),
  ('cong-nghe-so-2', 3, 'recevoir', 'nhận', 'v'),
  ('cong-nghe-so-2', 4, 'la connexion', 'kết nối', 'n'),
  ('cong-nghe-so-2', 5, 'en ligne', 'trực tuyến', 'x'),
  ('cong-nghe-so-2', 6, 'chercher', 'tìm kiếm', 'v'),
  ('cong-nghe-so-2', 7, 'le lien', 'đường liên kết', 'n'),
  ('cong-nghe-so-3', 0, 'l''application', 'ứng dụng', 'n'),
  ('cong-nghe-so-3', 1, 'la batterie', 'pin', 'n'),
  ('cong-nghe-so-3', 2, 'recharger', 'sạc lại', 'v'),
  ('cong-nghe-so-3', 3, 'le message', 'tin nhắn', 'n'),
  ('cong-nghe-so-3', 4, 'l''appel', 'cuộc gọi', 'n'),
  ('cong-nghe-so-3', 5, 'la notification', 'thông báo', 'n'),
  ('cong-nghe-so-3', 6, 'installer', 'cài đặt', 'v'),
  ('cong-nghe-so-3', 7, 'mettre à jour', 'cập nhật', 'x'),
  ('cong-nghe-so-4', 0, 'les données', 'dữ liệu', 'n'),
  ('cong-nghe-so-4', 1, 'la vie privée', 'đời tư', 'n'),
  ('cong-nghe-so-4', 2, 'protéger', 'bảo vệ', 'v'),
  ('cong-nghe-so-4', 3, 'le compte', 'tài khoản', 'n'),
  ('cong-nghe-so-4', 4, 'se connecter', 'đăng nhập', 'v'),
  ('cong-nghe-so-4', 5, 'supprimer', 'xoá', 'v'),
  ('cong-nghe-so-4', 6, 'sauvegarder', 'lưu', 'v'),
  ('cong-nghe-so-4', 7, 'le piratage', 'vụ tin tặc', 'n'),
  ('cong-nghe-so-5', 0, 'l''intelligence artificielle', 'trí tuệ nhân tạo', 'n'),
  ('cong-nghe-so-5', 1, 'l''algorithme', 'thuật toán', 'n'),
  ('cong-nghe-so-5', 2, 'automatiser', 'tự động hoá', 'v'),
  ('cong-nghe-so-5', 3, 'le robot', 'rô-bốt', 'n'),
  ('cong-nghe-so-5', 4, 'remplacer', 'thay thế', 'v'),
  ('cong-nghe-so-5', 5, 'générer', 'tạo ra', 'v'),
  ('cong-nghe-so-5', 6, 'fiable', 'đáng tin cậy', 'a'),
  ('cong-nghe-so-5', 7, 'l''outil', 'công cụ', 'n'),
  ('cong-nghe-so-6', 0, 'la fracture numérique', 'khoảng cách số', 'n'),
  ('cong-nghe-so-6', 1, 'la cybersécurité', 'an ninh mạng', 'n'),
  ('cong-nghe-so-6', 2, 'l''éthique', 'đạo đức', 'n'),
  ('cong-nghe-so-6', 3, 'surveiller', 'giám sát', 'v'),
  ('cong-nghe-so-6', 4, 'la dépendance', 'sự lệ thuộc', 'n'),
  ('cong-nghe-so-6', 5, 'réglementer', 'điều tiết', 'v'),
  ('cong-nghe-so-6', 6, 'anonyme', 'ẩn danh', 'a'),
  ('cong-nghe-so-6', 7, 'numérique', 'kỹ thuật số', 'a'),
  ('mang-xa-hoi-1', 0, 'la photo', 'bức ảnh', 'n'),
  ('mang-xa-hoi-1', 1, 'la vidéo', 'đoạn video', 'n'),
  ('mang-xa-hoi-1', 2, 'publier', 'đăng', 'v'),
  ('mang-xa-hoi-1', 3, 'partager', 'chia sẻ', 'v'),
  ('mang-xa-hoi-1', 4, 'aimer', 'thích', 'v'),
  ('mang-xa-hoi-1', 5, 'commenter', 'bình luận', 'v'),
  ('mang-xa-hoi-1', 6, 'l''ami', 'người bạn', 'n'),
  ('mang-xa-hoi-1', 7, 'le profil', 'trang cá nhân', 'n'),
  ('mang-xa-hoi-2', 0, 'l''écran', 'màn hình', 'n'),
  ('mang-xa-hoi-2', 1, 'le temps d''écran', 'thời gian dùng màn hình', 'n'),
  ('mang-xa-hoi-2', 2, 'regarder', 'xem', 'v'),
  ('mang-xa-hoi-2', 3, 'jouer', 'chơi', 'v'),
  ('mang-xa-hoi-2', 4, 'le jeu vidéo', 'trò chơi điện tử', 'n'),
  ('mang-xa-hoi-2', 5, 'la tablette', 'máy tính bảng', 'n'),
  ('mang-xa-hoi-2', 6, 'la série', 'phim bộ', 'n'),
  ('mang-xa-hoi-2', 7, 'la nuit', 'ban đêm', 'n'),
  ('mang-xa-hoi-3', 0, 'l''abonné', 'người theo dõi', 'n'),
  ('mang-xa-hoi-3', 1, 's''abonner', 'đăng ký theo dõi', 'v'),
  ('mang-xa-hoi-3', 2, 'la story', 'tin 24 giờ', 'n'),
  ('mang-xa-hoi-3', 3, 'l''influenceur', 'người có ảnh hưởng', 'n'),
  ('mang-xa-hoi-3', 4, 'populaire', 'nổi tiếng', 'a'),
  ('mang-xa-hoi-3', 5, 'viral', 'lan truyền mạnh', 'a'),
  ('mang-xa-hoi-3', 6, 'le pseudo', 'biệt danh', 'n'),
  ('mang-xa-hoi-3', 7, 'bloquer', 'chặn', 'v'),
  ('mang-xa-hoi-4', 0, 'le cyberharcèlement', 'bắt nạt trên mạng', 'n'),
  ('mang-xa-hoi-4', 1, 'l''arnaque', 'trò lừa đảo', 'n'),
  ('mang-xa-hoi-4', 2, 'la dépendance', 'sự nghiện', 'n'),
  ('mang-xa-hoi-4', 3, 'signaler', 'báo cáo', 'v'),
  ('mang-xa-hoi-4', 4, 'se méfier', 'cảnh giác', 'v'),
  ('mang-xa-hoi-4', 5, 'dangereux', 'nguy hiểm', 'a'),
  ('mang-xa-hoi-4', 6, 'isolé', 'bị cô lập', 'a'),
  ('mang-xa-hoi-4', 7, 'anxieux', 'lo âu', 'a'),
  ('mang-xa-hoi-5', 0, 'la fausse information', 'tin giả', 'n'),
  ('mang-xa-hoi-5', 1, 'la rumeur', 'tin đồn', 'n'),
  ('mang-xa-hoi-5', 2, 'la source', 'nguồn tin', 'n'),
  ('mang-xa-hoi-5', 3, 'vérifier', 'kiểm chứng', 'v'),
  ('mang-xa-hoi-5', 4, 'manipuler', 'thao túng', 'v'),
  ('mang-xa-hoi-5', 5, 'douteux', 'đáng ngờ', 'a'),
  ('mang-xa-hoi-5', 6, 'crédible', 'đáng tin', 'a'),
  ('mang-xa-hoi-5', 7, 'le complot', 'âm mưu', 'n'),
  ('mang-xa-hoi-6', 0, 'l''esprit critique', 'tư duy phản biện', 'n'),
  ('mang-xa-hoi-6', 1, 'le biais', 'thiên kiến', 'n'),
  ('mang-xa-hoi-6', 2, 'la bulle de filtres', 'bong bóng lọc', 'n'),
  ('mang-xa-hoi-6', 3, 'démentir', 'bác bỏ', 'v'),
  ('mang-xa-hoi-6', 4, 'relayer', 'chuyển tiếp', 'v'),
  ('mang-xa-hoi-6', 5, 'objectif', 'khách quan', 'a'),
  ('mang-xa-hoi-6', 6, 'trompeur', 'gây hiểu lầm', 'a'),
  ('mang-xa-hoi-6', 7, 'la désinformation', 'thông tin sai lệch', 'n'),
  ('viec-lam-1', 0, 'le travail', 'công việc', 'n'),
  ('viec-lam-1', 1, 'le bureau', 'văn phòng', 'n'),
  ('viec-lam-1', 2, 'le collègue', 'đồng nghiệp', 'n'),
  ('viec-lam-1', 3, 'le patron', 'ông chủ', 'n'),
  ('viec-lam-1', 4, 'travailler', 'làm việc', 'v'),
  ('viec-lam-1', 5, 'l''horaire', 'giờ làm việc', 'n'),
  ('viec-lam-1', 6, 'la réunion', 'cuộc họp', 'n'),
  ('viec-lam-1', 7, 'la pause', 'giờ nghỉ', 'n'),
  ('viec-lam-2', 0, 'le CV', 'sơ yếu lý lịch', 'n'),
  ('viec-lam-2', 1, 'l''offre d''emploi', 'tin tuyển dụng', 'n'),
  ('viec-lam-2', 2, 'l''entretien', 'buổi phỏng vấn', 'n'),
  ('viec-lam-2', 3, 'postuler', 'nộp đơn', 'v'),
  ('viec-lam-2', 4, 'le stage', 'kỳ thực tập', 'n'),
  ('viec-lam-2', 5, 'le contrat', 'hợp đồng', 'n'),
  ('viec-lam-2', 6, 'le chômage', 'tình trạng thất nghiệp', 'n'),
  ('viec-lam-2', 7, 'embaucher', 'tuyển', 'v'),
  ('viec-lam-3', 0, 'le télétravail', 'làm việc từ xa', 'n'),
  ('viec-lam-3', 1, 'à domicile', 'tại nhà', 'x'),
  ('viec-lam-3', 2, 'la visioconférence', 'họp trực tuyến', 'n'),
  ('viec-lam-3', 3, 'se déplacer', 'đi lại', 'v'),
  ('viec-lam-3', 4, 'flexible', 'linh hoạt', 'a'),
  ('viec-lam-3', 5, 'isolé', 'bị cô lập', 'a'),
  ('viec-lam-3', 6, 'l''équilibre', 'sự cân bằng', 'n'),
  ('viec-lam-3', 7, 'l''ordinateur portable', 'máy tính xách tay', 'n'),
  ('viec-lam-4', 0, 'le salaire', 'tiền lương', 'n'),
  ('viec-lam-4', 1, 'les congés', 'ngày nghỉ phép', 'n'),
  ('viec-lam-4', 2, 'la retraite', 'sự nghỉ hưu', 'n'),
  ('viec-lam-4', 3, 'démissionner', 'xin nghỉ việc', 'v'),
  ('viec-lam-4', 4, 'licencier', 'sa thải', 'v'),
  ('viec-lam-4', 5, 'à temps partiel', 'bán thời gian', 'x'),
  ('viec-lam-4', 6, 'à temps plein', 'toàn thời gian', 'x'),
  ('viec-lam-4', 7, 'le syndicat', 'công đoàn', 'n'),
  ('viec-lam-5', 0, 'la productivité', 'năng suất', 'n'),
  ('viec-lam-5', 1, 'le recrutement', 'sự tuyển dụng', 'n'),
  ('viec-lam-5', 2, 'la reconversion', 'sự chuyển nghề', 'n'),
  ('viec-lam-5', 3, 'l''épuisement', 'sự kiệt sức', 'n'),
  ('viec-lam-5', 4, 'négocier', 'đàm phán', 'v'),
  ('viec-lam-5', 5, 'se former', 'tự đào tạo', 'v'),
  ('viec-lam-5', 6, 'précaire', 'bấp bênh', 'a'),
  ('viec-lam-5', 7, 'qualifié', 'có tay nghề', 'a'),
  ('viec-lam-6', 0, 'la semaine de quatre jours', 'tuần làm bốn ngày', 'n'),
  ('viec-lam-6', 1, 'l''automatisation', 'sự tự động hoá', 'n'),
  ('viec-lam-6', 2, 'le travailleur indépendant', 'người làm tự do', 'n'),
  ('viec-lam-6', 3, 'la flexibilité', 'sự linh hoạt', 'n'),
  ('viec-lam-6', 4, 'délocaliser', 'chuyển ra nước ngoài', 'v'),
  ('viec-lam-6', 5, 'recruter', 'tuyển dụng', 'v'),
  ('viec-lam-6', 6, 'pénible', 'vất vả', 'a'),
  ('viec-lam-6', 7, 'épanouissant', 'giúp phát triển bản thân', 'a'),
  ('nhap-cu-1', 0, 'le pays', 'đất nước', 'n'),
  ('nhap-cu-1', 1, 'la frontière', 'biên giới', 'n'),
  ('nhap-cu-1', 2, 'le passeport', 'hộ chiếu', 'n'),
  ('nhap-cu-1', 3, 'le visa', 'thị thực', 'n'),
  ('nhap-cu-1', 4, 'étranger', 'nước ngoài', 'a'),
  ('nhap-cu-1', 5, 'habiter', 'sinh sống', 'v'),
  ('nhap-cu-1', 6, 'déménager', 'chuyển nhà', 'v'),
  ('nhap-cu-1', 7, 'la nationalité', 'quốc tịch', 'n'),
  ('nhap-cu-2', 0, 'la langue', 'ngôn ngữ', 'n'),
  ('nhap-cu-2', 1, 'apprendre', 'học', 'v'),
  ('nhap-cu-2', 2, 'parler', 'nói', 'v'),
  ('nhap-cu-2', 3, 'comprendre', 'hiểu', 'v'),
  ('nhap-cu-2', 4, 'traduire', 'dịch', 'v'),
  ('nhap-cu-2', 5, 'l''accent', 'giọng nói', 'n'),
  ('nhap-cu-2', 6, 'le dictionnaire', 'từ điển', 'n'),
  ('nhap-cu-2', 7, 'bilingue', 'song ngữ', 'a'),
  ('nhap-cu-3', 0, 'le titre de séjour', 'thẻ cư trú', 'n'),
  ('nhap-cu-3', 1, 'la préfecture', 'sở hành chính tỉnh', 'n'),
  ('nhap-cu-3', 2, 'le formulaire', 'mẫu đơn', 'n'),
  ('nhap-cu-3', 3, 'remplir', 'điền', 'v'),
  ('nhap-cu-3', 4, 'le rendez-vous', 'cuộc hẹn', 'n'),
  ('nhap-cu-3', 5, 'le justificatif', 'giấy tờ chứng minh', 'n'),
  ('nhap-cu-3', 6, 'renouveler', 'gia hạn', 'v'),
  ('nhap-cu-3', 7, 'administratif', 'hành chính', 'a'),
  ('nhap-cu-4', 0, 's''intégrer', 'hội nhập', 'v'),
  ('nhap-cu-4', 1, 'la culture', 'văn hoá', 'n'),
  ('nhap-cu-4', 2, 'la tradition', 'truyền thống', 'n'),
  ('nhap-cu-4', 3, 'le voisin', 'hàng xóm', 'n'),
  ('nhap-cu-4', 4, 'accueillir', 'đón tiếp', 'v'),
  ('nhap-cu-4', 5, 'l''association', 'hội đoàn', 'n'),
  ('nhap-cu-4', 6, 's''habituer', 'quen dần', 'v'),
  ('nhap-cu-4', 7, 'le mal du pays', 'nỗi nhớ quê', 'n'),
  ('nhap-cu-5', 0, 'le migrant', 'người di cư', 'n'),
  ('nhap-cu-5', 1, 'le réfugié', 'người tị nạn', 'n'),
  ('nhap-cu-5', 2, 'l''exil', 'sự lưu vong', 'n'),
  ('nhap-cu-5', 3, 'fuir', 'chạy trốn', 'v'),
  ('nhap-cu-5', 4, 'la persécution', 'sự đàn áp', 'n'),
  ('nhap-cu-5', 5, 'le droit d''asile', 'quyền tị nạn', 'n'),
  ('nhap-cu-5', 6, 'clandestin', 'bất hợp pháp', 'a'),
  ('nhap-cu-5', 7, 'humanitaire', 'nhân đạo', 'a'),
  ('nhap-cu-6', 0, 'la diversité', 'sự đa dạng', 'n'),
  ('nhap-cu-6', 1, 'le racisme', 'nạn phân biệt chủng tộc', 'n'),
  ('nhap-cu-6', 2, 'la xénophobie', 'sự bài ngoại', 'n'),
  ('nhap-cu-6', 3, 'la tolérance', 'lòng khoan dung', 'n'),
  ('nhap-cu-6', 4, 'enrichir', 'làm phong phú', 'v'),
  ('nhap-cu-6', 5, 'exclure', 'loại trừ', 'v'),
  ('nhap-cu-6', 6, 'multiculturel', 'đa văn hoá', 'a'),
  ('nhap-cu-6', 7, 'la naturalisation', 'sự nhập quốc tịch', 'n'),
  ('suc-khoe-1', 0, 'la tête', 'cái đầu', 'n'),
  ('suc-khoe-1', 1, 'le bras', 'cánh tay', 'n'),
  ('suc-khoe-1', 2, 'la jambe', 'cẳng chân', 'n'),
  ('suc-khoe-1', 3, 'le dos', 'cái lưng', 'n'),
  ('suc-khoe-1', 4, 'le ventre', 'cái bụng', 'n'),
  ('suc-khoe-1', 5, 'la main', 'bàn tay', 'n'),
  ('suc-khoe-1', 6, 'le pied', 'bàn chân', 'n'),
  ('suc-khoe-1', 7, 'le cœur', 'trái tim', 'n'),
  ('suc-khoe-2', 0, 'malade', 'bị ốm', 'a'),
  ('suc-khoe-2', 1, 'la fièvre', 'cơn sốt', 'n'),
  ('suc-khoe-2', 2, 'tousser', 'ho', 'v'),
  ('suc-khoe-2', 3, 'le médicament', 'thuốc', 'n'),
  ('suc-khoe-2', 4, 'l''ordonnance', 'đơn thuốc', 'n'),
  ('suc-khoe-2', 5, 'la pharmacie', 'hiệu thuốc', 'n'),
  ('suc-khoe-2', 6, 'avoir mal', 'bị đau', 'x'),
  ('suc-khoe-2', 7, 'guérir', 'khỏi bệnh', 'v'),
  ('suc-khoe-3', 0, 'courir', 'chạy', 'v'),
  ('suc-khoe-3', 1, 'nager', 'bơi', 'v'),
  ('suc-khoe-3', 2, 'le match', 'trận đấu', 'n'),
  ('suc-khoe-3', 3, 'l''équipe', 'đội', 'n'),
  ('suc-khoe-3', 4, 's''entraîner', 'tập luyện', 'v'),
  ('suc-khoe-3', 5, 'la salle de sport', 'phòng tập', 'n'),
  ('suc-khoe-3', 6, 'le ballon', 'quả bóng', 'n'),
  ('suc-khoe-3', 7, 'gagner', 'thắng', 'v'),
  ('suc-khoe-4', 0, 'les légumes', 'rau củ', 'n'),
  ('suc-khoe-4', 1, 'les fruits', 'trái cây', 'n'),
  ('suc-khoe-4', 2, 'le sucre', 'đường', 'n'),
  ('suc-khoe-4', 3, 'le sel', 'muối', 'n'),
  ('suc-khoe-4', 4, 'gras', 'nhiều mỡ', 'a'),
  ('suc-khoe-4', 5, 'équilibré', 'cân bằng', 'a'),
  ('suc-khoe-4', 6, 'le repas', 'bữa ăn', 'n'),
  ('suc-khoe-4', 7, 'grignoter', 'ăn vặt', 'v'),
  ('suc-khoe-5', 0, 'le sommeil', 'giấc ngủ', 'n'),
  ('suc-khoe-5', 1, 'le stress', 'căng thẳng', 'n'),
  ('suc-khoe-5', 2, 'se reposer', 'nghỉ ngơi', 'v'),
  ('suc-khoe-5', 3, 'bouger', 'vận động', 'v'),
  ('suc-khoe-5', 4, 'sédentaire', 'ít vận động', 'a'),
  ('suc-khoe-5', 5, 'la santé', 'sức khoẻ', 'n'),
  ('suc-khoe-5', 6, 'en forme', 'khoẻ khoắn', 'x'),
  ('suc-khoe-5', 7, 'l''habitude', 'thói quen', 'n'),
  ('suc-khoe-6', 0, 'la prévention', 'sự phòng ngừa', 'n'),
  ('suc-khoe-6', 1, 'le vaccin', 'vắc-xin', 'n'),
  ('suc-khoe-6', 2, 'l''obésité', 'bệnh béo phì', 'n'),
  ('suc-khoe-6', 3, 'la maladie chronique', 'bệnh mãn tính', 'n'),
  ('suc-khoe-6', 4, 'rembourser', 'hoàn tiền', 'v'),
  ('suc-khoe-6', 5, 'la sécurité sociale', 'bảo hiểm xã hội', 'n'),
  ('suc-khoe-6', 6, 'nocif', 'có hại', 'a'),
  ('suc-khoe-6', 7, 'bénéfique', 'có lợi', 'a'),
  ('suc-khoe-7', 0, 'le bien-être', 'sự an lạc', 'n'),
  ('suc-khoe-7', 1, 'la méditation', 'thiền', 'n'),
  ('suc-khoe-7', 2, 'l''épuisement professionnel', 'kiệt sức vì công việc', 'n'),
  ('suc-khoe-7', 3, 'se détendre', 'thư giãn', 'v'),
  ('suc-khoe-7', 4, 'prévenir', 'phòng ngừa', 'v'),
  ('suc-khoe-7', 5, 'mental', 'tinh thần', 'a'),
  ('suc-khoe-7', 6, 'physique', 'thể chất', 'a'),
  ('suc-khoe-7', 7, 'l''équilibre de vie', 'cân bằng cuộc sống', 'n'),
  ('giao-duc-1', 0, 'le professeur', 'giáo viên', 'n'),
  ('giao-duc-1', 1, 'l''élève', 'học sinh', 'n'),
  ('giao-duc-1', 2, 'la classe', 'lớp học', 'n'),
  ('giao-duc-1', 3, 'le cahier', 'quyển vở', 'n'),
  ('giao-duc-1', 4, 'le stylo', 'cây bút', 'n'),
  ('giao-duc-1', 5, 'le cours', 'tiết học', 'n'),
  ('giao-duc-1', 6, 'la récréation', 'giờ ra chơi', 'n'),
  ('giao-duc-1', 7, 'le cartable', 'cặp sách', 'n'),
  ('giao-duc-2', 0, 'les mathématiques', 'môn toán', 'n'),
  ('giao-duc-2', 1, 'l''histoire', 'môn lịch sử', 'n'),
  ('giao-duc-2', 2, 'la géographie', 'môn địa lý', 'n'),
  ('giao-duc-2', 3, 'l''anglais', 'tiếng Anh', 'n'),
  ('giao-duc-2', 4, 'la physique', 'môn vật lý', 'n'),
  ('giao-duc-2', 5, 'le dessin', 'môn vẽ', 'n'),
  ('giao-duc-2', 6, 'la musique', 'môn âm nhạc', 'n'),
  ('giao-duc-2', 7, 'la biologie', 'môn sinh học', 'n'),
  ('giao-duc-3', 0, 'réviser', 'ôn bài', 'v'),
  ('giao-duc-3', 1, 'l''examen', 'kỳ thi', 'n'),
  ('giao-duc-3', 2, 'la note', 'điểm số', 'n'),
  ('giao-duc-3', 3, 'réussir', 'thi đỗ', 'v'),
  ('giao-duc-3', 4, 'échouer', 'thi trượt', 'v'),
  ('giao-duc-3', 5, 'le diplôme', 'bằng cấp', 'n'),
  ('giao-duc-3', 6, 'les devoirs', 'bài tập về nhà', 'n'),
  ('giao-duc-3', 7, 'redoubler', 'học lại lớp', 'v'),
  ('giao-duc-4', 0, 'l''université', 'trường đại học', 'n'),
  ('giao-duc-4', 1, 'l''étudiant', 'sinh viên', 'n'),
  ('giao-duc-4', 2, 'la bourse', 'học bổng', 'n'),
  ('giao-duc-4', 3, 'la licence', 'bằng cử nhân', 'n'),
  ('giao-duc-4', 4, 'le master', 'bằng thạc sĩ', 'n'),
  ('giao-duc-4', 5, 's''inscrire', 'ghi danh', 'v'),
  ('giao-duc-4', 6, 'l''amphithéâtre', 'giảng đường', 'n'),
  ('giao-duc-4', 7, 'les frais d''inscription', 'học phí', 'n'),
  ('giao-duc-5', 0, 'l''enseignement', 'sự giảng dạy', 'n'),
  ('giao-duc-5', 1, 'la scolarité', 'việc học hành', 'n'),
  ('giao-duc-5', 2, 'obligatoire', 'bắt buộc', 'a'),
  ('giao-duc-5', 3, 'gratuit', 'miễn phí', 'a'),
  ('giao-duc-5', 4, 'l''échec scolaire', 'thất bại học đường', 'n'),
  ('giao-duc-5', 5, 'le décrochage', 'sự bỏ học', 'n'),
  ('giao-duc-5', 6, 'orienter', 'định hướng', 'v'),
  ('giao-duc-5', 7, 'évaluer', 'đánh giá', 'v'),
  ('giao-duc-6', 0, 'l''apprentissage', 'sự học tập', 'n'),
  ('giao-duc-6', 1, 'la formation continue', 'đào tạo liên tục', 'n'),
  ('giao-duc-6', 2, 'l''autonomie', 'tính tự chủ', 'n'),
  ('giao-duc-6', 3, 'la pédagogie', 'phương pháp sư phạm', 'n'),
  ('giao-duc-6', 4, 'motiver', 'tạo động lực', 'v'),
  ('giao-duc-6', 5, 'mémoriser', 'ghi nhớ', 'v'),
  ('giao-duc-6', 6, 'à distance', 'từ xa', 'x'),
  ('giao-duc-6', 7, 'ludique', 'mang tính trò chơi', 'a'),
  ('gia-dinh-1', 0, 'les parents', 'bố mẹ', 'n'),
  ('gia-dinh-1', 1, 'l''enfant', 'đứa trẻ', 'n'),
  ('gia-dinh-1', 2, 'les grands-parents', 'ông bà', 'n'),
  ('gia-dinh-1', 3, 'l''oncle', 'chú, bác', 'n'),
  ('gia-dinh-1', 4, 'la tante', 'cô, dì', 'n'),
  ('gia-dinh-1', 5, 'le cousin', 'anh em họ', 'n'),
  ('gia-dinh-1', 6, 'le mari', 'người chồng', 'n'),
  ('gia-dinh-1', 7, 'l''épouse', 'người vợ', 'n'),
  ('gia-dinh-2', 0, 'naître', 'được sinh ra', 'v'),
  ('gia-dinh-2', 1, 'grandir', 'lớn lên', 'v'),
  ('gia-dinh-2', 2, 'se marier', 'kết hôn', 'v'),
  ('gia-dinh-2', 3, 'vieillir', 'già đi', 'v'),
  ('gia-dinh-2', 4, 'le bébé', 'em bé', 'n'),
  ('gia-dinh-2', 5, 'l''adolescent', 'thiếu niên', 'n'),
  ('gia-dinh-2', 6, 'l''adulte', 'người lớn', 'n'),
  ('gia-dinh-2', 7, 'la personne âgée', 'người cao tuổi', 'n'),
  ('gia-dinh-3', 0, 'le repas de famille', 'bữa cơm gia đình', 'n'),
  ('gia-dinh-3', 1, 's''entendre', 'hoà thuận', 'v'),
  ('gia-dinh-3', 2, 'se disputer', 'cãi nhau', 'v'),
  ('gia-dinh-3', 3, 'l''éducation', 'sự dạy dỗ con', 'n'),
  ('gia-dinh-3', 4, 'élever', 'nuôi dạy', 'v'),
  ('gia-dinh-3', 5, 'le divorce', 'việc ly hôn', 'n'),
  ('gia-dinh-3', 6, 'la famille recomposée', 'gia đình tái hôn', 'n'),
  ('gia-dinh-3', 7, 'monoparental', 'đơn thân', 'a'),
  ('gia-dinh-4', 0, 'la génération', 'thế hệ', 'n'),
  ('gia-dinh-4', 1, 'transmettre', 'truyền lại', 'v'),
  ('gia-dinh-4', 2, 'le souvenir', 'kỷ niệm', 'n'),
  ('gia-dinh-4', 3, 'la retraite', 'sự nghỉ hưu', 'n'),
  ('gia-dinh-4', 4, 'la maison de retraite', 'viện dưỡng lão', 'n'),
  ('gia-dinh-4', 5, 'rendre visite', 'đến thăm', 'x'),
  ('gia-dinh-4', 6, 'le petit-enfant', 'đứa cháu', 'n'),
  ('gia-dinh-4', 7, 'âgé', 'lớn tuổi', 'a'),
  ('gia-dinh-5', 0, 'le conflit de générations', 'xung đột thế hệ', 'n'),
  ('gia-dinh-5', 1, 'la solidarité', 'tình đoàn kết', 'n'),
  ('gia-dinh-5', 2, 'le fossé', 'hố ngăn cách', 'n'),
  ('gia-dinh-5', 3, 'cohabiter', 'sống chung', 'v'),
  ('gia-dinh-5', 4, 'dépendant', 'phụ thuộc', 'a'),
  ('gia-dinh-5', 5, 'autonome', 'tự lập', 'a'),
  ('gia-dinh-5', 6, 'le vieillissement', 'sự già hoá', 'n'),
  ('gia-dinh-5', 7, 'prendre soin de', 'chăm sóc', 'x'),
  ('gia-dinh-6', 0, 'la natalité', 'tỷ lệ sinh', 'n'),
  ('gia-dinh-6', 1, 'le mariage', 'hôn nhân', 'n'),
  ('gia-dinh-6', 2, 'l''union libre', 'sống chung không cưới', 'n'),
  ('gia-dinh-6', 3, 'la parentalité', 'việc làm cha mẹ', 'n'),
  ('gia-dinh-6', 4, 'l''adoption', 'việc nhận con nuôi', 'n'),
  ('gia-dinh-6', 5, 'adopter', 'nhận con nuôi', 'v'),
  ('gia-dinh-6', 6, 'traditionnel', 'truyền thống', 'a'),
  ('gia-dinh-6', 7, 'nombreux', 'đông đúc', 'a'),
  ('do-thi-1', 0, 'la rue', 'đường phố', 'n'),
  ('do-thi-1', 1, 'la place', 'quảng trường', 'n'),
  ('do-thi-1', 2, 'le pont', 'cây cầu', 'n'),
  ('do-thi-1', 3, 'le parc', 'công viên', 'n'),
  ('do-thi-1', 4, 'la mairie', 'toà thị chính', 'n'),
  ('do-thi-1', 5, 'le quartier', 'khu phố', 'n'),
  ('do-thi-1', 6, 'le carrefour', 'ngã tư', 'n'),
  ('do-thi-1', 7, 'le trottoir', 'vỉa hè', 'n'),
  ('do-thi-2', 0, 'le ticket', 'tấm vé', 'n'),
  ('do-thi-2', 1, 'l''arrêt', 'điểm dừng xe', 'n'),
  ('do-thi-2', 2, 'la gare', 'ga tàu', 'n'),
  ('do-thi-2', 3, 'prendre le bus', 'đi xe buýt', 'x'),
  ('do-thi-2', 4, 'descendre', 'xuống xe', 'v'),
  ('do-thi-2', 5, 'monter', 'lên xe', 'v'),
  ('do-thi-2', 6, 'le retard', 'sự chậm trễ', 'n'),
  ('do-thi-2', 7, 'l''horaire', 'giờ chạy', 'n'),
  ('do-thi-3', 0, 'l''appartement', 'căn hộ', 'n'),
  ('do-thi-3', 1, 'la maison', 'ngôi nhà', 'n'),
  ('do-thi-3', 2, 'le loyer', 'tiền thuê nhà', 'n'),
  ('do-thi-3', 3, 'louer', 'thuê', 'v'),
  ('do-thi-3', 4, 'la chambre', 'phòng ngủ', 'n'),
  ('do-thi-3', 5, 'la cuisine', 'nhà bếp', 'n'),
  ('do-thi-3', 6, 'le propriétaire', 'chủ nhà', 'n'),
  ('do-thi-3', 7, 'le locataire', 'người thuê nhà', 'n'),
  ('do-thi-4', 0, 'les embouteillages', 'tắc đường', 'n'),
  ('do-thi-4', 1, 'le bruit', 'tiếng ồn', 'n'),
  ('do-thi-4', 2, 'bruyant', 'ồn ào', 'a'),
  ('do-thi-4', 3, 'calme', 'yên tĩnh', 'a'),
  ('do-thi-4', 4, 'animé', 'nhộn nhịp', 'a'),
  ('do-thi-4', 5, 'la banlieue', 'ngoại ô', 'n'),
  ('do-thi-4', 6, 'le centre-ville', 'trung tâm thành phố', 'n'),
  ('do-thi-4', 7, 'se garer', 'đỗ xe', 'v'),
  ('do-thi-5', 0, 'l''urbanisme', 'quy hoạch đô thị', 'n'),
  ('do-thi-5', 1, 'la piste cyclable', 'làn xe đạp', 'n'),
  ('do-thi-5', 2, 'la zone piétonne', 'phố đi bộ', 'n'),
  ('do-thi-5', 3, 'aménager', 'quy hoạch', 'v'),
  ('do-thi-5', 4, 'rénover', 'cải tạo', 'v'),
  ('do-thi-5', 5, 'l''espace vert', 'không gian xanh', 'n'),
  ('do-thi-5', 6, 'dense', 'dày đặc', 'a'),
  ('do-thi-5', 7, 'accessible', 'dễ tiếp cận', 'a'),
  ('do-thi-6', 0, 'la crise du logement', 'khủng hoảng nhà ở', 'n'),
  ('do-thi-6', 1, 'le logement social', 'nhà ở xã hội', 'n'),
  ('do-thi-6', 2, 'le sans-abri', 'người vô gia cư', 'n'),
  ('do-thi-6', 3, 'expulser', 'trục xuất', 'v'),
  ('do-thi-6', 4, 'spéculer', 'đầu cơ', 'v'),
  ('do-thi-6', 5, 'la colocation', 'ở ghép', 'n'),
  ('do-thi-6', 6, 'insalubre', 'mất vệ sinh', 'a'),
  ('do-thi-6', 7, 'abordable', 'giá phải chăng', 'a'),
  ('du-lich-1', 0, 'la valise', 'vali', 'n'),
  ('du-lich-1', 1, 'l''hôtel', 'khách sạn', 'n'),
  ('du-lich-1', 2, 'la réservation', 'việc đặt chỗ', 'n'),
  ('du-lich-1', 3, 'le billet', 'tấm vé', 'n'),
  ('du-lich-1', 4, 'partir', 'khởi hành', 'v'),
  ('du-lich-1', 5, 'visiter', 'tham quan', 'v'),
  ('du-lich-1', 6, 'le touriste', 'khách du lịch', 'n'),
  ('du-lich-1', 7, 'le souvenir', 'quà lưu niệm', 'n'),
  ('du-lich-2', 0, 'le musée', 'bảo tàng', 'n'),
  ('du-lich-2', 1, 'le château', 'lâu đài', 'n'),
  ('du-lich-2', 2, 'l''église', 'nhà thờ', 'n'),
  ('du-lich-2', 3, 'le monument', 'công trình kỷ niệm', 'n'),
  ('du-lich-2', 4, 'le guide', 'hướng dẫn viên', 'n'),
  ('du-lich-2', 5, 'la visite guidée', 'chuyến tham quan có hướng dẫn', 'n'),
  ('du-lich-2', 6, 'le plan', 'bản đồ', 'n'),
  ('du-lich-2', 7, 'l''entrée', 'vé vào cửa', 'n'),
  ('du-lich-3', 0, 'le spectacle', 'buổi biểu diễn', 'n'),
  ('du-lich-3', 1, 'le concert', 'buổi hoà nhạc', 'n'),
  ('du-lich-3', 2, 'l''exposition', 'cuộc triển lãm', 'n'),
  ('du-lich-3', 3, 'le théâtre', 'nhà hát', 'n'),
  ('du-lich-3', 4, 'le festival', 'lễ hội', 'n'),
  ('du-lich-3', 5, 'l''artiste', 'nghệ sĩ', 'n'),
  ('du-lich-3', 6, 'applaudir', 'vỗ tay', 'v'),
  ('du-lich-3', 7, 'le patrimoine', 'di sản', 'n'),
  ('du-lich-4', 0, 'le sac à dos', 'ba lô', 'n'),
  ('du-lich-4', 1, 'l''auberge de jeunesse', 'nhà nghỉ thanh niên', 'n'),
  ('du-lich-4', 2, 'chez l''habitant', 'ở nhà dân', 'x'),
  ('du-lich-4', 3, 'le séjour', 'chuyến lưu trú', 'n'),
  ('du-lich-4', 4, 'découvrir', 'khám phá', 'v'),
  ('du-lich-4', 5, 'l''itinéraire', 'lộ trình', 'n'),
  ('du-lich-4', 6, 'dépaysant', 'lạ lẫm thú vị', 'a'),
  ('du-lich-4', 7, 'authentique', 'chân thực', 'a'),
  ('du-lich-5', 0, 'le surtourisme', 'du lịch quá tải', 'n'),
  ('du-lich-5', 1, 'la fréquentation', 'lượng khách', 'n'),
  ('du-lich-5', 2, 'saturé', 'quá tải', 'a'),
  ('du-lich-5', 3, 'dégrader', 'làm xuống cấp', 'v'),
  ('du-lich-5', 4, 'le quota', 'hạn ngạch', 'n'),
  ('du-lich-5', 5, 'la haute saison', 'mùa cao điểm', 'n'),
  ('du-lich-5', 6, 'la basse saison', 'mùa thấp điểm', 'n'),
  ('du-lich-5', 7, 'réglementer', 'điều tiết', 'v'),
  ('du-lich-6', 0, 'le tourisme durable', 'du lịch bền vững', 'n'),
  ('du-lich-6', 1, 'l''écotourisme', 'du lịch sinh thái', 'n'),
  ('du-lich-6', 2, 'préserver', 'gìn giữ', 'v'),
  ('du-lich-6', 3, 'respectueux', 'biết tôn trọng', 'a'),
  ('du-lich-6', 4, 'la retombée économique', 'lợi ích kinh tế', 'n'),
  ('du-lich-6', 5, 'la communauté locale', 'cộng đồng địa phương', 'n'),
  ('du-lich-6', 6, 'l''empreinte', 'dấu vết', 'n'),
  ('du-lich-6', 7, 'voyager', 'du lịch', 'v'),
  ('tieu-dung-1', 0, 'le magasin', 'cửa hàng', 'n'),
  ('tieu-dung-1', 1, 'le supermarché', 'siêu thị', 'n'),
  ('tieu-dung-1', 2, 'le prix', 'giá tiền', 'n'),
  ('tieu-dung-1', 3, 'payer', 'trả tiền', 'v'),
  ('tieu-dung-1', 4, 'la caisse', 'quầy thu ngân', 'n'),
  ('tieu-dung-1', 5, 'cher', 'đắt', 'a'),
  ('tieu-dung-1', 6, 'bon marché', 'rẻ', 'x'),
  ('tieu-dung-1', 7, 'le panier', 'giỏ hàng', 'n'),
  ('tieu-dung-2', 0, 'la chemise', 'áo sơ mi', 'n'),
  ('tieu-dung-2', 1, 'le pantalon', 'quần dài', 'n'),
  ('tieu-dung-2', 2, 'la robe', 'váy liền', 'n'),
  ('tieu-dung-2', 3, 'les chaussures', 'đôi giày', 'n'),
  ('tieu-dung-2', 4, 'la taille', 'cỡ', 'n'),
  ('tieu-dung-2', 5, 'essayer', 'mặc thử', 'v'),
  ('tieu-dung-2', 6, 'la couleur', 'màu sắc', 'n'),
  ('tieu-dung-2', 7, 'le manteau', 'áo khoác', 'n'),
  ('tieu-dung-3', 0, 'commander', 'đặt hàng', 'v'),
  ('tieu-dung-3', 1, 'livrer', 'giao hàng', 'v'),
  ('tieu-dung-3', 2, 'la livraison', 'việc giao hàng', 'n'),
  ('tieu-dung-3', 3, 'le colis', 'bưu kiện', 'n'),
  ('tieu-dung-3', 4, 'rembourser', 'hoàn tiền', 'v'),
  ('tieu-dung-3', 5, 'le retour', 'việc trả hàng', 'n'),
  ('tieu-dung-3', 6, 'l''avis', 'lời đánh giá', 'n'),
  ('tieu-dung-3', 7, 'la carte bancaire', 'thẻ ngân hàng', 'n'),
  ('tieu-dung-4', 0, 'les soldes', 'đợt giảm giá', 'n'),
  ('tieu-dung-4', 1, 'la promotion', 'khuyến mãi', 'n'),
  ('tieu-dung-4', 2, 'la réduction', 'sự giảm giá', 'n'),
  ('tieu-dung-4', 3, 'gratuit', 'miễn phí', 'a'),
  ('tieu-dung-4', 4, 'une bonne affaire', 'món hời', 'x'),
  ('tieu-dung-4', 5, 'dépenser', 'tiêu tiền', 'v'),
  ('tieu-dung-4', 6, 'le reçu', 'biên lai', 'n'),
  ('tieu-dung-4', 7, 'le budget', 'ngân sách', 'n'),
  ('tieu-dung-5', 0, 'la publicité', 'quảng cáo', 'n'),
  ('tieu-dung-5', 1, 'la marque', 'thương hiệu', 'n'),
  ('tieu-dung-5', 2, 'le slogan', 'khẩu hiệu', 'n'),
  ('tieu-dung-5', 3, 'cibler', 'nhắm tới', 'v'),
  ('tieu-dung-5', 4, 'inciter', 'thúc giục', 'v'),
  ('tieu-dung-5', 5, 'le consommateur', 'người tiêu dùng', 'n'),
  ('tieu-dung-5', 6, 'mensonger', 'sai sự thật', 'a'),
  ('tieu-dung-5', 7, 'persuasif', 'có sức thuyết phục', 'a'),
  ('tieu-dung-6', 0, 'la surconsommation', 'tiêu dùng quá mức', 'n'),
  ('tieu-dung-6', 1, 'l''achat compulsif', 'mua sắm bốc đồng', 'n'),
  ('tieu-dung-6', 2, 'l''obsolescence programmée', 'lỗi thời có chủ đích', 'n'),
  ('tieu-dung-6', 3, 'le pouvoir d''achat', 'sức mua', 'n'),
  ('tieu-dung-6', 4, 's''endetter', 'mắc nợ', 'v'),
  ('tieu-dung-6', 5, 'superflu', 'thừa thãi', 'a'),
  ('tieu-dung-6', 6, 'éphémère', 'ngắn ngủi', 'a'),
  ('tieu-dung-6', 7, 'la décroissance', 'sự giảm tăng trưởng', 'n'),
  ('cong-dong-1', 0, 'aider', 'giúp đỡ', 'v'),
  ('cong-dong-1', 1, 'donner', 'cho', 'v'),
  ('cong-dong-1', 2, 'le voisin', 'người hàng xóm', 'n'),
  ('cong-dong-1', 3, 'gentil', 'tốt bụng', 'a'),
  ('cong-dong-1', 4, 'le cadeau', 'món quà', 'n'),
  ('cong-dong-1', 5, 'merci', 'cảm ơn', 'x'),
  ('cong-dong-1', 6, 'ensemble', 'cùng nhau', 'x'),
  ('cong-dong-1', 7, 'prêter', 'cho mượn', 'v'),
  ('cong-dong-2', 0, 'l''association', 'hội', 'n'),
  ('cong-dong-2', 1, 'le membre', 'thành viên', 'n'),
  ('cong-dong-2', 2, 'la réunion', 'buổi họp', 'n'),
  ('cong-dong-2', 3, 'participer', 'tham gia', 'v'),
  ('cong-dong-2', 4, 'organiser', 'tổ chức', 'v'),
  ('cong-dong-2', 5, 'la fête', 'bữa tiệc', 'n'),
  ('cong-dong-2', 6, 'le club', 'câu lạc bộ', 'n'),
  ('cong-dong-2', 7, 'inscrit', 'đã đăng ký', 'a'),
  ('cong-dong-3', 0, 'le bénévole', 'tình nguyện viên', 'n'),
  ('cong-dong-3', 1, 'le bénévolat', 'công việc tình nguyện', 'n'),
  ('cong-dong-3', 2, 's''engager', 'dấn thân', 'v'),
  ('cong-dong-3', 3, 'la collecte', 'đợt quyên góp', 'n'),
  ('cong-dong-3', 4, 'la distribution', 'việc phát chia', 'n'),
  ('cong-dong-3', 5, 'les sans-abri', 'người vô gia cư', 'n'),
  ('cong-dong-3', 6, 'solidaire', 'đoàn kết', 'a'),
  ('cong-dong-3', 7, 'utile', 'có ích', 'a'),
  ('cong-dong-4', 0, 'le lien social', 'gắn kết xã hội', 'n'),
  ('cong-dong-4', 1, 'la fête des voisins', 'ngày hội hàng xóm', 'n'),
  ('cong-dong-4', 2, 'rencontrer', 'gặp gỡ', 'v'),
  ('cong-dong-4', 3, 'la solitude', 'sự cô đơn', 'n'),
  ('cong-dong-4', 4, 's''entraider', 'giúp đỡ nhau', 'v'),
  ('cong-dong-4', 5, 'isolé', 'cô lập', 'a'),
  ('cong-dong-4', 6, 'convivial', 'thân mật', 'a'),
  ('cong-dong-4', 7, 'le quartier', 'khu phố', 'n'),
  ('cong-dong-5', 0, 'la citoyenneté', 'quyền công dân', 'n'),
  ('cong-dong-5', 1, 'l''engagement', 'sự dấn thân', 'n'),
  ('cong-dong-5', 2, 'le service civique', 'nghĩa vụ công dân tự nguyện', 'n'),
  ('cong-dong-5', 3, 'militer', 'hoạt động đấu tranh', 'v'),
  ('cong-dong-5', 4, 'mobiliser', 'huy động', 'v'),
  ('cong-dong-5', 5, 'la cause', 'sự nghiệp', 'n'),
  ('cong-dong-5', 6, 'altruiste', 'vị tha', 'a'),
  ('cong-dong-5', 7, 'bénévole', 'tự nguyện', 'a'),
  ('cong-dong-6', 0, 'la précarité', 'sự bấp bênh', 'n'),
  ('cong-dong-6', 1, 'l''exclusion', 'sự loại trừ', 'n'),
  ('cong-dong-6', 2, 'la pauvreté', 'cảnh nghèo đói', 'n'),
  ('cong-dong-6', 3, 'le don', 'khoản quyên góp', 'n'),
  ('cong-dong-6', 4, 'financer', 'tài trợ', 'v'),
  ('cong-dong-6', 5, 'soutenir', 'ủng hộ', 'v'),
  ('cong-dong-6', 6, 'démuni', 'túng thiếu', 'a'),
  ('cong-dong-6', 7, 'généreux', 'hào phóng', 'a'),
  ('truyen-thong-1', 0, 'le journal', 'tờ báo', 'n'),
  ('truyen-thong-1', 1, 'la radio', 'đài phát thanh', 'n'),
  ('truyen-thong-1', 2, 'la télévision', 'truyền hình', 'n'),
  ('truyen-thong-1', 3, 'le magazine', 'tạp chí', 'n'),
  ('truyen-thong-1', 4, 'lire', 'đọc', 'v'),
  ('truyen-thong-1', 5, 'écouter', 'nghe', 'v'),
  ('truyen-thong-1', 6, 'l''article', 'bài báo', 'n'),
  ('truyen-thong-1', 7, 'les informations', 'tin tức', 'n'),
  ('truyen-thong-2', 0, 'la chaîne', 'kênh truyền hình', 'n'),
  ('truyen-thong-2', 1, 'l''émission', 'chương trình', 'n'),
  ('truyen-thong-2', 2, 'le présentateur', 'người dẫn chương trình', 'n'),
  ('truyen-thong-2', 3, 'la météo', 'dự báo thời tiết', 'n'),
  ('truyen-thong-2', 4, 'le documentaire', 'phim tài liệu', 'n'),
  ('truyen-thong-2', 5, 'le direct', 'chương trình trực tiếp', 'n'),
  ('truyen-thong-2', 6, 'regarder', 'xem', 'v'),
  ('truyen-thong-2', 7, 'zapper', 'chuyển kênh', 'v'),
  ('truyen-thong-3', 0, 'le journaliste', 'nhà báo', 'n'),
  ('truyen-thong-3', 1, 'l''interview', 'cuộc phỏng vấn', 'n'),
  ('truyen-thong-3', 2, 'le reportage', 'phóng sự', 'n'),
  ('truyen-thong-3', 3, 'enquêter', 'điều tra', 'v'),
  ('truyen-thong-3', 4, 'le titre', 'tít báo', 'n'),
  ('truyen-thong-3', 5, 'la une', 'trang nhất', 'n'),
  ('truyen-thong-3', 6, 'rédiger', 'soạn thảo', 'v'),
  ('truyen-thong-3', 7, 'l''actualité', 'thời sự', 'n'),
  ('truyen-thong-4', 0, 's''informer', 'tìm hiểu tin tức', 'v'),
  ('truyen-thong-4', 1, 'l''abonnement', 'việc đặt mua dài hạn', 'n'),
  ('truyen-thong-4', 2, 'quotidien', 'hằng ngày', 'a'),
  ('truyen-thong-4', 3, 'hebdomadaire', 'hằng tuần', 'a'),
  ('truyen-thong-4', 4, 'mensuel', 'hằng tháng', 'a'),
  ('truyen-thong-4', 5, 'en ligne', 'trên mạng', 'x'),
  ('truyen-thong-4', 6, 'le lecteur', 'độc giả', 'n'),
  ('truyen-thong-4', 7, 'l''auditeur', 'thính giả', 'n'),
  ('truyen-thong-5', 0, 'la liberté de la presse', 'tự do báo chí', 'n'),
  ('truyen-thong-5', 1, 'la censure', 'sự kiểm duyệt', 'n'),
  ('truyen-thong-5', 2, 'censurer', 'kiểm duyệt', 'v'),
  ('truyen-thong-5', 3, 'l''indépendance', 'sự độc lập', 'n'),
  ('truyen-thong-5', 4, 'la déontologie', 'đạo đức nghề nghiệp', 'n'),
  ('truyen-thong-5', 5, 'impartial', 'vô tư', 'a'),
  ('truyen-thong-5', 6, 'engagé', 'có lập trường', 'a'),
  ('truyen-thong-5', 7, 'le scoop', 'tin độc quyền', 'n'),
  ('truyen-thong-6', 0, 'l''audience', 'lượng khán giả', 'n'),
  ('truyen-thong-6', 1, 'le sensationnalisme', 'lối giật gân', 'n'),
  ('truyen-thong-6', 2, 'décrypter', 'giải mã', 'v'),
  ('truyen-thong-6', 3, 'diffuser', 'phát sóng', 'v'),
  ('truyen-thong-6', 4, 'la rédaction', 'toà soạn', 'n'),
  ('truyen-thong-6', 5, 'fiable', 'đáng tin cậy', 'a'),
  ('truyen-thong-6', 6, 'partial', 'thiên vị', 'a'),
  ('truyen-thong-6', 7, 'le média', 'phương tiện truyền thông', 'n'),
  ('nghien-1', 0, 'la cigarette', 'điếu thuốc', 'n'),
  ('nghien-1', 1, 'fumer', 'hút thuốc', 'v'),
  ('nghien-1', 2, 'le fumeur', 'người hút thuốc', 'n'),
  ('nghien-1', 3, 'interdit', 'bị cấm', 'a'),
  ('nghien-1', 4, 'le briquet', 'bật lửa', 'n'),
  ('nghien-1', 5, 'la fumée', 'khói', 'n'),
  ('nghien-1', 6, 'arrêter', 'dừng lại', 'v'),
  ('nghien-1', 7, 'le paquet', 'bao thuốc', 'n'),
  ('nghien-2', 0, 'tousser', 'ho', 'v'),
  ('nghien-2', 1, 'respirer', 'thở', 'v'),
  ('nghien-2', 2, 'les poumons', 'phổi', 'n'),
  ('nghien-2', 3, 'dangereux', 'nguy hiểm', 'a'),
  ('nghien-2', 4, 'la toux', 'cơn ho', 'n'),
  ('nghien-2', 5, 'fatigué', 'mệt mỏi', 'a'),
  ('nghien-2', 6, 'le souffle', 'hơi thở', 'n'),
  ('nghien-2', 7, 'mauvais', 'có hại', 'a'),
  ('nghien-3', 0, 'le patch', 'miếng dán', 'n'),
  ('nghien-3', 1, 'le sevrage', 'việc cai nghiện', 'n'),
  ('nghien-3', 2, 'l''envie', 'cơn thèm', 'n'),
  ('nghien-3', 3, 'résister', 'kháng cự', 'v'),
  ('nghien-3', 4, 'rechuter', 'tái nghiện', 'v'),
  ('nghien-3', 5, 'tenir bon', 'giữ vững', 'x'),
  ('nghien-3', 6, 'le tabacologue', 'chuyên gia cai thuốc lá', 'n'),
  ('nghien-3', 7, 'motivé', 'có động lực', 'a'),
  ('nghien-4', 0, 'l''alcool', 'rượu', 'n'),
  ('nghien-4', 1, 'la drogue', 'ma tuý', 'n'),
  ('nghien-4', 2, 'dépendant', 'lệ thuộc', 'a'),
  ('nghien-4', 3, 'l''addiction', 'chứng nghiện', 'n'),
  ('nghien-4', 4, 'boire', 'uống', 'v'),
  ('nghien-4', 5, 'consommer', 'sử dụng', 'v'),
  ('nghien-4', 6, 'l''excès', 'sự quá độ', 'n'),
  ('nghien-4', 7, 'nocif', 'có hại', 'a'),
  ('nghien-5', 0, 'la prévention', 'sự phòng ngừa', 'n'),
  ('nghien-5', 1, 'sensibiliser', 'nâng cao nhận thức', 'v'),
  ('nghien-5', 2, 'la campagne', 'chiến dịch', 'n'),
  ('nghien-5', 3, 'le paquet neutre', 'bao thuốc trơn', 'n'),
  ('nghien-5', 4, 'la taxe', 'thuế', 'n'),
  ('nghien-5', 5, 'interdire', 'cấm', 'v'),
  ('nghien-5', 6, 'le vapotage', 'việc hút thuốc lá điện tử', 'n'),
  ('nghien-5', 7, 'mineur', 'vị thành niên', 'a'),
  ('nghien-6', 0, 'la toxicomanie', 'chứng nghiện ma tuý', 'n'),
  ('nghien-6', 1, 'la réduction des risques', 'giảm thiểu tác hại', 'n'),
  ('nghien-6', 2, 'dépénaliser', 'bỏ hình sự hoá', 'v'),
  ('nghien-6', 3, 'le lobby', 'nhóm vận động hành lang', 'n'),
  ('nghien-6', 4, 'la santé mentale', 'sức khoẻ tâm thần', 'n'),
  ('nghien-6', 5, 'accro', 'nghiện', 'a'),
  ('nghien-6', 6, 'illicite', 'bất hợp pháp', 'a'),
  ('nghien-6', 7, 'légal', 'hợp pháp', 'a');
